### ISSUE TITLE
All “TestJlmRemote” tests failed on Test_openjdk8_hs_sanity.system_x86-64_linux

### ISSUE THREAD

**Issue by austin0** [AdoptOpenJDK/openjdk-tests#1903] opened 2020-07-20 13:21 UTC
**Describe the bug**
All “TestJlmRemote” test cases fail after 30 mins.

**To Reproduce**
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.system_x86-64_linux/467/console
```
20:20:58  CL1 j> 2020/07/19 19:20:58.315 ServerURL=service:jmx:rmi:///jndi/rmi://localhost:1234/jmxrmi
20:20:58  CL1 j> 2020/07/19 19:20:58.376 Trying to connect using JMXConnectorFactory
20:21:09  CL1 j> 2020/07/19 19:21:08.815 Monitored VM not ready at Jul 19, 2020 7:21:08 PM (attempt 0).
20:21:09  CL1 j> 2020/07/19 19:21:08.815 Wait 10 secs and trying again...
20:21:09  CL1 j> 2020/07/19 19:21:08.815 Trying to connect using JMXConnectorFactory
20:25:49  CL1 j> 2020/07/19 19:25:34.511 Monitored VM not ready at Jul 19, 2020 7:25:34 PM (attempt 1).
20:25:49  CL1 j> 2020/07/19 19:25:34.512 Wait 10 secs and trying again...
20:25:49  CL1 j> 2020/07/19 19:25:34.512 Trying to connect using JMXConnectorFactory
20:25:58  STF 19:25:57.231 - Heartbeat: Process CL1 is still running
20:28:07  CL1 j> 2020/07/19 19:27:51.954 Monitored VM not ready at Jul 19, 2020 7:27:51 PM (attempt 2).
20:28:07  CL1 j> 2020/07/19 19:27:51.955 Wait 10 secs and trying again...
20:28:07  CL1 j> 2020/07/19 19:27:51.955 Trying to connect using JMXConnectorFactory

...

20:48:36  CL1 j> 2020/07/19 19:48:29.385 Monitored VM not ready at Jul 19, 2020 7:48:29 PM (attempt 11).
20:48:36  CL1 j> 2020/07/19 19:48:29.385 Wait 10 secs and trying again...
20:48:36  CL1 j> 2020/07/19 19:48:29.387 Trying to connect using JMXConnectorFactory
20:51:00  CL1 j> 2020/07/19 19:50:46.824 Monitored VM not ready at Jul 19, 2020 7:50:46 PM (attempt 12).
20:51:00  CL1 j> 2020/07/19 19:50:46.827 Wait 10 secs and trying again...
20:51:00  CL1 j> 2020/07/19 19:50:46.827 Trying to connect using JMXConnectorFactory
20:51:00  STF 19:50:57.088 - Heartbeat: Process CL1 is still running
20:51:09  STF 19:51:08.146 - **FAILED** Process LT1 has ended unexpectedly
20:51:09  STF 19:51:08.146 - Monitoring Report Summary:
20:51:09  STF 19:51:08.146 -   o Process CL1 is still running
20:51:09  STF 19:51:08.146 -   o Process LT1 has ended unexpectedly
20:51:09  STF 19:51:08.147 - Killing processes: CL1 LT1
20:51:20  STF 19:51:19.154 -   o Process CL1 killed
20:51:20  STF 19:51:19.154 -   o Process LT1 is not running
20:51:20  **FAILED** at step 3 (Wait for processes to complete). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk8_hs_sanity.system_x86-64_linux/openjdk-tests/TKG/../TKG/test_output_15951799453776/TestJlmRemoteMemoryNoAuth_SE80_Linux_0/20200719-192055-TestJlmRemoteMemoryNoAuth/execute.pl line 157.
20:51:20  STF 19:51:19.501 - **FAILED** execute script failed. Expected return value=0 Actual=1
```

**Expected behavior**
```
19:11:18  CL1 j> 2020/07/18 11:11:18.052 ServerURL=service:jmx:rmi:///jndi/rmi://localhost:1234/jmxrmi
19:11:18  CL1 j> 2020/07/18 11:11:18.076 Trying to connect using JMXConnectorFactory
19:11:29  CL1 j> 2020/07/18 11:11:28.303 Monitored VM not ready at Jul 18, 2020 11:11:28 AM (attempt 0).
19:11:29  CL1 j> 2020/07/18 11:11:28.303 Wait 10 secs and trying again...
19:11:29  CL1 j> 2020/07/18 11:11:28.303 Trying to connect using JMXConnectorFactory
19:11:29  CL1 j> 2020/07/18 11:11:28.976 Connection established!
19:11:30  CL1 j> 2020/07/18 11:11:29.758 Starting to write data
```
**Additional context**
Similar issue raised in the OpenJ9 repository for jdk14 here: https://github.com/eclipse/openj9/issues/10156
Potentially a network problem on the machine.

**Comment by adamfarley** [comment] 2020-07-20 14:49
I think this is a duplicate of https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/246

**Comment by lumpfish** [comment] 2020-11-11 10:29
Closing as duplicate of https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/246 (now fixed).

**Closed** 2020-11-11 10:29 UTC
Labels: bug, duplicate
