### ISSUE TITLE
openjdk8_hs_external_sanity_payara-mp-tck_x86-64_linux failing

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-tests#1160] opened 2019-06-04 10:19 UTC
External test openjdk8_hs_external_sanity_payara-mp-tck_x86-64_linux is failing with:
```
05:31:27  [[1;31mERROR[m] Failed to execute goal on project [36mtck-runner[m: [1;31mCould not resolve dependencies for project fish.payara.microprofile.rest-client:tck-runner:jar:1.0: Failed to collect dependencies at org.glassfish.jersey.ext:mp-rest-client:jar:2.29.payara-p1-SNAPSHOT[m: Failed to read artifact descriptor for org.glassfish.jersey.ext:mp-rest-client:jar:2.29.payara-p1-SNAPSHOT: Could not transfer artifact org.glassfish.jersey.ext:mp-rest-client:pom:2.29.payara-p1-SNAPSHOT from/to payara-staging (https://nexus.payara.fish/content/repositories/payara-staging/): Not authorized , ReasonPhrase:Unauthorized. -> [1m[Help 1][m
```
e.g. https://ci.adoptopenjdk.net/job/openjdk8_hs_external_sanity_payara-mp-tck_x86-64_linux/73/console.

According to Jenkins the test last ran successfully on 26th Apr 2019: https://ci.adoptopenjdk.net/job/openjdk8_hs_external_sanity_payara-mp-tck_x86-64_linux/.
There have been changes between the two runs - for instance I notice that in the failing job, the 'Build' step ends with
```
04:53:00  dist:
04:53:00       [copy] Copying 3 files to /home/jenkins/workspace/openjdk8_hs_external_sanity_payara-mp-tck_x86-64_linux/jvmtest/external
```
whereas in the passing job, the 'Build' step ends with
```
04:59:14  dist:
04:59:14       [copy] Copying 3 files to /home/jenkins/workspace/openjdk8_hs_external_sanity_payara-mp-tck_x86-64_linux/jvmtest/thirdparty_containers/payara-mp-tck
```
The openj9 builds also fail in the same way.

**Comment by sophia-guo** [comment] 2019-06-04 20:28
The change is caused by renaming thirdparty_containers to external. https://github.com/AdoptOpenJDK/openjdk-tests/pull/1164 will also copy each test set to its own folders to make it more clear, which won't fix the test errors.

**Comment by lumpfish** [comment] 2019-06-06 15:14
I've rerun the test locally with the same build as the last time the test passed (https://ci.adoptopenjdk.net/job/openjdk8_j9_external_sanity_payara-mp-tck_x86-64_linux/29/console) and it also failed with the same error as that reported in the issue description.

**Comment by lumpfish** [comment] 2019-06-06 15:47
If the test is run via
```
make _payara_microprofile_tck_0
```
The the docker container running the test is deleted at the end of the run:
```
[ERROR] Failed to execute goal on project tck-runner: Could not resolve dependencies for project fish.payara.microprofile.rest-client:tck-runner:jar:1.0: Failed to collect dependencies at org.glassfish.jersey.ext:mp-rest-client:jar:2.29.payara-p1-SNAPSHOT: Failed to read artifact descriptor for org.glassfish.jersey.ext:mp-rest-client:jar:2.29.payara-p1-SNAPSHOT: Could not transfer artifact org.glassfish.jersey.ext:mp-rest-client:pom:2.29.payara-p1-SNAPSHOT from/to payara-staging (https://nexus.payara.fish/content/repositories/payara-staging/): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf fish.payara.microprofile.rest-client:tck-runner

payara_microprofile_tck_0_FAILED

Error: No such container:path: payara-mp-tck:/testResults/junitreports
payara-mp-tck
Untagged: adoptopenjdk-payara-mp-tck:latest
Deleted: sha256:0513dcf672af2fd6fb82a760f8402a4b513e8f610a8c3211adf7d46d923770bc
Deleted: sha256:9a51da35419377a33a9223b0d10c94ded2d461665ca4f95b7ec025fab1bccdab
Deleted: sha256:757e2da8599e3b7b8f799ad989e032a533b67e8aa0c406bb03562c8f09dabe62
Deleted: sha256:c168df095149ef43ef70afa2a9f4d89f5fa39d8208fb7ccd8bdcbea28f3bfd5c
Deleted: sha256:267ca585110f8802c7d4378e5a67e0744ed2c4c94139fa6f9208b39cf7f195a9
Deleted: sha256:851d5578025a1ec4135183a083674d650f56f4f285190894006935679520771a
Deleted: sha256:5a6ee8c328e769540dc2b0c34c60708da401eb1d9d236964747a34272e275f7d
Deleted: sha256:ef02b998525b478dcae44cf8946c2259c7ade8ac7b665facb3c3e3a06386f529
Deleted: sha256:281a28fa330ff638c024f0f1986513f85c5117c2cb47a2387110a6246dadd8ab
Deleted: sha256:6e45e825b78967891ed76f99dcd4f85a59301b9e26a67928a3369a77a562c8ad
Deleted: sha256:dda16f85db5b5139e6eaec5d8b19000f17c013d42dbd66c51b8c62692274175a
Deleted: sha256:34b64aa4cdc9a3e0bd46c430e1152936da78e49243c9418761eb5b1065fd2352
Deleted: sha256:72761e4a32e694622f50fd1fa067283382209e4a0e10a2f10edcadfc4fde26ab
Deleted: sha256:2c1420378d4e425af14a1eb1b05443585479089552eba2a55140bc20e38e3560
Deleted: sha256:d0d178916b1e72519b16d7487f5c1a217e32816bdb8ecf590fc370781c23d029
Deleted: sha256:dd71046274ea0591f3e91360c8329f5ddb5039b1d3c0dc66542df790bbb4a538
"/tmp/jdk8u/download/openjdkbinary/j2sdk-image/jre/bin/java" -Xshareclasses:destroyAll; "/tmp/jdk8u/download/openjdkbinary/j2sdk-image/jre/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
JVMSHRC005I No shared class caches available
JVMSHRC005I No shared class caches available
cache cleanup done
payara_microprofile_tck_0 Finish Time: Thu Jun  6 15:46:54 2019 Epoch Time (ms): 1559832414452
make[3]: Leaving directory '/disk2/git/openjdk-tests/external/payara-mp-tck'
make[2]: Leaving directory '/disk2/git/openjdk-tests/external'
make[1]: Leaving directory '/disk2/git/openjdk-tests'
```
@sophia-guo - is there some way to tell the test to keep the containers?  Alternatively are there any instructions of how to run the tests outside docker?

**Comment by sophia-guo** [comment] 2019-06-06 16:05
@lumpfish if you are running it locally you can simply edit texternal/payara-mp-tck/playlist.xml to remove the line

```
		 docker rm -f payara-mp-tck; \
			 docker rmi -f adoptopenjdk-payara-mp-tck
```

**Comment by sophia-guo** [comment] 2019-06-06 16:11
To run it outside docker you will need:
1. export JAVA_HOME
2. git clone https://github.com/payara/MicroProfile-TCK-Runners
3. cd MicroProfile-TCK-Runners
4. mvn clean verify -Dpayara.version=5.184 -pl !MicroProfile-OpenTracing/tck-runner,!MicroProfile-JWT-Auth,!MicroProfile-JWT-Auth/tck-arquillian-extension,!MicroProfile-JWT-Auth/tck-runner

**Comment by lumpfish** [comment] 2019-06-10 13:04
Reproduced the error outside of docker as follows:
1. export JAVA_HOME
2. Add JAVA_HOME/bin to PATH
3. git clone https://github.com/payara/MicroProfile-TCK-Runners
4. cd MicroProfile-TCK-Runners
5. mvn clean verify -Dpayara.version=5.184 -f MicroProfile-Rest-Client/tck-runner

This page was also helpful: https://github.com/payara/MicroProfile-TCK-Runners/blob/master/README.md

The error reported is
```
[ERROR] Failed to execute goal on project tck-runner: Could not resolve dependencies for project fish.payara.microprofile.rest-client:tck-runner:jar:1.0: Failed to collect dependencies at org.glassfish.jersey.ext:mp-rest-client:jar:2.29.payara-p1-SNAPSHOT: Failed to read artifact descriptor for org.glassfish.jersey.ext:mp-rest-client:jar:2.29.payara-p1-SNAPSHOT: Could not transfer artifact org.glassfish.jersey.ext:mp-rest-client:pom:2.29.payara-p1-SNAPSHOT from/to payara-staging (https://nexus.payara.fish/content/repositories/payara-staging/): Not authorized , ReasonPhrase:Unauthorized.
```
The error occurs both with the latest openjdk nightly builds and with jdk8u212-b03 which would be very close to the level at which we know the tests previously passed.  I am assuming at this point that the error does not lie in the jdk.

**Comment by lumpfish** [comment] 2019-06-10 13:21
Raised https://github.com/payara/MicroProfile-TCK-Runners/issues/42 to see if the payara community can see where the problem lies.

**Comment by smlambert** [comment] 2019-06-10 13:31
Wonderful, thanks @lumpfish !

**Comment by smlambert** [comment] 2020-02-22 18:11
closing this as we will track all type:external Reported upstream issues via https://github.com/AdoptOpenJDK/openjdk-tests/issues/587

**Closed by smlambert** 2020-02-22 18:11 UTC
Labels: Reported/Fixed Upstream, bug, type:external
