### ISSUE TITLE
jdk_lang: java/lang/Math/HypotTests.java Intermittent failure : Failed. Execution failed: `main' threw exception: java.lang.RuntimeException

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#128] opened 2017-10-03 17:34 UTC
<pre>
17:57:32 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException
17:57:32 REASON: Assumed action based on file name: run main HypotTests 
17:57:32 TIME:   0.807 seconds
17:57:32 messages:
17:57:32 command: main HypotTests
17:57:32 reason: Assumed action based on file name: run main HypotTests 
17:57:32 Mode: agentvm
17:57:32 Agent id: 2
17:57:32 elapsed time (seconds): 0.807
17:57:32 configuration:
17:57:32 Boot Layer
17:57:32   class path: /home/jenkins/workspace/test_x86-64_linux_experimental/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar
17:57:32               /home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar
17:57:32               /home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar
17:57:32 
17:57:32 Test Layer
17:57:32   class path: /home/jenkins/workspace/test_x86-64_linux_experimental/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/lang/Math/HypotTests.d
17:57:32               /home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/lang/Math
17:57:32 
17:57:32 rerun:
17:57:32 HOME=/home/jenkins \
17:57:32 LANG=en_US.UTF-8 \
17:57:32 PATH=/bin:/usr/bin \
17:57:32     /home/jenkins/workspace/test_x86-64_linux_experimental/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
17:57:32         -Dtest.class.path.prefix=/home/jenkins/workspace/test_x86-64_linux_experimental/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/lang/Math/HypotTests.d:/home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/lang/Math \
17:57:32         -Dtest.src=/home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/lang/Math \
17:57:32         -Dtest.src.path=/home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/lang/Math \
17:57:32         -Dtest.classes=/home/jenkins/workspace/test_x86-64_linux_experimental/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/lang/Math/HypotTests.d \
17:57:32         -Dtest.class.path=/home/jenkins/workspace/test_x86-64_linux_experimental/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/lang/Math/HypotTests.d \
17:57:32         -Dtest.vm.opts='-ea -esa -Xmx512m' \
17:57:32         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
17:57:32         -Dtest.compiler.opts= \
17:57:32         -Dtest.java.opts= \
17:57:32         -Dtest.jdk=/home/jenkins/workspace/test_x86-64_linux_experimental/openjdkbinary/j2sdk-image/jre/bin/../.. \
17:57:32         -Dcompile.jdk=/home/jenkins/workspace/test_x86-64_linux_experimental/openjdkbinary/j2sdk-image/jre/bin/../.. \
17:57:32         -Dtest.timeout.factor=4.0 \
17:57:32         -classpath /home/jenkins/workspace/test_x86-64_linux_experimental/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/lang/Math/HypotTests.d:/home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/lang/Math:/home/jenkins/workspace/test_x86-64_linux_experimental/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
17:57:32         HypotTests
17:57:32 STDERR:
17:57:32 Failure for Math.hypot:
17:57:32 	For inputs -3.2700772948558615E306	(-0x1.2a081aae75f48p1018) and -4.3601030598078155E306	(-0x1.8d60239347f0bp1018)
17:57:32 	expected  5.4501288247597695E306	(0x1.f0b82c7819ecep1018)
17:57:32 	got       5.450128824759769E306	(0x1.f0b82c7819ecdp1018);
17:57:32 	difference greater than ulp tolerance 2.5
17:57:32 Testing the hypot incurred 1 failures.
17:57:32 java.lang.RuntimeException
17:57:32 	at HypotTests.main(HypotTests.java:241)
17:57:32 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:57:32 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:57:32 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:57:32 	at java.lang.reflect.Method.invoke(Method.java:498)
17:57:32 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
17:57:32 	at java.lang.Thread.run(Thread.java:748)
17:57:32 
17:57:32 JavaTest Message: Test threw exception: java.lang.RuntimeException
17:57:32 JavaTest Message: shutting down test
17:57:32 
17:57:32 
17:57:32 TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException
</pre>

**Comment by akolarkunnu** [comment] 2018-03-15 08:37
It is a duplicate of openjdk bug https://bugs.openjdk.java.net/browse/JDK-8078672.

**Comment by smlambert** [comment] 2018-03-18 02:02
Closing as now listed in summary issue #345

**Closed by smlambert** 2018-03-18 02:02 UTC
Labels: Reported/Fixed Upstream, bug
