### ISSUE TITLE
MauveMultiThreadLoadTest_0 and others FAILED in Test_openjdk14_hs_sanity.system_aarch64_linux

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#1891] opened 2020-07-15 14:44 UTC
**Test Info**
Test Name: MauveMultiThreadLoadTest_0
Test Duration: 7 sec
Machine: test-aws-rhel76-armv8-3
TRSS link for the test output: https://trss.adoptopenjdk.net/output/test?id=5f0edf597eaab3443ca8494c

**Build Info**
Build Name: Test_openjdk14_hs_sanity.system_aarch64_linux
Jenkins Build start time: Jul 15 2020, 05:39 am
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk14_hs_sanity.system_aarch64_linux/140/
TRSS link for the build: https://trss.adoptopenjdk.net/allTestsInfo?buildId=5f0eded87eaab3443ca84781

**Java Version**
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)

**This test has been failed 19 times since Jun 25 2020, 04:45 pm**
**Java Version when the issue first seen**
[0.025s][error][cds] Unable to map CDS archive -- os::vm_allocation_granularity() expected: 65536 actual: 4096
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7-202006252018)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7-202006252018, mixed mode)
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk14_hs_sanity.system_aarch64_linux/122/

The test failed on machine test-aws-rhel76-armv8-3 5 times 
The test failed on machine test-aws-rhel76-armv8-6 1 times 
The test failed on machine test-aws-rhel76-armv8-5 3 times 
The test failed on machine test-packet-ubuntu1604-armv8-2 1 times 
The test failed on machine test-aws-rhel76-armv8-2 1 times 
The test failed on machine test-aws-rhel76-armv8-4 1 times 
The test failed on machine test-aws-ubuntu1804-armv8-1 3 times 
The test failed on machine test-aws-rhel76-armv8-1 3 times 
The test failed on machine test-packet-ubuntu1604-armv8-1 1 times 

2 other Mauve tests are also failing consistently for a long time:
MauveSingleInvocationLoadTest_HotSpot_0 ([deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5f0edf597eaab3443ca8495f))
and 
MauveSingleThreadLoadTest_HotSpot_0 ([deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5f0edf597eaab3443ca84938)) 

--------------

**Console output:** 

```
[2020-07-15T10:35:42.981Z] LT  10:35:42.632 - First failure detected by thread: load-0. Not creating dumps as no dump generation is requested for this load test
[2020-07-15T10:35:43.401Z] LT  10:35:43.152 - Uncaught exception: 
[2020-07-15T10:35:43.401Z] LT  java.lang.StackOverflowError: null
[2020-07-15T10:35:43.401Z] LT  	at java.lang.Throwable.getLocalizedMessage(Throwable.java:398) ~[?:?]
[2020-07-15T10:35:43.401Z] LT  	at java.lang.Throwable.toString(Throwable.java:497) ~[?:?]
[2020-07-15T10:35:43.401Z] LT  	at java.lang.String.valueOf(String.java:3388) ~[?:?]
[2020-07-15T10:35:43.401Z] LT  	at java.io.PrintStream.println(PrintStream.java:1047) ~[?:?]
[2020-07-15T10:35:43.401Z] LT  	at java.lang.Throwable$WrappedPrintStream.println(Throwable.java:764) ~[?:?]
[2020-07-15T10:35:43.401Z] LT  	at java.lang.Throwable.printStackTrace(Throwable.java:671) ~[?:?]
[2020-07-15T10:35:43.401Z] LT  	at java.lang.Throwable.printStackTrace(Throwable.java:660) ~[?:?]
[2020-07-15T10:35:43.401Z] LT  	at java.lang.Throwable.printStackTrace(Throwable.java:651) ~[?:?]
[2020-07-15T10:35:43.401Z] LT  	at net.adoptopenjdk.loadTest.reporting.OutputFilter.write(OutputFilter.java:60) ~[bin/:?]
...
[2020-07-15T10:35:45.826Z] LT  10:35:45.682 -   Ran     : 2743
[2020-07-15T10:35:45.826Z] LT  10:35:45.682 -   Passed  : 2740
[2020-07-15T10:35:45.826Z] LT  10:35:45.683 -   Failed  : 0
[2020-07-15T10:35:45.826Z] LT  10:35:45.683 -   Uncaught: 3
[2020-07-15T10:35:45.826Z] LT  10:35:45.683 -   Result  : FAILED
[2020-07-15T10:35:45.826Z] STF 10:35:45.740 - **FAILED** Process LT  ended with exit code (1) and not the expected exit code/s (0)
[2020-07-15T10:35:45.826Z] STF 10:35:45.740 - Monitoring Report Summary:
[2020-07-15T10:35:45.826Z] STF 10:35:45.741 -   o Process LT  ended with exit code (1) and not the expected exit code/s (0)
[2020-07-15T10:35:45.826Z] STF 10:35:45.741 - Killing processes: LT 
[2020-07-15T10:35:45.826Z] STF 10:35:45.741 -   o Process LT  is not running
[2020-07-15T10:35:45.826Z] **FAILED** at step 1 (Run Mauve load test). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk14_hs_sanity.system_aarch64_linux/openjdk-tests/TKG/../TKG/test_output_1594806171798/MauveMultiThreadLoadTest_0/20200715-103538-MauveMultiThreadLoadTest/execute.pl line 94.
[2020-07-15T10:35:45.826Z] STF 10:35:45.775 - **FAILED** execute script failed. Expected return value=0 Actual=1
```

**Comment by smlambert** [comment] 2020-07-15 17:00
related: https://github.com/AdoptOpenJDK/stf/pull/83

**Comment by smlambert** [comment] 2020-11-10 15:12
Given https://github.com/AdoptOpenJDK/stf/pull/83 has been merged, should validate this issue has been fixed & close.  

FYI @lumpfish

**Comment by smlambert** [comment] 2021-01-06 02:49
The mauve test targets were renamed (MauveMultiThrdLoad), but are still failing (not with StackOverflowError, but with a test case failure, console output from [recent jdk15 run](https://ci.adoptopenjdk.net/job/Test_openjdk15_hs_sanity.system_aarch64_linux/148/tapResults/)):

```
LT  20:49:18.732 - Test failed
LT    Failure num.  = 1
LT    Test number   = 1899
LT    Test details  = 'Mauve[gnu.testlet.java.lang.Math.strictfp_modifier.cos]'
LT    Suite number  = 0
LT    Thread number = 2
LT  >>> Captured test output >>>
LT  PASS: gnu.testlet.java.lang.Math.strictfp_modifier.cos (number 0)
LT  PASS: gnu.testlet.java.lang.Math.strictfp_modifier.cos (number 1)
LT  PASS: gnu.testlet.java.lang.Math.strictfp_modifier.cos (number 2)
LT  FAIL: gnu.testlet.java.lang.Math.strictfp_modifier.cos (number 3)
LT  got -4616189728938546314 but expected -4616189728938546315
```

**Comment by lumpfish** [comment] 2021-01-06 16:59
It looks like this is a hotspot aarch64 (> jdk8) specific issue where Math.cos inside a static function with a strictfp modifier is not returning the expected value.
It may be that the strictfp modifier is not being honored, or that StrictMath.cos itself returns the wrong value. I'll try top create a test case to narrow it down.

**Comment by lumpfish** [comment] 2021-01-07 15:38
I have created a standalone test case (
[StrictfpTest.java.txt](https://github.com/AdoptOpenJDK/openjdk-tests/files/5782504/StrictfpTest.java.txt)
) from the failing mauve test case which if I understand what the strictfp class modifier is meant to do correctly (to guarantee strictfp operations for all methods within the class with the strictfp modifier), appears to show 
that the strictfp modifier simply does not work.
The test:
1. Declares a class with the strictfp modifier
2. Executes StrictMath.cos, and Math.cos inside a static method, a non-static method and a method which is also defined with the strictfp modifer
3. Executes StrictMath.exp, and Math.exp inside a static method, a non-static method and a method which is also defined with the strictfp modifer

Where the Math operations result in different values to their StrictMath counterparts (which is permissible according to the specification) those values are not overridden by the StrictMath result.

Here are two examples from running the test (jdk15 aarch64 and jdk8 x86-64_linux) :
```
java -cp . StrictfpTest
Running on:
os.arch: aarch64
os.name: Linux
java.runtime.version: 15.0.1+9-202101062031
java.vm.name: OpenJDK 64-Bit Server VM
java.vm.version: 15.0.1+9-202101062031
To recalibrate the reference values:
Set outputValueCos variable to -0.99998768942656
Set outputValueExp variable to 0.29428694035725067
strictfp Math.cos: got -4616189728938546314 , expected -4616189728938546315
Fail
non static Math.cos: got -4616189728938546314 , expected -4616189728938546315
Fail
static Math.cos: got -4616189728938546314 , expected -4616189728938546315
Fail
strictMath.cos: got -4616189728938546315 , expected -4616189728938546315
Pass
strictfp Math.exp: got 4598973022137637590 , expected 4598973022137637590
Pass
non static Math.exp: got 4598973022137637590 , expected 4598973022137637590
Pass
static Math.exp: got 4598973022137637590 , expected 4598973022137637590
Pass
strictMath.exp: got 4598973022137637590 , expected 4598973022137637590
Pass
```
Example 2:
```
java -cp . StrictfpTest
Running on:
os.arch: amd64
os.name: Linux
java.runtime.version: 1.8.0_275-b01
java.vm.name: OpenJDK 64-Bit Server VM
java.vm.version: 25.275-b01
To recalibrate the reference values:
Set outputValueCos variable to -0.9999876894265599
Set outputValueExp variable to 0.2942869403572507
strictfp Math.cos: got -4616189728938546315 , expected -4616189728938546315
Pass
non static Math.cos: got -4616189728938546315 , expected -4616189728938546315
Pass
static Math.cos: got -4616189728938546315 , expected -4616189728938546315
Pass
strictMath.cos: got -4616189728938546315 , expected -4616189728938546315
Pass
strictfp Math.exp: got 4598973022137637591 , expected 4598973022137637590
Fail
non static Math.exp: got 4598973022137637591 , expected 4598973022137637590
Fail
static Math.exp: got 4598973022137637591 , expected 4598973022137637590
Fail
strictMath.exp: got 4598973022137637590 , expected 4598973022137637590
Pass
```

**Comment by smlambert** [comment] 2021-01-12 16:21
That is an interesting/subtle discovery @lumpfish ... 

I am curious what if any openjdk test material exercises strictfp modifier (not that a straight-forward test case would catch this issue, as you say, it does read like you need a specific case where they return different to then verify the strictfp behaviour).

**Comment by lumpfish** [comment] 2021-01-12 17:28
Browsing the openjdk code has confused me further - in https://github.com/AdoptOpenJDK/openjdk-jdk15u/blob/61c35054bd4b320479c1764a790cfb2c82909f3e/src/java.base/share/classes/java/lang/Math.java the implementations of Math.cos and Math.exp look like they just delegate to StrictMath.cos and StrictMath.exp anyway - so how can they give different results?
The output is the same if I run with `-Xint` (and `-XX:+PrintCompilation` to make sure nothing is being compiled).

**Comment by andrew-m-leonard** [comment] 2021-01-25 20:24
The following disables the Math.exp() intrinsic on jdk-17, and makes your testcase pass:
```
 java -XX:+UnlockDiagnosticVMOptions -XX:DisableIntrinsic=_dexp StrictfpTest
```
With Intrinsics disabled, Math.exp() uses this function: https://github.com/openjdk/jdk/blob/05a764f4ffb8030d6b768f2d362c388e5aabd92d/src/hotspot/share/runtime/sharedRuntimeTrans.cpp#L238

With Intrinsics on it uses this: https://github.com/openjdk/jdk/blob/b78cd633f6b885a6a3059042df8dd38bee43c21e/src/hotspot/cpu/x86/stubGenerator_x86_64.cpp#L6310

StrictMath.exp() uses native C library:
FdLibm.Exp.compute(a);

My reading of the spec and this article lead me to believe that a user method specifying strictfp will not make its use of java.lang.Math.exp() strictfp:
https://en.wikipedia.org/wiki/Strictfp

**Comment by aahlenst** [comment] 2021-01-25 20:54
exp is buggy on 32 bit x86 if that's the question. I dug into it a while ago and the resolution is either to fix the assembler 🤢, ask Intel for a fix or remove the intrinsic. Never came around doing any of those. If it's not about that, sorry for the noise.

**Comment by andrew-m-leonard** [comment] 2021-01-25 21:08
The java Math.exp() specification states:
```
The computed result must be within 1 ulp of the exact result. Results must be semi-monotonic.
```
So in the above example: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1891#issuecomment-756192451
Math.exp(-1.2232D) exact to 20dp: 0.**2942869403572507**1819
So Java Math.exp() with 16-bit double 1ulp accuracy is:
```
0.2942869403572507 or
0.2942869403572508
```

**Comment by andrew-m-leonard** [comment] 2021-01-25 21:09
@aahlenst thanks that is useful, it quite possibly is.

**Comment by aahlenst** [comment] 2021-01-25 21:15
See also https://github.com/AdoptOpenJDK/openjdk-support/issues/182.

**Comment by andrew-m-leonard** [comment] 2021-01-25 21:17
> The mauve test targets were renamed (MauveMultiThrdLoad), but are still failing (not with StackOverflowError, but with a test case failure, console output from [recent jdk15 run](https://ci.adoptopenjdk.net/job/Test_openjdk15_hs_sanity.system_aarch64_linux/148/tapResults/)):
> 
> ```
> LT  20:49:18.732 - Test failed
> LT    Failure num.  = 1
> LT    Test number   = 1899
> LT    Test details  = 'Mauve[gnu.testlet.java.lang.Math.strictfp_modifier.cos]'
> LT    Suite number  = 0
> LT    Thread number = 2
> LT  >>> Captured test output >>>
> LT  PASS: gnu.testlet.java.lang.Math.strictfp_modifier.cos (number 0)
> LT  PASS: gnu.testlet.java.lang.Math.strictfp_modifier.cos (number 1)
> LT  PASS: gnu.testlet.java.lang.Math.strictfp_modifier.cos (number 2)
> LT  FAIL: gnu.testlet.java.lang.Math.strictfp_modifier.cos (number 3)
> LT  got -4616189728938546314 but expected -4616189728938546315
> ```

I'm suspecting those Mauve testcases are not valid, it's implying you can alter the ulp accuracy of a called functional libary, which I don't think you can reading the Java strictfp spec.
Where is the Mauve source for these tests?

**Comment by andrew-m-leonard** [comment] 2021-01-26 08:42
Confirmed from OpenJDK: https://mail.openjdk.java.net/pipermail/core-libs-dev/2021-January/073458.html

**Comment by lumpfish** [comment] 2021-01-26 10:29
@andrew-m-leonard - thank you for getting to the bottom of this.  From what you have established the test cases are invalid (though I can see how the spec might be misinterpreted here: https://docs.oracle.com/javase/specs/jls/se7/html/jls-15.html#jls-15.4).

The mauve test cases are downloaded and built as part of the openjdk-systemtest repository build (see https://www.sourceware.org/mauve/cvs.html for the cvs repository location of the files) , and then inventory files used in the load tests specify exactly which tests within the test suite to run.  I'll create a PR to exclude these tests from the inventory(-ies).

**Comment by lumpfish** [comment] 2021-01-26 12:18
In fact the non-strictfp equivalent test fails in the same way (not surprising since that is effectively what the strictfp test actually is).  That test will also need to be excluded because its assumption is that the Math.cos result will be the same as that hard coded into the test from a reference implementation whereas in fact the result may vary by 1 ulp ( https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#cos-double- ).
There are also additional subtests which fail as described in https://github.com/AdoptOpenJDK/openjdk-tests/issues/2120 where NaN is not returned unchanged on aarch64.  Excluding the test will also exclude those subtests, which at this point I assume are failing because of a real jdk issue,

**Comment by lumpfish** [comment] 2021-02-04 16:36
This is fixed (tests excluded) by https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/400, closing.

**Closed by lumpfish** 2021-02-04 16:36 UTC
Labels: triage required, type:system
