### ISSUE TITLE
Mac ： jdk_sound ：javax/sound/midi/Devices/InitializationHang.java failed with Execution failed: `main' threw exception: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#136] opened 2017-10-04 19:05 UTC
<pre>
22:48:35 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.UnsatisfiedLinkError: /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/lib/libfontmanager.dylib: dlopen(/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/lib/libfontmanager.dylib, 1): Library not loaded: /Users/jenkins/workspace/openjdk_build_x86-64_macos/openjdk/installedfreetype/lib/libfreetype.6.dylib Referenced from: /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/lib/libfontmanager.dylib Reason: image not found
22:48:35 REASON: Assumed action based on file name: run main InitializationHang 
22:48:35 TIME:   3.06 seconds
22:48:35 messages:
22:48:35 command: main InitializationHang
22:48:35 reason: Assumed action based on file name: run main InitializationHang 
22:48:35 Mode: othervm
22:48:35 elapsed time (seconds): 3.06
22:48:35 configuration:
22:48:35 STDOUT:
22:48:35 STDERR:
22:48:35 2017-10-03 13:48:33.067 java[68473:33415094] 13:48:33.066 ERROR:     MIDIClientLib.cpp:199: Initialize: Couldn't connect to com.apple.midiserver; CoreMIDI will not be usable
22:48:35 2017-10-03 13:48:33.068 java[68473:33415094] 13:48:33.068 ERROR:     ObjectTreeCache.h:54: ObjectTreeAccessor: ObjectTreeCache: refresh status 268435459
22:48:35 2017-10-03 13:48:33.069 java[68473:33415094] 13:48:33.069 ERROR:     ObjectTreeCache.h:54: ObjectTreeAccessor: ObjectTreeCache: refresh status 268435459
22:48:35 java.lang.UnsatisfiedLinkError: /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/lib/libfontmanager.dylib: dlopen(/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/lib/libfontmanager.dylib, 1): Library not loaded: /Users/jenkins/workspace/openjdk_build_x86-64_macos/openjdk/installedfreetype/lib/libfreetype.6.dylib
22:48:35   Referenced from: /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/lib/libfontmanager.dylib
22:48:35   Reason: image not found
22:48:35 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
22:48:35 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
22:48:35 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
22:48:35 	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
22:48:35 	at java.lang.System.loadLibrary(System.java:1122)
22:48:35 	at sun.lwawt.macosx.LWCToolkit$1.run(LWCToolkit.java:93)
22:48:35 	at sun.lwawt.macosx.LWCToolkit$1.run(LWCToolkit.java:80)
22:48:35 	at java.security.AccessController.doPrivileged(Native Method)
22:48:35 	at sun.lwawt.macosx.LWCToolkit.<clinit>(LWCToolkit.java:79)
22:48:35 	at java.lang.Class.forName0(Native Method)
22:48:35 	at java.lang.Class.forName(Class.java:264)
</pre>

**Comment by smlambert** [comment] 2017-12-01 20:21
Image not found, seems we are missing a library: 
j2sdk-image/jre/lib/libfontmanager.dylib

**Comment by karianna** [comment] 2017-12-02 20:19
@smlambert I can confirm that this should exist.

**Comment by akolarkunnu** [comment] 2018-01-05 09:44
Here actual error message is 
"Library not loaded: /Users/jenkins/workspace/openjdk_build_x86-64_macos/openjdk/installedfreetype/lib/libfreetype.6.dylib Referenced from: /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/lib/libfontmanager.dylib"
So we are missing the library libfreetype.6.dylib not libfontmanager.dylib.
Also I can confirm that both libfreetype.6.dylib and libfontmanager.dylib are exist in jre/lib directory. But it is referring to the location "/Users/jenkins/workspace/openjdk_build_x86-64_macos/openjdk/installedfreetype/lib" for libfreetype.6.dylib.
It should refer to jre/lib for libfreetype.6.dylib.
So it has to correct in build configuration. This freetype related scripts are there in files https://github.com/AdoptOpenJDK/openjdk-build/blob/master/makejdk.sh makejdk-any-platform.sh sbin/common-functions.sh

**Comment by akolarkunnu** [comment] 2018-01-05 09:47
https://github.com/AdoptOpenJDK/openjdk-tests/issues/137 is a duplicate of this bug.

**Comment by akolarkunnu** [comment] 2018-01-15 10:34
There are a lot of other test cases also fails because of this reason:
java/beans/EventHandler/Test6179222.java
java/beans/EventHandler/Test6788531.java
java/beans/PropertyChangeSupport/Test4682386.java
java/beans/PropertyChangeSupport/TestSynchronization.java
java/beans/PropertyEditor/6380849/TestPropertyEditor.java
java/beans/PropertyEditor/TestFontClass.java
java/beans/PropertyEditor/TestFontClassJava.java
java/beans/PropertyEditor/TestFontClassNull.java
etc

About 35 test cases fails because of this.

**Comment by akolarkunnu** [comment] 2018-01-15 10:35
So I would suggest to prioritize the the openjdk-build bug https://github.com/AdoptOpenJDK/openjdk-build/issues/202

**Comment by sophia-guo** [comment] 2018-01-15 15:34
#135 is a duplicate of this according to comment above.

**Comment by akolarkunnu** [comment] 2018-01-15 16:26
#135 need not be a duplicate of this, java.lang.Error: could not find editor for class java.awt.Color can happen if test machine is headless. Also that happen in both linux and mac. Nevertheless, let's validate that once this bug is resolved.

**Comment by akolarkunnu** [comment] 2018-02-06 11:01
New failure because of this:
com/sun/jdi/RedefineCrossEvent.java

**Comment by smlambert** [comment] 2018-02-06 13:38
Mani provided a build (with the changes in PR [openjdk-build/216](https://github.com/AdoptOpenJDK/openjdk-build/pull/216)), that seem to correct the missing libfreetype lib problem.  The few remaining failures are likely related to the [x11 server issue](https://github.com/AdoptOpenJDK/openjdk-tests/issues/49)

**Comment by smlambert** [comment] 2018-03-18 02:48
Closing as now listed in summary issue #346

**Closed by smlambert** 2018-03-18 02:48 UTC
Labels: bug, java8, mac
