### ISSUE TITLE
Mac: java/rmi/activation/rmidViaInheritedChannel/InheritedChannelNotServerSocket.java TestFailedException: TEST FAILED: rmid not destroyed in: 60000 milliseconds

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#154] opened 2017-10-16 15:49 UTC
19:55:39 ACTIVATION_LIBRARY: Activation System available after 0 milliseconds
19:55:39 RMID: getting a reference to the activation system
19:55:39 RMID: obtained a reference to the activation system
19:55:39 TEST FAILED: reference to the activation system was null
19:55:39 RMID: caught exception trying to shutdown rmid
19:55:39 RMID: TEST FAILED: reference to the activation system was null
19:55:39 TestFailedException: TEST FAILED: reference to the activation system was null
19:55:39 	at TestLibrary.bomb(TestLibrary.java:121)
19:55:39 	at TestLibrary.bomb(TestLibrary.java:124)
19:55:39 	at RMID.shutdown(RMID.java:291)
19:55:39 	at RMID.destroy(RMID.java:313)
19:55:39 	at ActivationLibrary$DestroyThread.run(ActivationLibrary.java:220)
19:55:39 RMID: testlibrary finished shutting down rmid
19:55:39 RMID: RMID's process still not terminated after more than 200 milliseconds
19:55:39 RMID: RMID's process still not terminated after more than 400 milliseconds

**Comment by smlambert** [comment] 2017-12-01 01:13
@sophia-guo I am guessing this is java8.  

Just a thought that for any new issues we put a link to the test (either to the job in Jenkins, although we don't keep too many of those around, or the test in the playlist with a note on how to run to reproduce, in this case I guess this test belongs in this test suite: https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk_regression/playlist.xml#L337 and could be rerun by "make jdk_rmi_SE80_0"

**Comment by sophia-guo** [comment] 2017-12-01 21:23
Yes, should add more information to reproduce.

All issues created by now are java8 specific. Locally we don't have a separate ProblemList.txt for java9. Though we haven't got a chance to see whole java9 test build behavior by default  tests will be exclude in java9 test build.

To rerun:

1. Search the class name in ProblemList.txt find the exclude line and comment the line
 (Here: java/rmi/activation/rmidViaInheritedChannel/InheritedChannelNotServerSocket.java 154 macosx-all) 
2. Above the line find the group test belongs to
(Here, jdk_rmi)
3. make jdk_rmi_SE80_0

Probably need to update README again. :-)

**Comment by akolarkunnu** [comment] 2018-03-15 08:38
It is a duplicate of openjdk bug https://bugs.openjdk.java.net/browse/JDK-8170562

**Comment by smlambert** [comment] 2018-03-18 02:00
Closing as now listed in summary issue #345

**Closed by smlambert** 2018-03-18 02:00 UTC
Labels: Reported/Fixed Upstream, bug, java8, mac
