### ISSUE TITLE
mac : jdk_tools : tools/launcher/TestSpecialArgs.java failed with Execution failed: `main' threw exception: java.lang.RuntimeException: Tests failed: 1

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#133] opened 2017-10-04 17:39 UTC
<pre>
23:07:30 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Tests failed: 1
23:07:30 REASON: User specified action: run main TestSpecialArgs 
23:07:30 TIME:   8.617 seconds
23:07:30 messages:
23:07:30 command: main TestSpecialArgs
23:07:30 reason: User specified action: run main TestSpecialArgs 
23:07:30 Mode: agentvm
23:07:30 Agent id: 1
23:07:30 elapsed time (seconds): 8.617
23:07:30 configuration:
23:07:30 Boot Layer
23:07:30   class path: /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar
23:07:30               /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar
23:07:30               /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar
23:07:30 
23:07:30 Test Layer
23:07:30   class path: /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/tools/launcher/TestSpecialArgs.d
23:07:30               /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/tools/launcher
23:07:30 
23:07:30 rerun:
23:07:30 HOME=/Users/jenkins \
23:07:30 PATH=/bin:/usr/bin \
23:07:30     /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
23:07:30         -Dtest.class.path.prefix=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/tools/launcher/TestSpecialArgs.d:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/tools/launcher \
23:07:30         -Dtest.src=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/tools/launcher \
23:07:30         -Dtest.src.path=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/tools/launcher \
23:07:30         -Dtest.classes=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/tools/launcher/TestSpecialArgs.d \
23:07:30         -Dtest.class.path=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/tools/launcher/TestSpecialArgs.d \
23:07:30         -Dtest.vm.opts='-ea -esa -Xmx512m' \
23:07:30         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
23:07:30         -Dtest.compiler.opts= \
23:07:30         -Dtest.java.opts= \
23:07:30         -Dtest.jdk=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../.. \
23:07:30         -Dcompile.jdk=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../.. \
23:07:30         -Dtest.timeout.factor=4.0 \
23:07:30         -classpath /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/tools/launcher/TestSpecialArgs.d:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/tools/launcher:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
23:07:30         TestSpecialArgs
23:07:30 STDOUT:
23:07:30 testDocking: OK
23:07:30 Passed: 1, Failed: 0, ExitValue: 0
23:07:30 testNativeMemoryTracking: OK
23:07:30 Passed: 2, Failed: 0, ExitValue: 2
23:07:30 Test void TestSpecialArgs.testNMArgumentProcessing() throws java.io.FileNotFoundException failed: java.lang.reflect.InvocationTargetException 
23:07:30 ----begin detailed exceptions----
23:07:30 java.lang.reflect.InvocationTargetException
23:07:30 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:07:30 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:07:30 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:07:30 	at java.lang.reflect.Method.invoke(Method.java:498)
23:07:30 	at TestHelper.run(TestHelper.java:214)
23:07:30 	at TestSpecialArgs.main(TestSpecialArgs.java:42)
23:07:30 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:07:30 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:07:30 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:07:30 	at java.lang.reflect.Method.invoke(Method.java:498)
23:07:30 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
23:07:30 	at java.lang.Thread.run(Thread.java:748)
23:07:30 Caused by: java.lang.RuntimeException: Test Fails
23:07:30 	at TestSpecialArgs.checkTestResult(TestSpecialArgs.java:284)
23:07:30 	at TestSpecialArgs.testNMArgumentProcessing(TestSpecialArgs.java:251)
23:07:30 	... 12 more
23:07:30 ----end detailed exceptions----
23:07:30 Total: Passed: 2, Failed 1
23:07:30 STDERR:
23:07:30 Executed command: /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/bin/java -version -XX:NativeMemoryTracking=summary 
</pre>

**Comment by smlambert** [comment] 2017-12-01 18:17
Extracted from test output:
TestSpecialArgs.testNMArgumentProcessing() throws java.io.FileNotFoundException failed: java.lang.reflect.InvocationTargetException 
23:07:30 ----begin detailed exceptions----

What file does this test expect to find?  Are we missing some test material?

**Comment by akolarkunnu** [comment] 2018-01-16 01:55
I rerun this test case on linux and mac, and not able to reproduce. Also this test case added in ProblemList_openjdk8.txt by referring to bug 115, not 133. This bug is only for mac platform, but it added in ProblemList_openjdk8.txt for generic.

**Comment by akolarkunnu** [comment] 2018-01-16 02:14
Created a PR https://github.com/AdoptOpenJDK/openjdk-tests/pull/219

**Comment by akolarkunnu** [comment] 2018-01-16 04:39
It resolved by PR #219

**Closed by akolarkunnu** 2018-01-16 04:39 UTC
Labels: bug, java8, mac
