### ISSUE TITLE
jdk_tools: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#115] opened 2017-10-02 18:16 UTC
<pre>
00:28:35 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
00:28:35 REASON: User specified action: run main/timeout=60 TestJstatdServer 
00:28:35 TIME:   11.605 seconds
00:28:35 messages:
00:28:35 command: main TestJstatdServer
00:28:35 reason: User specified action: run main/timeout=60 TestJstatdServer 
00:28:35 Mode: agentvm
00:28:35 Agent id: 2
00:28:35 elapsed time (seconds): 11.605
00:28:35 configuration:
00:28:35 Boot Layer
00:28:35   class path: /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar
00:28:35               /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar
00:28:35               /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar
00:28:35 
00:28:35 Test Layer
00:28:35   class path: /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/sun/tools/jstatd/TestJstatdServer.d
00:28:35               /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/sun/tools/jstatd
00:28:35               /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/lib/testlibrary
00:28:35               /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/lib/testlibrary
00:28:35 
00:28:35 rerun:
00:28:35 HOME=/home/jenkins \
00:28:35 LANG=en_US.UTF-8 \
00:28:35 PATH=/bin:/usr/bin \
00:28:35     /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
00:28:35         -Dtest.class.path.prefix=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/sun/tools/jstatd/TestJstatdServer.d:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/sun/tools/jstatd:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/lib/testlibrary \
00:28:35         -Dtest.src=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/sun/tools/jstatd \
00:28:35         -Dtest.src.path=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/sun/tools/jstatd:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/lib/testlibrary \
00:28:35         -Dtest.classes=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/sun/tools/jstatd/TestJstatdServer.d \
00:28:35         -Dtest.class.path=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/sun/tools/jstatd/TestJstatdServer.d:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/lib/testlibrary \
00:28:35         -Dtest.vm.opts='-ea -esa -Xmx512m' \
00:28:35         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
00:28:35         -Dtest.compiler.opts= \
00:28:35         -Dtest.java.opts= \
00:28:35         -Dtest.jdk=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
00:28:35         -Dcompile.jdk=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
00:28:35         -Dtest.timeout.factor=4.0 \
00:28:35         -classpath /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/sun/tools/jstatd/TestJstatdServer.d:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/sun/tools/jstatd:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/lib/testlibrary:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/lib/testlibrary:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
00:28:35         TestJstatdServer
00:28:35 STDOUT:
00:28:35 
00:28:35 Start jstatd:
00:28:35 [/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/jstatd -J-XX:+UsePerfData -J-Djava.security.policy=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/sun/tools/jstatd/all.policy -J-Dparent.pid.30408 -n TestJstatdServer]
00:28:35 
00:28:35 Start jps:
00:28:35 [/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/jps -J-XX:+UsePerfData -v test-packet-x64-ubuntu-16.04-1/TestJstatdServer]
00:28:35 32288 AgentServer -Djava.security.policy=file:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/../../jvmtest/OpenJDK_Playlist/SE80/work/jtreg.policy
00:28:35 32160 AgentServer -Djava.security.policy=file:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/../../jvmtest/OpenJDK_Playlist/SE80/work/jtreg.policy
00:28:35 2384 Jstatd -Denv.class.path=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar -Dapplication.home=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image -Xms8m -XX:+UsePerfData -Djava.security.policy=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/sun/tools/jstatd/all.policy -Dparent.pid.30408
00:28:35 30371 AgentServer -ea -esa -Xmx512m -Djava.security.policy=file:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/../../jvmtest/OpenJDK_Playlist/SE80/work/jtreg.policy
00:28:35 2451 -- process information unavailable
00:28:35 32131 AgentServer -Djava.security.policy=file:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/../../jvmtest/OpenJDK_Playlist/SE80/work/jtreg.policy
00:28:35 30389 AgentServer -ea -esa -Xmx512m -Djava.security.policy=file:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/../../jvmtest/OpenJDK_Playlist/SE80/work/jtreg.policy
00:28:35 30408 AgentServer -ea -esa -Xmx512m -Djava.security.policy=file:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/../../jvmtest/OpenJDK_Playlist/SE80/work/jtreg.policy
00:28:35 30427 AgentServer -ea -esa -Xmx512m -Djava.security.policy=file:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/../../jvmtest/OpenJDK_Playlist/SE80/work/jtreg.policy
00:28:35 27964 jar
00:28:35 30302 jtreg.jar -Xmx512m
00:28:35 2383 Jps -Denv.class.path=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar -Dapplication.home=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image -Xms8m -XX:+UsePerfData
00:28:35 
00:28:35 jstatd pid: 2384
00:28:35 
00:28:35 Start jps:
00:28:35 [/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/jps -J-XX:+UsePerfData -v test-packet-x64-ubuntu-16.04-1/TestJstatdServer]
00:28:35 32288 AgentServer -Djava.security.policy=file:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/../../jvmtest/OpenJDK_Playlist/SE80/work/jtreg.policy
00:28:35 32160 AgentServer -Djava.security.policy=file:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/../../jvmtest/OpenJDK_Playlist/SE80/work/jtreg.policy
00:28:35 2384 Jstatd -Denv.class.path=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar -Dapplication.home=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image -Xms8m -XX:+UsePerfData -Djava.security.policy=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/sun/tools/jstatd/all.policy -Dparent.pid.30408
00:28:35 30371 AgentServer -ea -esa -Xmx512m -Djava.security.policy=file:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/../../jvmtest/OpenJDK_Playlist/SE80/work/jtreg.policy
00:28:35 32131 AgentServer -Djava.security.policy=file:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/../../jvmtest/OpenJDK_Playlist/SE80/work/jtreg.policy
00:28:35 30389 AgentServer -ea -esa -Xmx512m -Djava.security.policy=file:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/../../jvmtest/OpenJDK_Playlist/SE80/work/jtreg.policy
00:28:35 30408 AgentServer -ea -esa -Xmx512m -Djava.security.policy=file:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/../../jvmtest/OpenJDK_Playlist/SE80/work/jtreg.policy
00:28:35 30427 AgentServer -ea -esa -Xmx512m -Djava.security.policy=file:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/../../jvmtest/OpenJDK_Playlist/SE80/work/jtreg.policy
00:28:35 27964 jar
00:28:35 30302 jtreg.jar -Xmx512m
00:28:35 2495 Jps -Denv.class.path=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar -Dapplication.home=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image -Xms8m -XX:+UsePerfData
00:28:35 
00:28:35 
00:28:35 Start jstat:
00:28:35 [/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/jstat -J-XX:+UsePerfData -J-Duser.language=en -gcutil 2384@test-packet-x64-ubuntu-16.04-1/TestJstatdServer 250 5]
00:28:35 Malformed VM Identifier: 2384@test-packet-x64-ubuntu-16.04-1/TestJstatdServer
00:28:35 Usage: jstat -help|-options
00:28:35        jstat -<option> [-t] [-h<lines>] <vmid> [<interval> [<count>]]
00:28:35 
00:28:35 Definitions:
00:28:35   <option>      An option reported by the -options option
00:28:35   <vmid>        Virtual Machine Identifier. A vmid takes the following form:
00:28:35                      <lvmid>[@<hostname>[:<port>]]
00:28:35                 Where <lvmid> is the local vm identifier for the target
00:28:35                 Java virtual machine, typically a process id; <hostname> is
00:28:35                 the name of the host running the target Java virtual machine;
00:28:35                 and <port> is the port number for the rmiregistry on the
00:28:35                 target host. See the jvmstat documentation for a more complete
00:28:35                 description of the Virtual Machine Identifier.
00:28:35   <lines>       Number of samples between header lines.
00:28:35   <interval>    Sampling interval. The following forms are allowed:
00:28:35                     <n>["ms"|"s"]
00:28:35                 Where <n> is an integer and the suffix specifies the units as 
00:28:35                 milliseconds("ms") or seconds("s"). The default units are "ms".
00:28:35   <count>       Number of samples to take before terminating.
00:28:35   -J<flag>      Pass <flag> directly to the runtime system.
00:28:35 
00:28:35 ProcessThread.stopProcess() will kill process
00:28:35 --- ProcessLog ---
00:28:35 cmd: /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/jstatd -J-XX:+UsePerfData -J-Djava.security.policy=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/sun/tools/jstatd/all.policy -J-Dparent.pid.30408 -n TestJstatdServer
00:28:35 exitvalue: 143
00:28:35 stderr: 
00:28:35 stdout: 
00:28:35 
00:28:35 STDERR:
00:28:35  stdout: [];
00:28:35  stderr: [Malformed VM Identifier: 2384@test-packet-x64-ubuntu-16.04-1/TestJstatdServer
00:28:35 Usage: jstat -help|-options
00:28:35        jstat -<option> [-t] [-h<lines>] <vmid> [<interval> [<count>]]
00:28:35 
00:28:35 Definitions:
00:28:35   <option>      An option reported by the -options option
00:28:35   <vmid>        Virtual Machine Identifier. A vmid takes the following form:
00:28:35                      <lvmid>[@<hostname>[:<port>]]
00:28:35                 Where <lvmid> is the local vm identifier for the target
00:28:35                 Java virtual machine, typically a process id; <hostname> is
00:28:35                 the name of the host running the target Java virtual machine;
00:28:35                 and <port> is the port number for the rmiregistry on the
00:28:35                 target host. See the jvmstat documentation for a more complete
00:28:35                 description of the Virtual Machine Identifier.
00:28:35   <lines>       Number of samples between header lines.
00:28:35   <interval>    Sampling interval. The following forms are allowed:
00:28:35                     <n>["ms"|"s"]
00:28:35                 Where <n> is an integer and the suffix specifies the units as 
00:28:35                 milliseconds("ms") or seconds("s"). The default units are "ms".
00:28:35   <count>       Number of samples to take before terminating.
00:28:35   -J<flag>      Pass <flag> directly to the runtime system.
00:28:35 ]
00:28:35  exitValue = 1
00:28:35 
00:28:35 java.lang.RuntimeException: Expected to get exit value of [0]
00:28:35 
00:28:35 	at jdk.testlibrary.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:361)
00:28:35 	at JstatdTest.verifyJstatOutput(JstatdTest.java:246)
00:28:35 	at JstatdTest.runToolsAndVerify(JstatdTest.java:259)
00:28:35 	at JstatdTest.doTest(JstatdTest.java:361)
00:28:35 	at TestJstatdServer.main(TestJstatdServer.java:36)
00:28:35 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:28:35 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:28:35 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:28:35 	at java.lang.reflect.Method.invoke(Method.java:498)
00:28:35 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
00:28:35 	at java.lang.Thread.run(Thread.java:748)
00:28:35 
00:28:35 JavaTest Message: Test threw exception: java.lang.RuntimeException
00:28:35 JavaTest Message: shutting down test
00:28:35 
00:28:35 
00:28:35 TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
</pre>

sun/tools/jstatd/TestJstatdDefaults.java
sun/tools/jstatd/TestJstatdExternalRegistry.java
sun/tools/jstatd/TestJstatdPort.java
sun/tools/jstatd/TestJstatdPortAndServer.java
sun/tools/jstatd/TestJstatdServer.java
tools/launcher/TestSpecialArgs.java

**Comment by akolarkunnu** [comment] 2018-03-15 08:46
It is a duplicate of openjdk bug https://bugs.openjdk.java.net/browse/JDK-8081569.

**Comment by smlambert** [comment] 2018-03-18 01:52
Closing as now listed in summary issue #345

**Closed by smlambert** 2018-03-18 01:52 UTC
Labels: Reported/Fixed Upstream, bug

**Comment by sophia-guo** [comment] 2022-05-16 19:37
jdk8 solaris-x64 https://github.com/adoptium/aqa-tests/issues/3603
