### ISSUE TITLE
hotspot_jre:runtime/ErrorHandling/TestOnOutOfMemoryError.java failed 

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#122] opened 2017-10-02 19:08 UTC
<pre>18:30:53 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'Requested array size exceeds VM limit' missing from stdout/stderr
18:30:53 REASON: User specified action: run main TestOnOutOfMemoryError 
18:30:53 TIME:   0.549 seconds
18:30:53 messages:
18:30:53 command: main TestOnOutOfMemoryError
18:30:53 reason: User specified action: run main TestOnOutOfMemoryError 
18:30:53 Mode: agentvm
18:30:53 Agent id: 3
18:30:53 elapsed time (seconds): 0.549
18:30:53 configuration:
18:30:53 Boot Layer
18:30:53   class path: /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar
18:30:53               /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar
18:30:53               /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar
18:30:53 
18:30:53 Test Layer
18:30:53   class path: /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/runtime/ErrorHandling/TestOnOutOfMemoryError.d
18:30:53               /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/runtime/ErrorHandling
18:30:53               /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/testlibrary
18:30:53               /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/testlibrary
18:30:53 
18:30:53 rerun:
18:30:53 HOME=/home/jenkins \
18:30:53 LANG=en_US.UTF-8 \
18:30:53 PATH=/bin:/usr/bin \
18:30:53     /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
18:30:53         -Dtest.class.path.prefix=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/runtime/ErrorHandling/TestOnOutOfMemoryError.d:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/runtime/ErrorHandling:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/testlibrary \
18:30:53         -Dtest.src=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/runtime/ErrorHandling \
18:30:53         -Dtest.src.path=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/runtime/ErrorHandling:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/testlibrary \
18:30:53         -Dtest.classes=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/runtime/ErrorHandling/TestOnOutOfMemoryError.d \
18:30:53         -Dtest.class.path=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/runtime/ErrorHandling/TestOnOutOfMemoryError.d:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/testlibrary \
18:30:53         -Dtest.vm.opts='-ea -esa -Xmx512m' \
18:30:53         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
18:30:53         -Dtest.compiler.opts= \
18:30:53         -Dtest.java.opts= \
18:30:53         -Dtest.jdk=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
18:30:53         -Dcompile.jdk=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
18:30:53         -Dtest.timeout.factor=4.0 \
18:30:53         -classpath /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/runtime/ErrorHandling/TestOnOutOfMemoryError.d:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/runtime/ErrorHandling:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/testlibrary:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/testlibrary:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
18:30:53         TestOnOutOfMemoryError
18:30:53 STDOUT:
18:30:53 Command line: [/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java -XX:OnOutOfMemoryError=echo Test Succeeded TestOnOutOfMemoryError throwOOME ]
18:30:53 STDERR:
18:30:53  stdout: [];
18:30:53  stderr: [Error: Could not find or load main class TestOnOutOfMemoryError
18:30:53 ]
18:30:53  exitValue = 1
18:30:53 
18:30:53 java.lang.RuntimeException: 'Requested array size exceeds VM limit' missing from stdout/stderr 
18:30:53 
18:30:53 	at com.oracle.java.testlibrary.OutputAnalyzer.shouldContain(OutputAnalyzer.java:134)
18:30:53 	at TestOnOutOfMemoryError.main(TestOnOutOfMemoryError.java:66)
18:30:53 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:30:53 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:30:53 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:30:53 	at java.lang.reflect.Method.invoke(Method.java:498)
18:30:53 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
18:30:53 	at java.lang.Thread.run(Thread.java:748)
18:30:53 
18:30:53 JavaTest Message: Test threw exception: java.lang.RuntimeException
18:30:53 JavaTest Message: shutting down test
18:30:53 
18:30:53 
18:30:53 TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'Requested array size exceeds VM limit' missing from stdout/stderr
18:30:53 --------------------------------------------------
18:30:53 TEST: runtime/handlerInTry/LoadHandlerInTry.java
18:30:53 TEST JDK: /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../..
18:30:53 
18:30:53 ACTION: compile -- Error. can't find jasm
18:30:53 REASON: User specified action: run compile HandlerInTry.jasm 
18:30:53 TIME:   0.001 seconds
18:30:53 messages:
18:30:53 command: compile /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/runtime/handlerInTry/HandlerInTry.jasm
18:30:53 reason: User specified action: run compile HandlerInTry.jasm 
18:30:53 elapsed time (seconds): 0.001
18:30:53 configuration:
18:30:53 rerun:
18:30:53     /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/java \
18:30:53     -classpath  \
18:30:53     org.openjdk.asmtools.jasm.Main -d /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/runtime/handlerInTry/LoadHandlerInTry.d /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/runtime/handlerInTry/HandlerInTry.jasm
18:30:53 
18:30:53 TEST RESULT: Error. can't find jasm

</pre>

**Comment by akolarkunnu** [comment] 2018-03-15 08:20
This is a duplicate of openjdk bug https://bugs.openjdk.java.net/browse/JDK-8180904.

**Comment by smlambert** [comment] 2018-03-18 01:56
Closing as now listed in summary issue #345

**Closed by smlambert** 2018-03-18 01:56 UTC
Labels: Reported/Fixed Upstream, bug
