### ISSUE TITLE
hotspot_jre: runtime/NMT/NMTWithCDS.java fails with Execution failed: `main' threw exception: java.lang.RuntimeException: 'Unable to use shared archive' missing from stdout/stderr

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#124] opened 2017-10-02 19:36 UTC
<pre>
18:18:56 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'Unable to use shared archive' missing from stdout/stderr
18:18:56 REASON: User specified action: run main NMTWithCDS 
18:18:56 TIME:   0.124 seconds
18:18:56 messages:
18:18:56 command: main NMTWithCDS
18:18:56 reason: User specified action: run main NMTWithCDS 
18:18:56 Mode: agentvm
18:18:56 Agent id: 3
18:18:56 elapsed time (seconds): 0.124
18:18:56 configuration:
18:18:56 Boot Layer
18:18:56   class path: /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar
18:18:56               /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar
18:18:56               /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar
18:18:56 
18:18:56 Test Layer
18:18:56   class path: /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/runtime/NMT/NMTWithCDS.d
18:18:56               /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/runtime/NMT
18:18:56               /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/testlibrary
18:18:56               /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/testlibrary
18:18:56 
18:18:56 rerun:
18:18:56 HOME=/home/jenkins \
18:18:56 LANG=en_US.UTF-8 \
18:18:56 PATH=/bin:/usr/bin \
18:18:56     /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
18:18:56         -Dtest.class.path.prefix=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/runtime/NMT/NMTWithCDS.d:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/runtime/NMT:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/testlibrary \
18:18:56         -Dtest.src=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/runtime/NMT \
18:18:56         -Dtest.src.path=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/runtime/NMT:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/testlibrary \
18:18:56         -Dtest.classes=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/runtime/NMT/NMTWithCDS.d \
18:18:56         -Dtest.class.path=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/runtime/NMT/NMTWithCDS.d:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/testlibrary \
18:18:56         -Dtest.vm.opts='-ea -esa -Xmx512m' \
18:18:56         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
18:18:56         -Dtest.compiler.opts= \
18:18:56         -Dtest.java.opts= \
18:18:56         -Dtest.jdk=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
18:18:56         -Dcompile.jdk=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
18:18:56         -Dtest.timeout.factor=4.0 \
18:18:56         -classpath /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/runtime/NMT/NMTWithCDS.d:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/runtime/NMT:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/2/testlibrary:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/testlibrary:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
18:18:56         NMTWithCDS
18:18:56 STDOUT:
18:18:56 Command line: [/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java -XX:SharedArchiveFile=./sample.jsa -Xshare:dump ]
18:18:56 STDERR:
18:18:56  stdout: [];
18:18:56  stderr: [Error: VM option 'SharedArchiveFile' is diagnostic and must be enabled via -XX:+UnlockDiagnosticVMOptions.
18:18:56 Error: Could not create the Java Virtual Machine.
18:18:56 Error: A fatal exception has occurred. Program will exit.
18:18:56 ]
18:18:56  exitValue = 1
18:18:56 
18:18:56  stdout: [];
18:18:56  stderr: [Error: VM option 'SharedArchiveFile' is diagnostic and must be enabled via -XX:+UnlockDiagnosticVMOptions.
18:18:56 Error: Could not create the Java Virtual Machine.
18:18:56 Error: A fatal exception has occurred. Program will exit.
18:18:56 ]
18:18:56  exitValue = 1
18:18:56 
18:18:56 java.lang.RuntimeException: 'Unable to use shared archive' missing from stdout/stderr 
18:18:56 
18:18:56 	at com.oracle.java.testlibrary.OutputAnalyzer.shouldContain(OutputAnalyzer.java:134)
18:18:56 	at NMTWithCDS.main(NMTWithCDS.java:51)
18:18:56 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:18:56 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:18:56 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:18:56 	at java.lang.reflect.Method.invoke(Method.java:498)
18:18:56 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
18:18:56 	at java.lang.Thread.run(Thread.java:748)
18:18:56 
18:18:56 JavaTest Message: Test threw exception: java.lang.RuntimeException
18:18:56 JavaTest Message: shutting down test
18:18:56 
18:18:56 
18:18:56 TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'Unable to use shared archive' missing from stdout/stderr
</pre>

Similar tests failure:
runtime/memory/ReserveMemory.java
ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'SIGSEGV' missing from stdout/stderr
serviceability/jvmti/TestRedefineWithUnresolvedClass.java 
Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]

**Comment by akolarkunnu** [comment] 2018-03-15 08:18
This is a duplicate of openjdk bug https://bugs.openjdk.java.net/browse/JDK-8180936

**Comment by smlambert** [comment] 2018-03-18 01:57
Closing as now listed in summary issue #345

**Closed by smlambert** 2018-03-18 01:57 UTC
Labels: Reported/Fixed Upstream, bug

**Comment by zzambers** [comment] 2023-03-27 19:15
This aggregate bug is little unfortunate . What connects excluded tests referencing this issue is that they use OutputAnalyzer class from testlibrary. This class is used to spawn process and check its stdout/stderr/exit code.  However to analyze these, exception/stack trace is not the interesting part. (with exception saying what was not found in stdout/stderr etc..)

What is more interesting is actual STDOUT/STDERR. In original problem it is following:
```
...
18:18:56 STDOUT:
18:18:56 Command line: [/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java -XX:SharedArchiveFile=./sample.jsa -Xshare:dump ]
18:18:56 STDERR:
18:18:56  stdout: [];
18:18:56  stderr: [Error: VM option 'SharedArchiveFile' is diagnostic and must be enabled via -XX:+UnlockDiagnosticVMOptions.
18:18:56 Error: Could not create the Java Virtual Machine.
18:18:56 Error: A fatal exception has occurred. Program will exit.
18:18:56 ]
18:18:56  exitValue = 1
18:18:56 
18:18:56  stdout: [];
18:18:56  stderr: [Error: VM option 'SharedArchiveFile' is diagnostic and must be enabled via -XX:+UnlockDiagnosticVMOptions.
18:18:56 Error: Could not create the Java Virtual Machine.
18:18:56 Error: A fatal exception has occurred. Program will exit.
18:18:56 ]
18:18:56  exitValue = 1
...
```

Unfortunately it is not clear what was problem with other tests referencing this issue. (Original issue was  JDK-8180936 as commented higher, other issues are unclear)

Anyway all problems seem to be fixed now.
