### ISSUE TITLE
openj9 specific tests being run on hotspot builds in jdk8 pipeline

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-tests#1468] opened 2019-11-27 11:28 UTC
The special.functional test target is trying to compile openj9 shareclasses tests when running on hotspot builds in the jdk8 nightly pipeline.
The first failure was 25/11/2019, previous success was 19/11/2019 (there were no runs of this test in between) - see https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_special.functional_x86-64_linux/

Test test compile step fails with messages like:
```
05:17:27  compile:
05:17:27       [echo] Ant version is Apache Ant(TM) version 1.10.5 compiled on July 10 2018
05:17:27       [echo] ============COMPILER SETTINGS============
05:17:27       [echo] ===fork:                         yes
05:17:27       [echo] ===executable:                   /home/jenkins/workspace/Test_openjdk8_hs_special.functional_x86-64_linux/openjdkbinary/j2sdk-image/bin/javac
05:17:27       [echo] ===debug:                        on
05:17:27       [echo] ===destdir:                      /home/jenkins/workspace/Test_openjdk8_hs_special.functional_x86-64_linux/openjdk-tests/TestConfig/../../jvmtest/functional/CacheManagement
05:17:27      [javac] Compiling 4 source files to /home/jenkins/workspace/Test_openjdk8_hs_special.functional_x86-64_linux/openjdk-tests/functional/CacheManagement/testcodebuild
05:17:28      [javac] Compiling 4 source files to /home/jenkins/workspace/Test_openjdk8_hs_special.functional_x86-64_linux/openjdk-tests/functional/CacheManagement/bin
05:17:28      [javac] Compiling 98 source files to /home/jenkins/workspace/Test_openjdk8_hs_special.functional_x86-64_linux/openjdk-tests/functional/CacheManagement/bin
05:17:29      [javac] /home/jenkins/workspace/Test_openjdk8_hs_special.functional_x86-64_linux/openjdk-tests/functional/CacheManagement/src/tests/sharedclasses/options/TestSharedCacheEnableBCI.java:26: error: package com.ibm.oti.shared does not exist
05:17:29      [javac] import com.ibm.oti.shared.*;
05:17:29      [javac] ^
05:17:29      [javac] /home/jenkins/workspace/Test_openjdk8_hs_special.functional_x86-64_linux/openjdk-tests/functional/CacheManagement/src/tests/sharedclasses/options/TestSharedCacheJavaAPI.java:26: error: package com.ibm.oti.shared does not exist
```
com.ibm.oti.shared is the openj9 sharedclasses package so it is not present in hotspot builds.

**Comment by llxia** [comment] 2019-11-27 14:05
CacheManagement should only compile on openj9 and ibm SDK.
fyi @sophia-guo

**Comment by lumpfish** [comment] 2019-11-27 14:34
Well yes - so why are we trying to build these tests in a hotspot run?

**Comment by smlambert** [comment] 2019-11-27 14:44
These are newly added tests, Lan has tagged Sophia who added them and who will correct this issue.

**Comment by llxia** [comment] 2019-11-28 18:15
PR is merged: https://github.com/eclipse/openj9/pull/7886

Please reopen if the issue still exists.

**Comment by sophia-guo** [comment] 2019-12-06 18:24
Another PR https://github.com/eclipse/openj9/pull/8013

Grinder: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/970/console

**Comment by junyzheng** [comment] 2019-12-06 18:25
I think this issue still exist in the AdoptOpenJDK CI pipeline, refs: 

https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_special.functional_x86-64_linux/136/execution/node/49/log/

**Comment by junyzheng** [comment] 2019-12-06 19:21
I think the issue is this part:

```
<target name="compile" depends="init" description="Using java ${JDK_VERSION} to compile the source ">
		<echo>Ant version is ${ant.version}</echo>
		<echo>============COMPILER SETTINGS============</echo>
		<echo>===fork:                         yes</echo>
		<echo>===executable:                   ${compiler.javac}</echo>
		<echo>===debug:                        on</echo>
		<echo>===destdir:                      ${DEST}</echo>
		<javac srcdir="./testcode" destdir="${testcodebuild}" debug="on" debuglevel="lines,vars,source" executable="${compiler.javac}" includeAntRuntime="false" encoding="ISO-8859-1"/>
		<javac srcdir="./testcode" destdir="${build}" debug="on" debuglevel="lines,vars,source" executable="${compiler.javac}" includeAntRuntime="false" encoding="ISO-8859-1"/>
		<javac destdir="${build}" debug="true" fork="true" executable="${compiler.javac}" includeAntRuntime="false" encoding="ISO-8859-1">
			<src path="${src}"/>
			<classpath>
				<pathelement location="${TEST_ROOT}/TestConfig/lib/junit4.jar" />
			</classpath>
		</javac>
	</target>
```

because the javac is causing the failure

**Comment by junyzheng** [comment] 2019-12-06 19:35
https://github.com/eclipse/openj9/pull/7886

**Comment by sophia-guo** [comment] 2019-12-06 19:46
@junyzheng FYI https://github.com/AdoptOpenJDK/openjdk-tests/issues/1468#issuecomment-562684778. The issue is the default task is `clean` instead of `build`.  Conditional logic is set in the `build` task.

**Comment by sophia-guo** [comment] 2019-12-09 17:11
Close this. Fixed by https://github.com/eclipse/openj9/pull/7886 & https://github.com/eclipse/openj9/pull/8013.

https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_special.functional_x86-64_linux/142/

**Closed by sophia-guo** 2019-12-09 17:11 UTC
Labels: bug
