### ISSUE TITLE
hotspot_jre : ACTION: driver -- Failed. 

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#110] opened 2017-10-02 17:44 UTC
Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of REASON: User specified action: run driver/timeout=720 TestShrinkAuxiliaryData05 

gc/g1/TestShrinkAuxiliaryData05.java
gc/g1/TestShrinkAuxiliaryData10.java
gc/g1/TestShrinkAuxiliaryData15.java
gc/g1/TestShrinkAuxiliaryData20.java

other failed similar tests:
runtime/os/AvailableProcessors.java 
18:30:58 ACTION: driver -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'Found expected processors: ' missing from stdout/stderr
18:30:58 REASON: User specified action: run driver AvailableProcessors

**Comment by akolarkunnu** [comment] 2018-03-15 08:19
This is a duplicate of openjdk bug https://bugs.openjdk.java.net/browse/JDK-8180904.

**Comment by smlambert** [comment] 2018-03-18 01:50
Closing as now listed in summary issue #345

**Closed by smlambert** 2018-03-18 01:50 UTC
Labels: Reported/Fixed Upstream, bug
