### ISSUE TITLE
system test has fatal: Invalid path error when running on wins

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#513] opened 2018-08-16 16:32 UTC
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-win_x86-64_cmprssptrs/3/console

```
11:58:14 clone_stf:
11:58:14      [exec] fatal: Invalid path '/cygdrive/c/Users/jenkins/workspace/Test-sanity.system-JDK8-win_x86-64_cmprssptrs/openjdk-tests/systemtest/C:\Users\jenkins\workspace\Test-sanity.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\systemtest': No such file or directory
11:58:14      [exec] Result: 128
11:58:14      [echo] C:\Users\jenkins\workspace\Test-sanity.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\systemtest/openjdk-systemtest does not exist, clone from GitHub
11:58:14 
11:58:14 clone_systemtest:
11:58:14      [exec] fatal: Invalid path '/cygdrive/c/Users/jenkins/workspace/Test-sanity.system-JDK8-win_x86-64_cmprssptrs/openjdk-tests/systemtest/C:\Users\jenkins\workspace\Test-sanity.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\systemtest': No such file or directory
11:58:14      [exec] Result: 128
11:58:14 
11:58:14 clone_openj9-systemtest:
11:58:14      [exec] fatal: Invalid path '/cygdrive/c/Users/jenkins/workspace/Test-sanity.system-JDK8-win_x86-64_cmprssptrs/openjdk-tests/systemtest/C:\Users\jenkins\workspace\Test-sanity.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\systemtest': No such file or directory
11:58:14      [exec] Result: 128
11:58:14      [echo] C:\Users\jenkins\workspace\Test-sanity.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\systemtest/openj9-systemtest does not exist, clone from GitHub
11:58:14 
11:58:14 clone_openj9-systemtest:
11:58:14      [exec] fatal: Invalid path '/cygdrive/c/Users/jenkins/workspace/Test-sanity.system-JDK8-win_x86-64_cmprssptrs/openjdk-tests/systemtest/C:\Users\jenkins\workspace\Test-sanity.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\systemtest': No such file or directory
11:58:14      [exec] Result: 128
11:58:14 
11:58:14 configure_systemtest:
11:58:14 
11:58:14 BUILD FAILED
11:58:14 C:\Users\jenkins\workspace\Test-sanity.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\TestConfig\scripts\build_test.xml:71: The following error occurred while executing this line:
11:58:14 C:\Users\jenkins\workspace\Test-sanity.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\systemtest\build.xml:181: Basedir C:\Users\jenkins\workspace\Test-sanity.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\systemtest\openj9-systemtest\openj9.build does not exist
```

**Comment by Mesbah-Alam** [comment] 2018-08-16 17:52
Looks like it's constructing wrong path value: `/cygdrive/c/Users/jenkins/workspace/Test-sanity.system-JDK8-win_x86-64_cmprssptrs/openjdk-tests/systemtest/C:\Users\jenkins\workspace\Test-sanity.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\systemtest`

I notice that in /openjdk.build/makefile, we have
 ```ifneq ($(WINDOWS),1)
    OPENJDK_SYSTEMTEST_ROOT:=$(shell cd "$(MAKEFILE_ROOT_DIR)"; pwd)
  else
    OPENJDK_SYSTEMTEST_ROOT:=$(strip $(subst Directory of,,$(shell dir "$(subst $(D),\,$(MAKEFILE_ROOT_DIR))" | findstr $(D)C:"Directory of")))
  endif```
also,
 ```ifeq ($(CYGWIN),1)
    #$(warning Running under cygwin)
    #$(warning Before cygpath OPENJDK_SYSTEMTEST_ROOT set to $(OPENJDK_SYSTEMTEST_ROOT))
    OPENJDK_SYSTEMTEST_ROOT:=$(shell cygpath -m '$(OPENJDK_SYSTEMTEST_ROOT)')
  endif```
Need to find the piece of code that is causing the concatenation of cygwin path and real path to happen: (In the path in the output above, you see, it is : /cygdrive/c/Users/jenkins/workspace/Test-sanity.system-JDK8-win_x86-64_cmprssptrs/openjdk-tests/systemtest  `+` /C:\Users\jenkins\workspace\Test-sanity.system-JDK8-win_x86-64_cmprssptrs\openjdk-tests\systemtest)

**Comment by Mesbah-Alam** [comment] 2018-08-16 17:53
@lumpfish - were these scripts tested on Cygwin environment before?

**Comment by Mesbah-Alam** [comment] 2018-08-16 19:02
Other people seem to have had the same issue of paths being merged as welll : https://github.com/npm/npm/issues/7623 - this suggests it could be a git version issue. 

```
Hooray! This version of git seems to fix it!

$ git --version
git version 1.9.5.msysgit.0
re-installed from: http://git-scm.com/download/win
```
Hi @AdamBrousseau , 
Are we using MSYS on these Windows machines? What's the git version on https://ci.eclipse.org/openj9/computer/win2012r2-x86-4/ ?

**Comment by AdamBrousseau** [comment] 2018-08-16 19:07
Git version 2.17.0 (cygwin git)

**Comment by lumpfish** [comment] 2018-08-20 08:46
The system tests expect to be running in a 'real' Windows environment.  The test makefiles set the SHELL to cmd.exe and set the systemtest root to the correct Windows path name if it finds it is running under cygwin (the code you have highlighted above).
Tools supplied by cygwin may not work correctly in a true windows environment - they may expect only file paths '/' and not 'C:' and '\' for example.
The system tests were developed and tested using the version of the tools ported to mswin32 - git, perl (Strawberry), gnu make.

**Comment by Mesbah-Alam** [comment] 2018-08-20 19:49
I ran a personal build with `-debug` enabled on the Ant script that fails and it reveals this: 

```
15:39:24 clone_stf:
15:39:24      [exec] Current OS is Windows Server 2012 R2
15:39:24      [exec] Executing 'git' with arguments:
15:39:24      [exec] 'clone'
15:39:24      [exec] '--depth'
15:39:24      [exec] '1'
15:39:24      [exec] '--single-branch'
15:39:24      [exec] 'https://github.com/AdoptOpenJDK/stf.git'
15:39:24      [exec] 'C:\Users\j9build\jenkins\workspace\Grinder\openjdk-tests\systemtest/stf'
15:39:24      [exec] 
15:39:24      [exec] The ' characters around the executable and arguments are
15:39:24      [exec] not part of the command.
15:39:24      [exec] fatal: Invalid path '/cygdrive/c/Users/j9build/jenkins/workspace/Grinder/openjdk-tests/systemtest/C:\Users\j9build\jenkins\workspace\Grinder\openjdk-tests\systemtest': No such file or directory```

This is the output from the orignal Ant code:

```
<exec executable="git" failonerror="false">
			<arg value="clone" />
			<arg value="--depth" />
			<arg value="1" />
			<arg value="--single-branch" />
			<arg value="${git-prefix}://github.com/AdoptOpenJDK/stf.git" />
			<arg value="${SYSTEMTEST_ROOT}/stf" />
		</exec>
```

Note, 
 
`${SYSTEMTEST_ROOT}/stf"` is evaluating to a valid path : 'C:\Users\j9build\jenkins\workspace\Grinder\openjdk-tests\systemtest/stf' (as evident in the output above) -- which is fed into the `git` command as the destination in which to check out stf. 

However, the "git" command complains about an invalid path "'/cygdrive/c/Users/j9build/jenkins/workspace/Grinder/openjdk-tests/systemtest/C:\Users\j9build\jenkins\workspace\Grinder\openjdk-tests\systemtest':" 

I suspect this invalid path is being constructed by Git itself. 

@llxia  - Is any other flavor of tests (functional, regression etc) running on Windows on cygwin on any of these Windows cloud machines?

**Comment by llxia** [comment] 2018-08-20 19:55
Both functional and regression runs ok on wins.
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_hs_openjdktest_x86-64_windows/
https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.functional-JDK10-win_x86-64_cmprssptrs/

**Comment by Mesbah-Alam** [comment] 2018-08-20 20:20
Interesting. I am able to reproduce the wrong path issue at an Adopt Windows machine too: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/133/console

**Comment by Mesbah-Alam** [comment] 2018-08-20 20:51
The difference between system tests and functional (and regression) test process is: 
In case of functional (and regression) tests, the involvement of git is only in checking out openjdk-test repo and openj9 repo - these two steps pass in case of systemtest build as well. But in case of systemtest, we have some additional git checkout steps (to checkout stf, openjdk-systemtest) -- this is where it fails.

**Comment by Mesbah-Alam** [comment] 2018-08-21 15:46
On my local Windows machine's Cygwin, I fail to reproduce the issue: 

```
alamm@TP-ALAMM ~
$ git clone --depth 1 --single-branch https://github.com/eclipse/openj9-systemtest.git 'C:\temp\mesbah\openj9-systemtest'
Cloning into 'C:\temp\mesbah\openj9-systemtest'...
remote: Counting objects: 230, done.
remote: Compressing objects: 100% (128/128), done.
remote: Total 230 (delta 72), reused 208 (delta 66), pack-reused 0
Receiving objects: 100% (230/230), 306.59 KiB | 507.00 KiB/s, done.
Resolving deltas: 100% (72/72), done.

alamm@TP-ALAMM ~
$ git --version
git version 2.11.0.windows.3
```
However, running the exact same command on a cloud Windows machine, I can reproduce it: 

```
j9build@win8-mesbah /cygdrive/c/temp/mesbah
$ git clone --depth 1 --single-branch https://github.com/eclipse/openj9-systemtest.git 'C:\temp\mesbah\openj9-systemtest'
Cloning into 'C:\temp\mesbah\openj9-systemtest'...
fatal: Invalid path '/cygdrive/c/temp/mesbah/C:\temp\mesbah\openj9-systemtest': No such file or directory

j9build@win8-mesbah /cygdrive/c/temp/mesbah
$ git --version
git version 2.17.0
```

Note: the git versions of the two places are different.

**Comment by lumpfish** [comment] 2018-08-21 15:48
Works OK for me too with
```
$ git --version
git version 2.11.0.windows.1
```

**Comment by Mesbah-Alam** [comment] 2018-08-21 20:49
This issue points out that we clearly have an issue with Cygwin git which, on certain versions can come up with invalid paths causing git check out to fail. One way to avoid this is to simply not provide a destination "path" to the `git` command, but simply execute the `git` command in a given "working directory". https://github.com/AdoptOpenJDK/openjdk-tests/pull/524 - makes that change.

**Closed** 2018-08-21 20:50 UTC
Labels: bug

**Comment by AdamBrousseau** [comment] 2018-08-21 21:03
If you pass a unix-style path does Cygwin git work properly?
Should `SYSTEMTEST_ROOT` be constructed as a unix-style path if in a unix environment?
