### ISSUE TITLE
Linux: (intermittent failure) jdk_management : java/lang/management/MemoryMXBean/LowMemoryTest2.sh Execution failed: exit code 1 

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#157] opened 2017-10-16 16:11 UTC
19:04:43 ACTION: shell -- Failed. Execution failed: exit code 1
19:04:43 REASON: User specified action: run shell/timeout=600 LowMemoryTest2.sh 
19:04:43 TIME:   5.862 seconds
19:04:43 messages:
19:04:43 command: shell LowMemoryTest2.sh
19:04:43 reason: User specified action: run shell/timeout=600 LowMemoryTest2.sh 
19:04:43 elapsed time (seconds): 5.862
19:04:43 STDOUT:
19:04:43 
19:04:43 + /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java -ea -esa -Xmx512m -noclassgc -XX:MaxMetaspaceSize=16m -XX:+UseSerialGC LowMemoryTest2
19:04:43 Selected memory pool for low memory detection.
19:04:43     Memory Pool name: Code Cache
19:04:43     Type: Non-heap memory
19:04:43     Memory Usage: init = 2555904(2496K) used = 1105408(1079K) committed = 2555904(2496K) max = 251658240(245760K)
19:04:43     Threshold: 201326592
19:04:43     Manager = [CodeCacheManager]
19:04:43 Selected memory pool for low memory detection.
19:04:43     Memory Pool name: Metaspace
19:04:43     Type: Non-heap memory
19:04:43     Memory Usage: init = 0(0K) used = 2632424(2570K) committed = 4980736(4864K) max = 16777216(16384K)
19:04:43     Threshold: 13421772
19:04:43     Manager = [Metaspace Manager]
19:04:43 Selected memory pool for low memory detection.
19:04:43     Memory Pool name: Compressed Class Space
19:04:43     Type: Non-heap memory
19:04:43     Memory Usage: init = 0(0K) used = 281432(274K) committed = 524288(512K) max = 1073741824(1048576K)
19:04:43     Threshold: 858993459
19:04:43     Manager = [Metaspace Manager]
19:04:43 Notification for Metaspace [type = java.management.memory.threshold.exceeded count = 1]
19:04:43     usage = init = 0(0K) used = 13454424(13139K) committed = 15728640(15360K) max = 16777216(16384K)
19:04:43 Notification received - test passed.
19:04:43 
19:04:43 + /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java -ea -esa -Xmx512m -noclassgc -XX:MaxMetaspaceSize=16m -XX:+UseParallelGC LowMemoryTest2
19:04:43 Selected memory pool for low memory detection.
19:04:43     Memory Pool name: Code Cache
19:04:43     Type: Non-heap memory
19:04:43     Memory Usage: init = 2555904(2496K) used = 1104512(1078K) committed = 2555904(2496K) max = 251658240(245760K)
19:04:43     Threshold: 201326592
19:04:43     Manager = [CodeCacheManager]
19:04:43 Selected memory pool for low memory detection.
19:04:43     Memory Pool name: Metaspace
19:04:43     Type: Non-heap memory
19:04:43     Memory Usage: init = 0(0K) used = 2630344(2568K) committed = 4980736(4864K) max = 16777216(16384K)
19:04:43     Threshold: 13421772
19:04:43     Manager = [Metaspace Manager]
19:04:43 Selected memory pool for low memory detection.
19:04:43     Memory Pool name: Compressed Class Space
19:04:43     Type: Non-heap memory
19:04:43     Memory Usage: init = 0(0K) used = 281432(274K) committed = 524288(512K) max = 1073741824(1048576K)
19:04:43     Threshold: 858993459
19:04:43     Manager = [Metaspace Manager]
19:04:43 Exception in thread "Thread-0" java.lang.OutOfMemoryError: Metaspace
19:04:43 	at java.lang.ClassLoader.defineClass1(Native Method)
19:04:43 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
19:04:43 	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
19:04:43 	at LowMemoryTest2$BoundlessLoaderThread.loadNext(LowMemoryTest2.java:134)
19:04:43 	at LowMemoryTest2$BoundlessLoaderThread.run(LowMemoryTest2.java:155)
19:04:43 	at java.lang.Thread.run(Thread.java:748)
19:04:43 Exception in thread "main" java.lang.RuntimeException: Test failed - notification not received!
19:04:43 	at LowMemoryTest2.main(LowMemoryTest2.java:239)
19:04:43 
19:04:43 + /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java -ea -esa -Xmx512m -noclassgc -XX:MaxMetaspaceSize=16m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC LowMemoryTest2
19:04:43 Selected memory pool for low memory detection.
19:04:43     Memory Pool name: Code Cache
19:04:43     Type: Non-heap memory
19:04:43     Memory Usage: init = 2555904(2496K) used = 1106944(1081K) committed = 2555904(2496K) max = 251658240(245760K)
19:04:43     Threshold: 201326592
19:04:43     Manager = [CodeCacheManager]
19:04:43 Selected memory pool for low memory detection.
19:04:43     Memory Pool name: Metaspace
19:04:43     Type: Non-heap memory
19:04:43     Memory Usage: init = 0(0K) used = 2632424(2570K) committed = 4980736(4864K) max = 16777216(16384K)
19:04:43     Threshold: 13421772
19:04:43     Manager = [Metaspace Manager]
19:04:43 Selected memory pool for low memory detection.
19:04:43     Memory Pool name: Compressed Class Space
19:04:43     Type: Non-heap memory
19:04:43     Memory Usage: init = 0(0K) used = 281432(274K) committed = 524288(512K) max = 1073741824(1048576K)
19:04:43     Threshold: 858993459
19:04:43     Manager = [Metaspace Manager]
19:04:43 Notification received - test passed.
19:04:43 Notification for Metaspace [type = java.management.memory.threshold.exceeded count = 1]
19:04:43     usage = init = 0(0K) used = 13454424(13139K) committed = 15728640(15360K) max = 16777216(16384K)
19:04:43 
19:04:43 + /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java -ea -esa -Xmx512m -noclassgc -XX:MaxMetaspaceSize=16m -XX:CompressedClassSpaceSize=4m LowMemoryTest2
19:04:43 Selected memory pool for low memory detection.
19:04:43     Memory Pool name: Code Cache
19:04:43     Type: Non-heap memory
19:04:43     Memory Usage: init = 2555904(2496K) used = 1104640(1078K) committed = 2555904(2496K) max = 251658240(245760K)
19:04:43     Threshold: 201326592
19:04:43     Manager = [CodeCacheManager]
19:04:43 Selected memory pool for low memory detection.
19:04:43     Memory Pool name: Metaspace
19:04:43     Type: Non-heap memory
19:04:43     Memory Usage: init = 0(0K) used = 2630344(2568K) committed = 4980736(4864K) max = 16777216(16384K)
19:04:43     Threshold: 13421772
19:04:43     Manager = [Metaspace Manager]
19:04:43 Selected memory pool for low memory detection.
19:04:43     Memory Pool name: Compressed Class Space
19:04:43     Type: Non-heap memory
19:04:43     Memory Usage: init = 0(0K) used = 281432(274K) committed = 524288(512K) max = 4194304(4096K)
19:04:43     Threshold: 3355443
19:04:43     Manager = [Metaspace Manager]
19:04:43 Notification for Compressed Class Space [type = java.management.memory.threshold.exceeded count = 1]
19:04:43     usage = init = 0(0K) used = 3373968(3294K) committed = 3538944(3456K) max = 4194304(4096K)
19:04:43 Notification received - test passed.
19:04:43 
19:04:43 1 test(s) failed

**Comment by akolarkunnu** [comment] 2018-03-15 08:31
It is a duplicate of openjdk bug https://bugs.openjdk.java.net/browse/JDK-8038822.

**Comment by smlambert** [comment] 2018-03-18 02:05
Closing as now listed in summary issue #345

**Closed by smlambert** 2018-03-18 02:05 UTC
Labels: Reported/Fixed Upstream, bug, java8, linux
