### ISSUE TITLE
pyara mp tck build fails to compile on jdk11

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-tests#669] opened 2018-11-05 18:59 UTC
Pyara mp tck fails to compile on jdk 11 build with following error: 

```

21:14:51 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project microprofile-openapi-tck-runner: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test failed.: NullPointerException -> [Help 1]
21:14:51 [ERROR] 
21:14:51 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
21:14:51 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
21:14:51 [ERROR] 
21:14:51 [ERROR] For more information about the errors and possible solutions, please read the following articles:
21:14:51 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
21:14:51 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
21:14:52 Exception in thread "main" java.lang.NullPointerException
21:14:52 	at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.initializeServiceLocator(AbstractModulesRegistryImpl.java:152)
21:14:52 	at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.newServiceLocator(AbstractModulesRegistryImpl.java:144)
21:14:52 	at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.createServiceLocator(AbstractModulesRegistryImpl.java:218)
21:14:52 	at com.sun.enterprise.module.common_impl.AbstractModulesRegistryImpl.createServiceLocator(AbstractModulesRegistryImpl.java:224)
21:14:52 	at com.sun.enterprise.module.single.StaticModulesRegistry.createServiceLocator(StaticModulesRegistry.java:88)
21:14:52 	at com.sun.enterprise.admin.cli.CLIContainer.getServiceLocator(CLIContainer.java:212)
21:14:52 	at com.sun.enterprise.admin.cli.CLIContainer.getLocalCommand(CLIContainer.java:244)
21:14:52 	at com.sun.enterprise.admin.cli.CLICommand.getCommand(CLICommand.java:229)
21:14:52 	at com.sun.enterprise.admin.cli.AdminMain.executeCommand(AdminMain.java:362)
21:14:52 	at com.sun.enterprise.admin.cli.AdminMain.doMain(AdminMain.java:298)
21:14:52 	at org.glassfish.admin.cli.AsadminMain.main(AsadminMain.java:56)

```

https://ci.adoptopenjdk.net/view/Test_external/job/openjdk11_hs_externaltest_extended_x86-64_linux/32/console

**Comment by smlambert** [comment] 2019-02-06 00:45
Will close this, as its duplicate of #839

**Closed by smlambert** 2019-02-06 00:45 UTC
Labels: bug
