### ISSUE TITLE
sanity.functional jdk11 x86-64_mac cmdLineTest_sigabrtHandlingTest_0 failure: gptest (Not found in java.library.path)

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-tests#2178] opened 2021-01-18 12:22 UTC
Some subtests within the sanity.functional cmdLineTest_sigabrtHandlingTest_0 fail with a `java.lang.UnsatisfiedLinkError: gptest (Not found in java.library.path)` exception.

```
21:39:12  Testing: -XX:-HandleSIGABRT
21:39:12  Test start time: 2021/01/14 21:39:12 Greenwich Mean Time
21:39:12  Running command: bash -c 'ulimit -c 0 ; "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java"   -Xmx20m -Xdump:system+heap+snap+jit:none -XX:-HandleSIGABRT -cp "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar" VMBench.GPTests.GPTest abort'
21:39:12  Time spent starting: 10 milliseconds
21:39:12  Time spent executing: 221 milliseconds
21:39:12  Test result: FAILED
21:39:12  Output from test:
21:39:12   [ERR] Exception in thread "main" java.lang.UnsatisfiedLinkError: gptest (Not found in java.library.path)
21:39:12   [ERR] 	at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1742)
21:39:12   [ERR] 	at java.base/java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1693)
21:39:12   [ERR] 	at java.base/java.lang.System.loadLibrary(System.java:603)
21:39:12   [ERR] 	at VMBench.GPTests.GPTest.<clinit>(GPTest.java:28)
21:39:12  >> Success condition was not found: [Output match: Invoking abort!]
21:39:12  >> Failure condition was not found: [Output match: Processing dump event "abort"]
21:39:12 
```

Other tests seem to find the gptest program OK.  A difference appears to be the failing commands having the `bash -c 'ulimit -c 0 ; ` prefixed to the command.

Full output of failing test (taken from https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.functional_x86-64_mac/63/consoleFull):
```
21:39:11  ===============================================
21:39:11  Running test cmdLineTest_sigabrtHandlingTest_0 ...
21:39:11  ===============================================
21:39:11  cmdLineTest_sigabrtHandlingTest_0 Start Time: Thu Jan 14 21:39:11 2021 Epoch Time (ms): 1610660351047
21:39:11  "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java" -Xshareclasses:destroyAll; "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
21:39:11  JVMSHRC005I No shared class caches available
21:39:11  JVMSHRC005I No shared class caches available
21:39:11  cache cleanup done
21:39:11  variation: NoOptions
21:39:11  JVM_OPTIONS:  
21:39:11  { itercnt=1; \
21:39:11  	mkdir -p "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/../TKG/test_output_16106584546121/cmdLineTest_sigabrtHandlingTest_0"; \
21:39:11  	cd "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/../TKG/test_output_16106584546121/cmdLineTest_sigabrtHandlingTest_0"; \
21:39:11  	export DYLD_LIBRARY_PATH="/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdkbinary/openjdk-test-image/openj9:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/../lib/compressedrefs:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/../lib/j9vm:"; \
21:39:11  	"/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java"   \
21:39:11  	-DRESJAR="/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar" \
21:39:11  	-DEXE='"/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java"  ' \
21:39:11  	-jar "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/../../jvmtest/functional/cmdline_options_tester/cmdlinetester.jar" \
21:39:11  	-config  "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/sigabrtHandlingTest/sigabrtHandlingTest.xml" -verbose -explainExcludes -xids all,osx_x86-64_cr, -plats all,osx_x86-64_cr, -nonZeroExitWhenError; \
21:39:11  	if [ $? -eq 0 ] ; then echo ""; echo "cmdLineTest_sigabrtHandlingTest_0""_PASSED"; echo ""; cd /Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/..;  else echo ""; echo "cmdLineTest_sigabrtHandlingTest_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/../TKG/test_output_16106584546121/TestTargetResult";
21:39:11  *** Starting test suite: SIGABRT Handling Tests ***
21:39:11  Testing: Default
21:39:11  Test start time: 2021/01/14 21:39:11 Greenwich Mean Time
21:39:11  Running command: "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java"   -Xmx20m -Xdump:system+heap+snap+jit:none -cp "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar" VMBench.GPTests.GPTest abort
21:39:12  Time spent starting: 60 milliseconds
21:39:12  Time spent executing: 292 milliseconds
21:39:12  Test result: PASSED
21:39:12  Output from test:
21:39:12   [OUT] Invoking abort!
21:39:12   [ERR] JVMDUMP039I Processing dump event "abort", detail "" at 2021/01/14 21:39:11 - please wait.
21:39:12   [ERR] JVMDUMP032I JVM requested Java dump using '/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/test_output_16106584546121/cmdLineTest_sigabrtHandlingTest_0/javacore.20210114.213911.38277.0001.txt' in response to an event
21:39:12   [ERR] JVMDUMP010I Java dump written to /Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/test_output_16106584546121/cmdLineTest_sigabrtHandlingTest_0/javacore.20210114.213911.38277.0001.txt
21:39:12   [ERR] JVMDUMP013I Processed dump event "abort", detail "".
21:39:12  >> Success condition was found: [Output match: Processing dump event "abort"]
21:39:12  >> Required condition was found: [Output match: Processed dump event "abort"]
21:39:12  
21:39:12  Testing: -XX:+HandleSIGABRT
21:39:12  Test start time: 2021/01/14 21:39:11 Greenwich Mean Time
21:39:12  Running command: "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java"   -Xmx20m -Xdump:system+heap+snap+jit:none -XX:+HandleSIGABRT -cp "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar" VMBench.GPTests.GPTest abort
21:39:12  Time spent starting: 15 milliseconds
21:39:12  Time spent executing: 278 milliseconds
21:39:12  Test result: PASSED
21:39:12  Output from test:
21:39:12   [OUT] Invoking abort!
21:39:12   [ERR] JVMDUMP039I Processing dump event "abort", detail "" at 2021/01/14 21:39:12 - please wait.
21:39:12   [ERR] JVMDUMP032I JVM requested Java dump using '/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/test_output_16106584546121/cmdLineTest_sigabrtHandlingTest_0/javacore.20210114.213912.38278.0001.txt' in response to an event
21:39:12   [ERR] JVMDUMP010I Java dump written to /Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/test_output_16106584546121/cmdLineTest_sigabrtHandlingTest_0/javacore.20210114.213912.38278.0001.txt
21:39:12   [ERR] JVMDUMP013I Processed dump event "abort", detail "".
21:39:12  >> Success condition was found: [Output match: Processing dump event "abort"]
21:39:12  >> Required condition was found: [Output match: Processed dump event "abort"]
21:39:12  
21:39:12  Testing: -XX:-HandleSIGABRT -XX:+HandleSIGABRT
21:39:12  Test start time: 2021/01/14 21:39:12 Greenwich Mean Time
21:39:12  Running command: "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java"   -Xmx20m -Xdump:system+heap+snap+jit:none -XX:-HandleSIGABRT -XX:+HandleSIGABRT -cp "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar" VMBench.GPTests.GPTest abort
21:39:12  Time spent starting: 15 milliseconds
21:39:12  Time spent executing: 271 milliseconds
21:39:12  Test result: PASSED
21:39:12  Output from test:
21:39:12   [OUT] Invoking abort!
21:39:12   [ERR] JVMDUMP039I Processing dump event "abort", detail "" at 2021/01/14 21:39:12 - please wait.
21:39:12   [ERR] JVMDUMP032I JVM requested Java dump using '/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/test_output_16106584546121/cmdLineTest_sigabrtHandlingTest_0/javacore.20210114.213912.38281.0001.txt' in response to an event
21:39:12   [ERR] JVMDUMP010I Java dump written to /Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/test_output_16106584546121/cmdLineTest_sigabrtHandlingTest_0/javacore.20210114.213912.38281.0001.txt
21:39:12   [ERR] JVMDUMP013I Processed dump event "abort", detail "".
21:39:12  >> Success condition was found: [Output match: Processing dump event "abort"]
21:39:12  >> Required condition was found: [Output match: Processed dump event "abort"]
21:39:12  
21:39:12  Testing: -XX:-HandleSIGABRT
21:39:12  Test start time: 2021/01/14 21:39:12 Greenwich Mean Time
21:39:12  Running command: bash -c 'ulimit -c 0 ; "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java"   -Xmx20m -Xdump:system+heap+snap+jit:none -XX:-HandleSIGABRT -cp "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar" VMBench.GPTests.GPTest abort'
21:39:12  Time spent starting: 10 milliseconds
21:39:12  Time spent executing: 221 milliseconds
21:39:12  Test result: FAILED
21:39:12  Output from test:
21:39:12   [ERR] Exception in thread "main" java.lang.UnsatisfiedLinkError: gptest (Not found in java.library.path)
21:39:12   [ERR] 	at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1742)
21:39:12   [ERR] 	at java.base/java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1693)
21:39:12   [ERR] 	at java.base/java.lang.System.loadLibrary(System.java:603)
21:39:12   [ERR] 	at VMBench.GPTests.GPTest.<clinit>(GPTest.java:28)
21:39:12  >> Success condition was not found: [Output match: Invoking abort!]
21:39:12  >> Failure condition was not found: [Output match: Processing dump event "abort"]
21:39:12  
21:39:13  Testing: -XX:+HandleSIGABRT -XX:-HandleSIGABRT
21:39:13  Test start time: 2021/01/14 21:39:12 Greenwich Mean Time
21:39:13  Running command: bash -c 'ulimit -c 0 ; "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java"   -Xmx20m -Xdump:system+heap+snap+jit:none -XX:+HandleSIGABRT -XX:-HandleSIGABRT -cp "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar" VMBench.GPTests.GPTest abort'
21:39:13  Time spent starting: 10 milliseconds
21:39:13  Time spent executing: 210 milliseconds
21:39:13  Test result: FAILED
21:39:13  Output from test:
21:39:13   [ERR] Exception in thread "main" java.lang.UnsatisfiedLinkError: gptest (Not found in java.library.path)
21:39:13   [ERR] 	at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1742)
21:39:13   [ERR] 	at java.base/java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1693)
21:39:13   [ERR] 	at java.base/java.lang.System.loadLibrary(System.java:603)
21:39:13   [ERR] 	at VMBench.GPTests.GPTest.<clinit>(GPTest.java:28)
21:39:13  >> Success condition was not found: [Output match: Invoking abort!]
21:39:13  >> Failure condition was not found: [Output match: Processing dump event "abort"]
21:39:13  
21:39:13  Testing: -XX:+HandleSIGABRT -Xrs
21:39:13  Test start time: 2021/01/14 21:39:12 Greenwich Mean Time
21:39:13  Running command: "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java"   -Xmx20m -Xdump:system+heap+snap+jit:none -XX:+HandleSIGABRT -Xrs -cp "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar" VMBench.GPTests.GPTest abort
21:39:13  Time spent starting: 10 milliseconds
21:39:13  Time spent executing: 55 milliseconds
21:39:13  Test result: PASSED
21:39:13  Output from test:
21:39:13   [ERR] JVMJ9VM197E -XX:+HandleSIGABRT is not supported with -Xrs.
21:39:13   [ERR] Error: Could not create the Java Virtual Machine.
21:39:13   [ERR] Error: A fatal exception has occurred. Program will exit.
21:39:13  >> Success condition was found: [Output match: -XX:+HandleSIGABRT is not supported with -Xrs]
21:39:13  >> Failure condition was not found: [Output match: Invoking abort!]
21:39:13  >> Failure condition was not found: [Output match: Processing dump event "abort"]
21:39:13  
21:39:13  Testing: -XX:+HandleSIGABRT -Xrs:sync
21:39:13  Test start time: 2021/01/14 21:39:13 Greenwich Mean Time
21:39:13  Running command: "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java"   -Xmx20m -Xdump:system+heap+snap+jit:none -XX:+HandleSIGABRT -Xrs:sync -cp "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar" VMBench.GPTests.GPTest abort
21:39:13  Time spent starting: 9 milliseconds
21:39:13  Time spent executing: 50 milliseconds
21:39:13  Test result: PASSED
21:39:13  Output from test:
21:39:13   [ERR] JVMJ9VM197E -XX:+HandleSIGABRT is not supported with -Xrs.
21:39:13   [ERR] Error: Could not create the Java Virtual Machine.
21:39:13   [ERR] Error: A fatal exception has occurred. Program will exit.
21:39:13  >> Success condition was found: [Output match: -XX:+HandleSIGABRT is not supported with -Xrs]
21:39:13  >> Failure condition was not found: [Output match: Invoking abort!]
21:39:13  >> Failure condition was not found: [Output match: Processing dump event "abort"]
21:39:13  
21:39:13  Testing: -Xrs
21:39:13  Test start time: 2021/01/14 21:39:13 Greenwich Mean Time
21:39:13  Running command: bash -c 'ulimit -c 0 ; "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java"   -Xmx20m -Xdump:system+heap+snap+jit:none -Xrs -cp "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar" VMBench.GPTests.GPTest abort'
21:39:13  Time spent starting: 10 milliseconds
21:39:13  Time spent executing: 213 milliseconds
21:39:13  Test result: FAILED
21:39:13  Output from test:
21:39:13   [ERR] Exception in thread "main" java.lang.UnsatisfiedLinkError: gptest (Not found in java.library.path)
21:39:13   [ERR] 	at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1742)
21:39:13   [ERR] 	at java.base/java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1693)
21:39:13   [ERR] 	at java.base/java.lang.System.loadLibrary(System.java:603)
21:39:13   [ERR] 	at VMBench.GPTests.GPTest.<clinit>(GPTest.java:28)
21:39:13  >> Success condition was not found: [Output match: Invoking abort!]
21:39:13  >> Failure condition was not found: [Output match: Processing dump event "abort"]
21:39:13  
21:39:13  Testing: -XX:-HandleSIGABRT -Xrs
21:39:13  Test start time: 2021/01/14 21:39:13 Greenwich Mean Time
21:39:13  Running command: bash -c 'ulimit -c 0 ; "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java"   -Xmx20m -Xdump:system+heap+snap+jit:none -XX:-HandleSIGABRT -Xrs -cp "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar" VMBench.GPTests.GPTest abort'
21:39:13  Time spent starting: 10 milliseconds
21:39:13  Time spent executing: 208 milliseconds
21:39:13  Test result: FAILED
21:39:13  Output from test:
21:39:13   [ERR] Exception in thread "main" java.lang.UnsatisfiedLinkError: gptest (Not found in java.library.path)
21:39:13   [ERR] 	at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1742)
21:39:13   [ERR] 	at java.base/java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1693)
21:39:13   [ERR] 	at java.base/java.lang.System.loadLibrary(System.java:603)
21:39:13   [ERR] 	at VMBench.GPTests.GPTest.<clinit>(GPTest.java:28)
21:39:13  >> Success condition was not found: [Output match: Invoking abort!]
21:39:13  >> Failure condition was not found: [Output match: Processing dump event "abort"]
21:39:13  
21:39:13  Testing: -XX:-HandleSIGABRT -Xrs:sync
21:39:13  Test start time: 2021/01/14 21:39:13 Greenwich Mean Time
21:39:13  Running command: bash -c 'ulimit -c 0 ; "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java"   -Xmx20m -Xdump:system+heap+snap+jit:none -XX:-HandleSIGABRT -Xrs:sync -cp "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac/openjdk-tests/TKG/../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar" VMBench.GPTests.GPTest abort'
21:39:13  Time spent starting: 10 milliseconds
21:39:13  Time spent executing: 205 milliseconds
21:39:13  Test result: FAILED
21:39:13  Output from test:
21:39:13   [ERR] Exception in thread "main" java.lang.UnsatisfiedLinkError: gptest (Not found in java.library.path)
21:39:13   [ERR] 	at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1742)
21:39:13   [ERR] 	at java.base/java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1693)
21:39:13   [ERR] 	at java.base/java.lang.System.loadLibrary(System.java:603)
21:39:13   [ERR] 	at VMBench.GPTests.GPTest.<clinit>(GPTest.java:28)
21:39:13  >> Success condition was not found: [Output match: Invoking abort!]
21:39:13  >> Failure condition was not found: [Output match: Processing dump event "abort"]
21:39:13  
21:39:13  Executing command: bash -c 'rm core.*'
21:39:13  
21:39:13  
21:39:13  ---TEST RESULTS---
21:39:13  Number of PASSED tests: 5 out of 10
21:39:13  Number of FAILED tests: 5 out of 10
21:39:13  
21:39:13  ---SUMMARY OF FAILED TESTS---
21:39:13  -XX:-HandleSIGABRT
21:39:13  -XX:+HandleSIGABRT -XX:-HandleSIGABRT
21:39:13  -Xrs
21:39:13  -XX:-HandleSIGABRT -Xrs
21:39:13  -XX:-HandleSIGABRT -Xrs:sync
21:39:13  -----------------------------
21:39:13  
21:39:13  
21:39:13  cmdLineTest_sigabrtHandlingTest_0_FAILED
```

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (or Grinder rerun link):

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sophia-guo** [comment] 2021-01-18 13:19
It passed on latest build https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.functional_x86-64_mac/64/ running on **test-macincloud-macos1010-x64-2**. All existing former failure runs are on **macos1013 or macos1014**.

**Comment by smlambert** [comment] 2021-01-18 14:19
We also have openjdk tests that pass on macos1010, but not macos1013/macos1014, posting here in case there is a related issue (theorized) around not being able to access certain dirs in later macos versions https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1274#issuecomment-708845395

**Comment by adamfarley** [comment] 2021-02-03 17:28
The cmdLineTest_sigabrtHandlingTest_0 subtests fail in different patterns, seemingly based on the machine.

Details below, including name, link to the machine's web page, os version, example of a failing test, and DYLD_LIBRARY_PATH value if known (which, as per [this openj9 issue](https://github.com/eclipse/openj9/issues/3686), is believed to be the source of gptest's path).

These machines fail every subtest.
- [osx1014-x86-3](https://ci.eclipse.org/openj9/computer/osx1014-x86-3/) - osx1014 - [(Test example)](https://ci.eclipse.org/openj9/job/Grinder/1482/consoleFull)
Note: DYLD_LIBRARY_PATH="/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/Contents/Home/bin/..//../native-test-libs/:/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/Contents/Home/bin/..//jre/bin/../lib//compressedrefs:/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/Contents/Home/bin/..//jre/bin/../lib//j9vm:"

These machines *only* fail the subtests that begin: bash -c 'ulimit -c 0 ; "\<test_java_command\>" '
The other subtests, which omit the "bash" shell, always seem to pass.
- [test-macstadium-macos1013-x64-1](https://ci.adoptopenjdk.net/computer/test-macstadium-macos1013-x64-1/) - osx1013 - [(Test example)](https://trss.adoptopenjdk.net/output/test?id=60133e1bddf93e76e9e686c3)

These machines pass every subtest.
- [osx1011-x86-2](https://ci.eclipse.org/openj9/computer/osx1011-x86-2) - osx1011vm2 - [(Test example)](https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_mac_Personal_testList_1/102/consoleText)

Based on this information, smlambert's theory seems solid. Other possibilities include the later machines having different jenkins user privileges, maybe due to earlier machines being setup up manually or with earlier playbooks, and never re-built with the later playbooks.

Will run a few more grinders on specific machines, and then open an infra ticket with a request for user + folder permissions information, so we can pin down the cause.

**Comment by andrew-m-leonard** [comment] 2021-02-11 13:13
It looks like Apple as part of System Integrity Protection have disabled DYLD_LIBRARY_PATH
https://gitlab.haskell.org/ghc/ghc/-/issues/11617
I need to investigate a workaround

**Comment by andrew-m-leonard** [comment] 2021-02-11 18:54
I am fairly sure now the problem is because the Jenkins agent is currently picking up /bin/bash when running tests as:
```
bash -c 'ulimit -c 0 ; " ...
```
and due to Mac 10.11+ SIP protection any process started from /bin will have DYLD_LIBRARY_PATH stripped.
We need to update the Jenkins agents on these nodes to have bash picked up from /usr/local/bin/bash

**Comment by andrew-m-leonard** [comment] 2021-02-11 21:38
All the Jenkins Mac agent configuration has now been updated to correctly add /usr/local/bin to the PATH, using the following setting:
![image](https://user-images.githubusercontent.com/31470007/107701776-46563c80-6cb1-11eb-99ed-41394c8066da.png)
This ensure the /usr/local/bin/bash gets used rather than /bin/bash, and the /usr/local/bin is not a SIP protected directory and so will not purge DYLD_LIBRARY_PATH.

**Comment by smlambert** [comment] 2021-03-01 15:58
Given the machine updates are completed, is this issue now fixed and can be closed?

**Comment by andrew-m-leonard** [comment] 2021-03-02 08:40
yes finished

**Closed by andrew-m-leonard** 2021-03-02 08:40 UTC
Labels: bug
