### ISSUE TITLE
jdk_beans: java/beans/Introspector/Test8027648.java fails 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#58] opened 2017-06-15 02:31 UTC
Test threw exception: java.lang.Error: the child property type is not override the parent property type
18:29:50 java.lang.Error: the child property type is not override the parent property type
18:29:50 	at Test8027648.test(Test8027648.java:45)
18:29:50 	at Test8027648.main(Test8027648.java:38), 
output from https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_linux/34/consoleFull:

18:29:50 HOME=/home/jenkins \
18:29:50 LANG=en_US.UTF-8 \
18:29:50 PATH=/bin:/usr/bin \
18:29:50     /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/javac \
18:29:50         -J-ea \
18:29:50         -J-esa \
18:29:50         -J-Xmx512m \
18:29:50         -J-Dtest.src=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/beans/Introspector \
18:29:50         -J-Dtest.src.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/beans/Introspector \
18:29:50         -J-Dtest.classes=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/3/java/beans/Introspector \
18:29:50         -J-Dtest.class.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/3/java/beans/Introspector \
18:29:50         -J-Dtest.vm.opts='-ea -esa -Xmx512m' \
18:29:50         -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
18:29:50         -J-Dtest.compiler.opts= \
18:29:50         -J-Dtest.java.opts= \
18:29:50         -J-Dtest.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
18:29:50         -J-Dcompile.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
18:29:50         -J-Dtest.timeout.factor=4.0 \
18:29:50         -d /home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/3/java/beans/Introspector \
18:29:50         -sourcepath /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/beans/Introspector \
18:29:50         -classpath /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/beans/Introspector:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/3/java/beans/Introspector:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar \
18:29:50         -XDignore.symbol.file=true /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/beans/Introspector/Test8027648.java
18:29:50 STDOUT:
18:29:50 STDERR:
18:29:50 
18:29:50 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.Error: the child property type is not override the parent property type
18:29:50 REASON: Assumed action based on file name: run main Test8027648 
18:29:50 TIME:   0.572 seconds
18:29:50 messages:
18:29:50 command: main Test8027648
18:29:50 reason: Assumed action based on file name: run main Test8027648 
18:29:50 Mode: othervm
18:29:50 elapsed time (seconds): 0.572
18:29:50 configuration:
18:29:50 STDOUT:
18:29:50 STDERR:
18:29:50 java.lang.Error: the child property type is not override the parent property type
18:29:50 	at Test8027648.test(Test8027648.java:45)
18:29:50 	at Test8027648.main(Test8027648.java:38)
18:29:50 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:29:50 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:29:50 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:29:50 	at java.lang.reflect.Method.invoke(Method.java:498)
18:29:50 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
18:29:50 	at java.lang.Thread.run(Thread.java:748)
18:29:50 
18:29:50 JavaTest Message: Test threw exception: java.lang.Error: the child property type is not override the parent property type
18:29:50 JavaTest Message: shutting down test
18:29:50 
18:29:50 STATUS:Failed.`main' threw exception: java.lang.Error: the child property type is not override the parent property type

**Comment by sophia-guo** [comment] 2017-10-03 16:08
Duplicate of #117

**Closed by sophia-guo** 2017-10-03 16:08 UTC
Labels: linux
