### ISSUE TITLE
Mac : (intermittent) jdk_nio : java/nio/channels/SocketChannel/Connect.java.Connect failed with java.lang.Exception: Refused connection throws no exception

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#156] opened 2017-10-16 16:06 UTC
<pre>20:03:52 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.Exception: Refused connection throws no exception
20:03:52 REASON: Assumed action based on file name: run main Connect 
20:03:52 TIME:   0.011 seconds
20:03:52 messages:
20:03:52 command: main Connect
20:03:52 reason: Assumed action based on file name: run main Connect 
20:03:52 Mode: agentvm
20:03:52 Agent id: 1
20:03:52 elapsed time (seconds): 0.011
20:03:52 configuration:
20:03:52 Boot Layer
20:03:52   class path: /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar
20:03:52               /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar
20:03:52               /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar
20:03:52 
20:03:52 Test Layer
20:03:52   class path: /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/nio/channels/SocketChannel
20:03:52               /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/nio/channels/SocketChannel
20:03:52               /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/nio/channels
20:03:52               /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/nio/channels
20:03:52 
20:03:52 rerun:
20:03:52 cd /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/scratch/0 && \
20:03:52 HOME=/Users/jenkins \
20:03:52 PATH=/bin:/usr/bin \
20:03:52     /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
20:03:52         -Dtest.class.path.prefix=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/nio/channels/SocketChannel:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/nio/channels/SocketChannel:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/nio/channels \
20:03:52         -Dtest.src=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/nio/channels/SocketChannel \
20:03:52         -Dtest.src.path=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/nio/channels/SocketChannel:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/nio/channels \
20:03:52         -Dtest.classes=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/nio/channels/SocketChannel \
20:03:52         -Dtest.class.path=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/nio/channels/SocketChannel:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/nio/channels \
20:03:52         -Dtest.vm.opts='-ea -esa -Xmx512m' \
20:03:52         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
20:03:52         -Dtest.compiler.opts= \
20:03:52         -Dtest.java.opts= \
20:03:52         -Dtest.jdk=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:03:52         -Dcompile.jdk=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:03:52         -Dtest.timeout.factor=4.0 \
20:03:52         -classpath /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/nio/channels/SocketChannel:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/nio/channels/SocketChannel:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/nio/channels:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/java/nio/channels:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
20:03:52         Connect
20:03:52 STDERR:
20:03:52 Got event for our selection key.
20:03:52 Successful connect.
20:03:52 SUCCESS! buffer contents were sent.
20:03:52 Got event for our selection key.
20:03:52 Successful connect.
20:03:52 SUCCESS! buffer contents were sent.
20:03:52 java.lang.Exception: Refused connection throws no exception
20:03:52 	at Connect.main(Connect.java:48)
20:03:52 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:03:52 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:03:52 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:03:52 	at java.lang.reflect.Method.invoke(Method.java:498)
20:03:52 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
20:03:52 	at java.lang.Thread.run(Thread.java:748)
20:03:52 
20:03:52 JavaTest Message: Test threw exception: java.lang.Exception
20:03:52 JavaTest Message: shutting down test
20:03:52 
20:03:52 
20:03:52 TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Exception: Refused connection throws no exception
</pre>

**Comment by akolarkunnu** [comment] 2018-03-15 08:32
It is a duplicate of openjdk bug https://bugs.openjdk.java.net/browse/JDK-8037360.

**Comment by smlambert** [comment] 2018-03-18 02:04
Closing as now listed in summary issue #345

**Closed by smlambert** 2018-03-18 02:04 UTC
Labels: Reported/Fixed Upstream, bug, java8, mac
