### ISSUE TITLE
JlinkTest* failed with directory could not be found

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-tests#456] opened 2018-06-19 17:48 UTC
Following tests failed with the error:
```
GEN stderr Exception in thread "main" net.adoptopenjdk.stf.StfException: Note: directory 'openjdk.test.modularity/bin/tests/com.test.jlink/native/bin/linux_ppcle-64' could not be found in any of the supplied roots: '/home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/stf','/home/jenkins/jenkins-agent/workspace/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/jvmtest/systemtest/openjdk-systemtest'
GEN stderr 	at net.adoptopenjdk.stf.environment.DirectoryRef.findDirectory(DirectoryRef.java:274)
GEN stderr 	at net.adoptopenjdk.stf.environment.StfEnvironmentCore.findTestDirectory(StfEnvironmentCore.java:277)
GEN stderr 	at net.adoptopenjdk.stf.extensions.core.StfEnvironment.findTestDirectory(StfEnvironment.java:55)
```

Failed tests:
- linkTest_RequiredMod_0
- JlinkTest_AddModLimitMod_0
- JlinkPluginOptionsTest_GeneralOptionsTest_0

https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK10-linux_ppc-64_cmprssptrs_le/3/tapResults/

fyi @Mesbah-Alam

**Comment by karianna** [comment] 2018-06-19 17:50
@llxia Which platform is this on?

**Comment by llxia** [comment] 2018-06-19 17:56
I found it on linux ppcle so far.
```
15:35:47 openjdk version "10.0.1-internal" 2018-04-17
15:35:47 OpenJDK Runtime Environment (build 10.0.1-internal+0-adhoc.jenkins.Build-JDK10-linuxppc-64cmprssptrsle)
15:35:47 Eclipse OpenJ9 VM (build master-e27ef8e, JRE 10 Linux ppc64le-64-Bit Compressed References 20180618_201 (JIT enabled, AOT enabled)
15:35:47 OpenJ9   - e27ef8e
15:35:47 OMR      - 447fdf4
15:35:47 JCL      - 3e42389 based on jdk-10.0.1+10)
```

**Comment by llxia** [comment] 2018-06-19 17:58
Adopt test build has same issue: https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk10_j9_systemtest_ppc64le_linux/37/tapResults/

**Comment by Mesbah-Alam** [comment] 2018-06-19 21:16
The test fails on linux ppcle 64 platform but passes on other platforms (e.g. , Linux x64 : https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk9_j9_systemtest_x86-64_linux/100/tapResults/) 

The reason why it's failing on linux ppcle 64 bit is that the systemtest build script is generating wrong value for `java9_platform` property (which is used in the compilation of the tests) on this platform. 

 `stf.core/src/stf.core/net/adoptopenjdk/stf/environment/PlatformFinder.java#getPlatformAsString()` (used in the test) returns `linux_ppcle-64`, whereas in the Ant build script top.xml, `java9_platform` is set to `linux_ppc-64`. 

So, for Linux ppcle 64 bit platform, the build.xml for modularity tests are generating test natives under `openjdk.test.modularity/bin/tests/com.test.jlink/native/bin/**linux_ppc-64**/`, but the test itself is looking for it under `openjdk.test.modularity/bin/tests/com.test.jlink/native/bin/**linux_ppcle-64**`. 

This mismatch needs to be resolved. 

I am working on resolving this issue.

**Comment by Mesbah-Alam** [comment] 2018-06-20 17:07
The root cause of the issue is that openjdk.build/include/top.xml contains a macro <get-platform-arch> which appears to be returning ppc when executing on ppcle, even though the java.os.arch java system property is set correctly to ppc64le.

The fix is:  

```
<condition property="@{property}" value="ppcle">
	<and>
		<contains string="@{arch}" substring="ppc64le"/>
	</and>
</condition>
```

The fix has been delivered via : https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/136

**Closed** 2018-06-20 21:14 UTC
Labels: bug
