### ISSUE TITLE
hotspot_jre: compile tests failed

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#116] opened 2017-10-02 18:35 UTC
18:28:18 TEST: compiler/types/correctness/OffTest.java
18:28:18 TEST JDK: /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../..
...
18:28:18 
18:28:18 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
18:28:18 REASON: User specified action: run main/timeout=1200 OffTest 
18:28:18 TIME:   1.638 seconds
18:28:18 messages:
18:28:18 command: main OffTest
18:28:18 reason: User specified action: run main/timeout=1200 OffTest 
18:28:18 Mode: agentvm
18:28:18 Agent id: 2
18:28:18 elapsed time (seconds): 1.638
18:28:18 configuration:
18:28:18 Boot Layer
18:28:18   class path: /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar
18:28:18               /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar
18:28:18               /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar
18:28:18 
18:28:18 Test Layer
18:28:18   class path: /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/compiler/types/correctness/OffTest.d
18:28:18               /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/compiler/types/correctness
18:28:18               /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/testlibrary
18:28:18               /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/testlibrary
18:28:18               /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/testlibrary/whitebox
18:28:18               /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/testlibrary/whitebox
18:28:18 
18:28:18 rerun:
18:28:18 HOME=/home/jenkins \
18:28:18 LANG=en_US.UTF-8 \
18:28:18 PATH=/bin:/usr/bin \
18:28:18     /home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
18:28:18         -Dtest.class.path.prefix=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/compiler/types/correctness/OffTest.d:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/compiler/types/correctness:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/testlibrary:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/testlibrary/whitebox \
18:28:18         -Dtest.src=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/compiler/types/correctness \
18:28:18         -Dtest.src.path=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/compiler/types/correctness:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/testlibrary:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/testlibrary/whitebox \
18:28:18         -Dtest.classes=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/compiler/types/correctness/OffTest.d \
18:28:18         -Dtest.class.path=/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/compiler/types/correctness/OffTest.d:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/testlibrary:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/testlibrary/whitebox \
18:28:18         -Dtest.vm.opts='-ea -esa -Xmx512m' \
18:28:18         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
18:28:18         -Dtest.compiler.opts= \
18:28:18         -Dtest.java.opts= \
18:28:18         -Dtest.jdk=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
18:28:18         -Dcompile.jdk=/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
18:28:18         -Dtest.timeout.factor=4.0 \
18:28:18         -classpath /home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/compiler/types/correctness/OffTest.d:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/compiler/types/correctness:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/testlibrary:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/testlibrary:/home/jenkins/workspace/openjdk8_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/testlibrary/whitebox:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk/hotspot/test/testlibrary/whitebox:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
18:28:18         OffTest
18:28:18 STDOUT:
18:28:18 -Dseed=-3068824989926123420
18:28:18 Command line: [/home/jenkins/workspace/openjdk8_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java -ea -esa -Xmx512m -Xbootclasspath/a:. -XX:+IgnoreUnrecognizedVMOptions -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+WhiteBoxAPI -XX:CompileCommand=exclude,execution/*::methodNotToCompile -XX:CompileCommand=dontinline,scenarios/Scenario::collectReturnType -XX:TypeProfileLevel=121 -XX:+UseTypeSpeculation CorrectnessTest PARAMETERS ]
18:28:18 STDERR:
18:28:18  stdout: [CompilerOracle: exclude execution/*.methodNotToCompile
18:28:18 CompilerOracle: dontinline scenarios/Scenario.collectReturnType
18:28:18 ];
18:28:18  stderr: [Error: Could not find or load main class CorrectnessTest
18:28:18 ]
18:28:18  exitValue = 1
18:28:18 
18:28:18 java.lang.RuntimeException: Expected to get exit value of [0]
18:28:18 
18:28:18 	at com.oracle.java.testlibrary.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:362)
18:28:18 	at OffTest.runTest(OffTest.java:93)
18:28:18 	at OffTest.main(OffTest.java:80)

compiler/5091921/Test7005594.java
compiler/c1/TestUnresolvedFieldMain.java
compiler/jsr292/PollutedTrapCounts.java
compiler/jsr292/RedefineMethodUsedByMultipleMethodHandles.java
compiler/loopopts/UseCountedLoopSafepoints.java
compiler/types/correctness/OffTest.java
compiler/unsafe/TestRawAliasing.java
gc/TestVerifySilently.java
gc/TestVerifySubSet.java
gc/arguments/TestG1HeapRegionSize.java
gc/arguments/TestMinInitialErgonomics.java
gc/class_unloading/TestCMSClassUnloadingEnabledHWM.java
gc/class_unloading/TestG1ClassUnloadingHWM.java
gc/ergonomics/TestDynamicNumberOfGCThreads.java
gc/g1/TestEagerReclaimHumongousRegions.java
gc/g1/TestEagerReclaimHumongousRegionsClearMarkBits.java
gc/g1/TestEagerReclaimHumongousRegionsWithRefs.java
gc/g1/TestG1TraceEagerReclaimHumongousObjects.java
gc/g1/TestGCLogMessages.java
gc/g1/TestHumongousAllocInitialMark.java
gc/g1/TestPrintGCDetails.java
gc/g1/TestPrintRegionRememberedSetInfo.java
gc/g1/TestShrinkAuxiliaryData00.java
gc/g1/TestShrinkDefragmentedHeap.java
gc/g1/TestStringDeduplicationAgeThreshold.java
gc/g1/TestStringDeduplicationFullGC.java
gc/g1/TestStringDeduplicationInterned.java
gc/g1/TestStringDeduplicationPrintOptions.java
gc/g1/TestStringDeduplicationTableRehash.java
gc/g1/TestStringDeduplicationTableResize.java
gc/g1/TestStringDeduplicationYoungGC.java
gc/g1/TestStringSymbolTableStats.java
gc/logging/TestGCId.java
gc/whitebox/TestWBGC.java

**Comment by sophia-guo** [comment] 2018-01-04 16:13
Re-enable compiler/unsafe/TestRawAliasing.java, which works fine now.

**Comment by karianna** [comment] 2018-01-04 16:21
@sophia-guo So this can be closed?

**Comment by sophia-guo** [comment] 2018-01-04 17:06
No, problem stays. The one I re-enabled has different issue, which was listed here by accident.

**Comment by akolarkunnu** [comment] 2018-03-15 08:19
This is a duplicate of openjdk bug https://bugs.openjdk.java.net/browse/JDK-8180904.

**Comment by smlambert** [comment] 2018-03-18 01:53
Closing as now listed in summary issue #345

**Closed by smlambert** 2018-03-18 01:53 UTC
Labels: Reported/Fixed Upstream, bug
