### ISSUE TITLE
 com/sun/jdi/RedefineCrossEvent.java fails with com.sun.jdi.VMDisconnectedException

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#227] opened 2018-01-23 02:40 UTC
Test category: openjdk
Testsuite name: jdk_jdi
Test name(s): com/sun/jdi/RedefineCrossEvent.java
Product(s) tested: https://github.com/AdoptOpenJDK/openjdk8-nightly/releases/download/jdk8u172-b00-20182201/OpenJDK8_x64_Mac_20182201.tar.gz
OS/architecture: OpenJDK8_x64_Mac
Platform specific:

Reproducibility: always
Reproducible on machine: test-macincloud-macos1010-1 
Regression: 

Exception/Error from Log:
Execution failed: `main' threw exception: com.sun.jdi.VMDisconnectedException: connection is closed

Error log file:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_personal/130/testReport/com_sun_jdi_RedefineCrossEvent/java/RedefineCrossEvent/

Steps to reproduce:
1) Re-include test in your branch.  (Search the Test class name in ProblemList.txt find the exclude line and comment the line
In this case looking for a group called jdk_jdi and an entry like this, "com/sun/jdi/RedefineCrossEvent.java	227	macosx-all")
2) Follow instructions at: https://github.com/AdoptOpenJDK/openjdk-tests/wiki/How-to-Run-a-Personal-Test-Build-on-Jenkins with settings:
PLATFORM x86_mac
JAVA_VERSION SE80
JVM_VERSION openjdk8
TARGET jdk_jdi_SE80_0  
TESTPROJECT openjdk_regression
MACHINE_LABEL mac&&x64&&test
SDK_RESOURCE nightly

**Comment by akolarkunnu** [comment] 2018-02-01 10:22
Copying log file: 
Stacktrace
Execution failed: `main' threw exception: com.sun.jdi.VMDisconnectedException: connection is closed    
Standard Output
JVM version:1.8.0-internal
JDI version: 1.8
JVM description: Java Debug Interface (Reference Implementation) version 1.8 
Java Debug Wire Protocol (Reference Implementation) version 1.8
JVM Debug Interface version 1.2
JVM version 1.8.0-internal (OpenJDK 64-Bit Server VM, mixed mode, sharing)
Howdy!
  Skipping boolean (primitive scalar type)
  Testing: boolean[] modifiers = 10001
  Testing: boolean[][] modifiers = 10001
  Skipping byte (primitive scalar type)
  Testing: byte[] modifiers = 10001
  Testing: byte[][] modifiers = 10001
  Skipping short (primitive scalar type)
  Testing: short[] modifiers = 10001
  Testing: short[][] modifiers = 10001
  Skipping int (primitive scalar type)
  Testing: int[] modifiers = 10001
  Testing: int[][] modifiers = 10001
  Skipping long (primitive scalar type)
  Testing: long[] modifiers = 10001
  Testing: long[][] modifiers = 10001
  Skipping char (primitive scalar type)
  Testing: char[] modifiers = 10001
  Testing: char[][] modifiers = 10001
  Skipping float (primitive scalar type)
  Testing: float[] modifiers = 10001
  Testing: float[][] modifiers = 10001
  Skipping double (primitive scalar type)
  Testing: double[] modifiers = 10001
  Testing: double[][] modifiers = 10001
  Testing: java.lang.Boolean[][] modifiers = 110001
  Testing: java.lang.Boolean[] modifiers = 110001
  Testing: java.lang.Boolean modifiers = 110001
  Testing: java.lang.Character[][] modifiers = 110001
  Testing: java.lang.Character[] modifiers = 110001
  Testing: java.lang.Character modifiers = 110001
Skipping java.lang.Class[][] (not found)
  Testing: java.lang.Class[] modifiers = 110001
  Testing: java.lang.Class modifiers = 110001
  Testing: java.lang.Double[][] modifiers = 110001
  Testing: java.lang.Double[] modifiers = 110001
  Testing: java.lang.Double modifiers = 110001
  Testing: java.lang.Float[][] modifiers = 110001
  Testing: java.lang.Float[] modifiers = 110001
  Testing: java.lang.Float modifiers = 110001
  Testing: java.lang.Integer[][] modifiers = 110001
  Testing: java.lang.Integer[] modifiers = 110001
  Testing: java.lang.Integer modifiers = 110001
  Testing: java.lang.Long[][] modifiers = 110001
  Testing: java.lang.Long[] modifiers = 110001
  Testing: java.lang.Long modifiers = 110001
  Testing: java.lang.String[][] modifiers = 110001
  Testing: java.lang.String[] modifiers = 110001
  Testing: java.lang.String modifiers = 110001
  Testing: java.lang.Object[][] modifiers = 100001
  Testing: java.lang.Object[] modifiers = 100001
  Testing: java.lang.Object modifiers = 100001
  Testing: AccessSpecifierTarg[][] modifiers = 100000
  Testing: AccessSpecifierTarg[] modifiers = 100000
  Testing: AccessSpecifierTarg modifiers = 100000
  Testing: AccessSpecifierPackagePrivateClass[][] modifiers = 100000
  Testing: AccessSpecifierPackagePrivateClass[] modifiers = 100000
  Testing: AccessSpecifierPackagePrivateClass modifiers = 100000
  Testing: AccessSpecifierPackagePrivateInterface[][] modifiers = 11000000000
  Testing: AccessSpecifierPackagePrivateInterface[] modifiers = 11000000000
  Testing: AccessSpecifierPackagePrivateInterface modifiers = 11000000000
  Testing: AccessSpecifierTarg$StaticInterface[][] modifiers = 11000001010
  Testing: AccessSpecifierTarg$StaticInterface[] modifiers = 11000001010
  Testing: AccessSpecifierTarg$StaticInterface modifiers = 11000001010
  Testing: AccessSpecifierTarg$U[][] modifiers = 101010
  Testing: AccessSpecifierTarg$U[] modifiers = 101010
  Testing: AccessSpecifierTarg$U modifiers = 101010
  Testing: AccessSpecifierTarg$V[][] modifiers = 101100
  Testing: AccessSpecifierTarg$V[] modifiers = 101100
  Testing: AccessSpecifierTarg$V modifiers = 101100
  Testing: AccessSpecifierTarg$W[][] modifiers = 101001
  Testing: AccessSpecifierTarg$W[] modifiers = 101001
  Testing: AccessSpecifierTarg$W modifiers = 101001
  Testing: AccessSpecifierTarg$P[][] modifiers = 101000
  Testing: AccessSpecifierTarg$P[] modifiers = 101000
  Testing: AccessSpecifierTarg$P modifiers = 101000
Ready!
Goodbye from AccessSpecifierTarg!
    
Standard Error
run args: [-redefstart, -redefevent, AccessSpecifierTarg]
Redefining class AccessSpecifierTarg (loaded by instance of sun.misc.Launcher$AppClassLoader(id=95))
Redefining class AccessSpecifierTarg (loaded by instance of sun.misc.Launcher$AppClassLoader(id=95))
AccessSpecifierTest: passed

JavaTest Message:  Test complete.

**Comment by akolarkunnu** [comment] 2018-02-06 10:57
Actual Error log:
Redefining class ClassesByName2Targ (loaded by instance of sun.misc.Launcher$AppClassLoader(id=86))
Note: Unexpected Debuggee Exception: java.lang.UnsatisfiedLinkError at line -1
detailMessage = "../jdk8u172-b01-adopt/jre/lib/libfontmanager.dylib: dlopen(../jdk8u172-b01-adopt/jre/lib/libfontmanager.dylib, 1): Library not loaded: /Users/jenkins/workspace/openjdk8_build_x86-64_macos/openjdk/installedfreetype/lib/libfreetype.6.dylib
  Referenced from: ../jdk8u172-b01-adopt/jre/lib/libfontmanager.dylib
  Reason: image not found"
com.sun.jdi.VMDisconnectedException: connection is closed
	at com.sun.tools.jdi.TargetVM.send(TargetVM.java:296)
	at com.sun.tools.jdi.VirtualMachineImpl.sendToTarget(VirtualMachineImpl.java:1032)
	at com.sun.tools.jdi.PacketStream.send(PacketStream.java:59)
	at com.sun.tools.jdi.JDWP$VirtualMachine$Exit.enqueueCommand(JDWP.java:650)
	at com.sun.tools.jdi.JDWP$VirtualMachine$Exit.process(JDWP.java:636)
	at com.sun.tools.jdi.VirtualMachineImpl.exit(VirtualMachineImpl.java:566)
	at ClassesByName2Test.runTests(ClassesByName2Test.java:176)
	at TestScaffold.startTests(TestScaffold.java:429)
	at ClassesByName2Test.main(ClassesByName2Test.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.lang.Thread.run(Thread.java:748)

JavaTest Message: Test threw exception: com.sun.jdi.VMDisconnectedException: connection is closed
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: com.sun.jdi.VMDisconnectedException: connection is closed

**Comment by akolarkunnu** [comment] 2018-02-06 10:59
So it's a duplicate of #136

**Closed** 2018-02-06 10:59 UTC
Labels: bug, java8, mac
