### ISSUE TITLE
jdk_lang_native_win_0 FAILED in Test_openjdk11_hs_sanity.openjdk_x86-32_windows

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#2029] opened 2020-10-23 18:48 UTC
**Test Info**
Test Name: jdk_lang_native_win_0
Test Duration: 23 sec
Machine: test-aws-win2019-x64-2
TRSS link for the test output: https://trss.adoptopenjdk.net/output/test?id=5f92d7e511d26031c130be5a

**Build Info**
Build Name: Test_openjdk11_hs_sanity.openjdk_x86-32_windows
Jenkins Build start time: Oct 23 2020, 08:08 am
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_x86-32_windows/363/
TRSS link for the build: https://trss.adoptopenjdk.net/allTestsInfo?buildId=5f92d75f11d26031c130bbf0

**Java Version**
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
OpenJDK Client VM AdoptOpenJDK (build 11.0.9+11, mixed mode)

**This test has been failed 14 times since Oct 10 2020, 08:09 pm**
**Java Version when the issue first seen**
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment Hotspot (build 11.0.9+10-202010102343)
OpenJDK Client VM Hotspot (build 11.0.9+10-202010102343, mixed mode)
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_x86-32_windows/350/

The test failed on machine test-aws-win2019-x64-2 3 times 
The test failed on machine test-azure-win2012r2-x64-1 3 times 
The test failed on machine test-aws-win2019-x64-1 3 times 
The test failed on machine test-ibmcloud-win2012r2-x64-1 1 times 
The test failed on machine test-godaddy-win2016-x64-1 2 times 
The test failed on machine test-godaddy-win2016-x64-4 1 times 
The test failed on machine test-godaddy-win2016-x64-2 1 times 

[Rerun in Grinder](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?TARGET=jdk_lang_native_win_0&amp;SDK_RESOURCE=upstream&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;EXTRA_DOCKER_ARGS=&amp;VENDOR_TEST_DIRS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;PLATFORM=x86-32_windows&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=11&amp;USER_CREDENTIALS_ID=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptopenjdk%2Fopenjdk-jdk11u&amp;RELEASE_TAG=jdk-11.0.9%2B11_adopt&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-windows-x86-32-hotspot&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=dev&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=720&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)

**Comment by smlambert** [comment] 2020-10-23 19:00
The failing test case within jdk_lang_native_win is [java/lang/ProcessBuilder/checkHandles/CheckHandles.java
](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_x86-32_windows/359/testReport/java_lang_ProcessBuilder_checkHandles_CheckHandles/java/CheckHandles/)

java.lang.UnsatisfiedLinkError: 'long CheckHandles.getProcessHandleCount()'
	at CheckHandles.getProcessHandleCount(Native Method)
	at CheckHandles.main(CheckHandles.java:64)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:834)

Appears to have been failing for at least 75 test runs / days.  

This testcase was not part of sanity.openjdk (tier1 tests) looking at a [run from July 30th](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_x86-32_windows/284/testReport/) where it is not present, though it appears to have been added to [openjdk repo](https://github.com/AdoptOpenJDK/openjdk-jdk11u/commit/77c0956ca8b1807ace2998b3de6300948eec0bb4#diff-ddd3248c93aa1ccf6c04df77cb634c6ab075f91c6c4255d3e7327b33792ba9ae) in March.  

Unclear if it has ever run and passed on win32.

**Comment by adamfarley** [comment] 2021-01-27 09:44
This issue appears to be a duplicate of #1773.

Also, #1773 created PR #1774 to exclude this test, and the test still appears to be excluded (twice, oddly enough), so I'm not sure why we're even running it.

```
java/lang/ProcessBuilder/checkHandles/CheckHandles.java https://github.com/AdoptOpenJDK/openjdk-tests/issues/1920 windows-all
```

```
java/lang/ProcessBuilder/checkHandles/CheckHandles.java https://github.com/AdoptOpenJDK/openjdk-tests/issues/1773 windows-x86
```

https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/ProblemList_openjdk11.txt

**Comment by adamfarley** [comment] 2021-01-27 09:52
The exclusion-list failure looks to explained in https://github.com/AdoptOpenJDK/openjdk-tests/issues/1920

That PR seems to say that tests excluded from other targets (jdk_lang, jdk_net in this case), are not excluded from native target runs. So that explains the exclusion oddity.

**Comment by adamfarley** [comment] 2021-01-27 10:03
Heya @sophia-guo 

It looks like you did some with with CheckHandles.java back in July 2020. [Link here](https://github.com/AdoptOpenJDK/openjdk-tests/pull/1926).

Can you recall if this test ever passed on 32bit Windows?

**Comment by adamfarley** [comment] 2021-01-27 10:14
Also, here's a timeline of what I think has happened:

- March 2020: Test introduced.
- May 2020: Morgan sees a link issue in CheckHandles.java, as it's being run in a non-native jdk_lang_0 target. [Link](https://github.com/AdoptOpenJDK/openjdk-tests/issues/1773)
- July 2020: Sophia spots the underlying issue and specifies CheckHandles.java as something that should be run in a seperate, native target. [Link.](https://github.com/AdoptOpenJDK/openjdk-tests/issues/1920)
- July 2020: Sophia moves CheckHandles.java into a native target, and prevents it running anywhere else. [Link.](https://github.com/AdoptOpenJDK/openjdk-tests/pull/1926)
- October 2020: Shelley spots that the native target run of CheckHandles.java continues to see the link issue. Raises this issue.
- October 2020: Shelley points this problem out during the October release. [Link.](https://github.com/AdoptOpenJDK/TSC/issues/182#issuecomment-715530896)
- January 2021: Adam starts doing triage again, and sees that the issue is still happening.

**Comment by sophia-guo** [comment] 2021-01-27 17:15
#1920 set jdk_lang_native_win as a separate testcase with only one test  java/lang/ProcessBuilder/checkHandles/CheckHandles.java to fix the native path issue. It doesn't use exclude problem list story. That's why test is still running on win32 with excluded in problemlist.  

I didn't remember any issue with win32 as the problem hit by me was on github runner with windows64. 

Looks like the win 32 issue has nothing to do with the native path issue as the failure is same before and after native path is added.

**Comment by adamfarley** [comment] 2021-01-28 18:21
@smlambert - Could you please launch a grinder test at Eclipse OpenJ9's CI, so I can compare openj9Settings.mk behaviour in their [passing test](https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_mac_Personal_testList_1/102/consoleText) compared to the output in our [failing](https://trss.adoptopenjdk.net/output/test?id=601133348a00d84d71f733ff) [test](https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.functional_x86-64_mac/85/consoleFull)?

If [this](https://github.com/eclipse/openj9/pull/3765/files) could solve our problem, I first need to know why it's not preventing the failure for Adopt when it seems to be working at Eclipse/openj9.

Parameters:
- ADOPTOPENJDK_REPO: https://github.com/adamfarley/openjdk-tests.git
- ADOPTOPENJDK_BRANCH: openj9_settings_debug
- PLATFORM: x86-64_mac
- BUILD_LIST: functional
- TARGET: cmdLineTest_sigabrtHandlingTest_0
- SDK_RESOURCE: nightly
- JDK_VERSION: 8
- JDK_IMPL: openj9


Additionally, here's the output from that parameter set [when run on Adopt's CI](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/6175/console).

```
18:01:32  JCL_VERSION is set to 
18:01:32  JAVA_SHARED_LIBRARIES_DIR is set to /Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/Contents/Home/bin/..//../native-test-libs/
18:01:32  VM_SUBDIR is set to compressedrefs
18:01:32  ADD_JVM_LIB_DIR_TO_LIBPATH is set to export DYLD_LIBRARY_PATH="/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/Contents/Home/bin/..//../native-test-libs/:
```

**Comment by smlambert** [comment] 2021-01-28 18:41
Grinder started: https://ci.eclipse.org/openj9/job/Grinder/1482

**Comment by adamfarley** [comment] 2021-02-01 13:51
My mistake: the grinder I asked for above was meant for #2178. Will copy the details over.

**Comment by adamfarley** [comment] 2021-03-01 16:15
FYI: Currently poking about locally, to figure out what's happening here. Will post information when I have any.

**Comment by adamfarley** [comment] 2021-03-09 16:29
Using the Visual Studio "dumpbin" tool to list the exports for the 64bit and 32bit dll files.

64bit: 
```
    ordinal hint RVA      name
          1    0 00001000 Java_jdk_test_lib_util_FileUtils_getWinProcessHandleCount
```

32bit:
```
    ordinal hint RVA      name
          1    0 00001000 _Java_jdk_test_lib_util_FileUtils_getWinProcessHandleCount@4
```

The difference seems to be that the exported function in the 32bit dll has an underscore at the start, and an "@4" at the end.

Currently Googling to see what that means, and whether it's responsible for us being unable to find the exported function.

**Comment by adamfarley** [comment] 2021-03-16 13:00
Back to basics.

This test was created for JDK15, and back ported as far as jdk11. There is no JDK8u version because the issue that spawned this test was confirmed not to occur on JDK8u or 9.

Since the last version of OpenJDK that was supported on Windows 32bit is JDK8u, this seems a solid argument for excluding the test. This test was never intended to run on JDK8u, and the issue it is checking for was confirmed to never occur on 8u.

If anyone wants to investigate this in the future, I think this test isn't working because the exported method in the dll file undergoes name mangling (See above comment, and also [this wiki page on name mangling](https://en.wikipedia.org/wiki/Name_mangling)). So while the dll file itself can be found, the exported method is not.

Since it seems that openjdk's copy of JNA (e.g. Kernal32.java) doesn't include StdCallLibrary, my theory is that we're not correctly handling the name mangling, and that is causing this problem.

Proposed long-term solution: exclude the test on 32-bit windows, as it was never intended to run there, and may never have passed there (see [timeline](https://github.com/AdoptOpenJDK/openjdk-tests/issues/2029#issuecomment-768181363)).

Raising a PR for the exclude shortly.

**Comment by adamfarley** [comment] 2021-03-17 10:22
Merged. Closing this issue.

**Closed by adamfarley** 2021-03-17 10:22 UTC
Labels: triage required
