### ISSUE TITLE
mac: jdk_management : com/sun/management/OperatingSystemMXBean/GetCommittedVirtualMemorySize.java failed with Execution failed: `main' threw exception: java.lang.RuntimeException: Committed virtual memory size illegal value: 4480126976 bytes (MIN = 1; MAX = 3221225472)

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#134] opened 2017-10-04 18:16 UTC
<pre>
21:44:39 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Committed virtual memory size illegal value: 4480126976 bytes (MIN = 1; MAX = 3221225472)
21:44:39 REASON: Assumed action based on file name: run main GetCommittedVirtualMemorySize 
21:44:39 TIME:   0.018 seconds
21:44:39 messages:
21:44:39 command: main GetCommittedVirtualMemorySize
21:44:39 reason: Assumed action based on file name: run main GetCommittedVirtualMemorySize 
21:44:39 Mode: agentvm
21:44:39 Agent id: 0
21:44:39 elapsed time (seconds): 0.018
21:44:39 configuration:
21:44:39 Boot Layer
21:44:39   class path: /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar
21:44:39               /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar
21:44:39               /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar
21:44:39 
21:44:39 Test Layer
21:44:39   class path: /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/com/sun/management/OperatingSystemMXBean/GetCommittedVirtualMemorySize.d
21:44:39               /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/com/sun/management/OperatingSystemMXBean
21:44:39 
21:44:39 rerun:
21:44:39 HOME=/Users/jenkins \
21:44:39 PATH=/bin:/usr/bin \
21:44:39     /Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
21:44:39         -Dtest.class.path.prefix=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/com/sun/management/OperatingSystemMXBean/GetCommittedVirtualMemorySize.d:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/com/sun/management/OperatingSystemMXBean \
21:44:39         -Dtest.src=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/com/sun/management/OperatingSystemMXBean \
21:44:39         -Dtest.src.path=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/com/sun/management/OperatingSystemMXBean \
21:44:39         -Dtest.classes=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/com/sun/management/OperatingSystemMXBean/GetCommittedVirtualMemorySize.d \
21:44:39         -Dtest.class.path=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/com/sun/management/OperatingSystemMXBean/GetCommittedVirtualMemorySize.d \
21:44:39         -Dtest.vm.opts='-ea -esa -Xmx512m' \
21:44:39         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
21:44:39         -Dtest.compiler.opts= \
21:44:39         -Dtest.java.opts= \
21:44:39         -Dtest.jdk=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../.. \
21:44:39         -Dcompile.jdk=/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../.. \
21:44:39         -Dtest.timeout.factor=4.0 \
21:44:39         -classpath /Users/jenkins/workspace/openjdk8_test_x86-64_macos/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/com/sun/management/OperatingSystemMXBean/GetCommittedVirtualMemorySize.d:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/com/sun/management/OperatingSystemMXBean:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/Users/jenkins/workspace/openjdk8_test_x86-64_macos/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
21:44:39         GetCommittedVirtualMemorySize
21:44:39 STDERR:
21:44:39 java.lang.RuntimeException: Committed virtual memory size illegal value: 4480126976 bytes (MIN = 1; MAX = 3221225472)
21:44:39 	at GetCommittedVirtualMemorySize.main(GetCommittedVirtualMemorySize.java:91)
21:44:39 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:44:39 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:44:39 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:44:39 	at java.lang.reflect.Method.invoke(Method.java:498)
21:44:39 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
21:44:39 	at java.lang.Thread.run(Thread.java:748)
</pre>

**Comment by akolarkunnu** [comment] 2018-03-15 08:45
It is a duplicate of openjdk bug https://bugs.openjdk.java.net/browse/JDK-8031036.

**Comment by smlambert** [comment] 2018-03-18 02:03
Closing as now listed in summary issue #345

**Closed by smlambert** 2018-03-18 02:03 UTC
Labels: Reported/Fixed Upstream, bug, java8, mac
