### ISSUE TITLE
jdk_lang: jdk/lambda/vm/InterfaceAccessFlagsTest.java failed with ACTION: testng -- Intermittent failure. Execution failed: `main' threw exception: java.lang.Exception: failures: 3

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-tests#126] opened 2017-10-03 14:50 UTC
00:00:19 ACTION: testng -- Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 3
00:00:19 REASON: Assumed action based on file name: run testng vm.InterfaceAccessFlagsTest 
00:00:19 TIME:   0.71 seconds
00:00:19 messages:
00:00:19 command: testng vm.InterfaceAccessFlagsTest
00:00:19 reason: Assumed action based on file name: run testng vm.InterfaceAccessFlagsTest 
00:00:19 Mode: agentvm
00:00:19 Agent id: 5
00:00:19 elapsed time (seconds): 0.71
00:00:19 configuration:
00:00:19 Boot Layer
00:00:19   class path: /home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/TestConfig/lib/jtreg/lib/testng.jar
00:00:19               /home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/TestConfig/lib/jtreg/lib/jcommander.jar
00:00:19               /home/jenkins/workspace/test_x86-64_linux_experimental/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar
00:00:19               /home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar
00:00:19               /home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar
00:00:19 
00:00:19 Test Layer
00:00:19   class path: /home/jenkins/workspace/test_x86-64_linux_experimental/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/jdk/lambda
00:00:19               /home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/jdk/lambda
00:00:19 
00:00:19 rerun:
00:00:19 HOME=/home/jenkins \
00:00:19 LANG=en_US.UTF-8 \
00:00:19 PATH=/bin:/usr/bin \
00:00:19     /home/jenkins/workspace/test_x86-64_linux_experimental/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \
00:00:19         -Dtest.class.path.prefix=/home/jenkins/workspace/test_x86-64_linux_experimental/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/jdk/lambda:/home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/jdk/lambda \
00:00:19         -Dtest.src=/home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/jdk/lambda \
00:00:19         -Dtest.src.path=/home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/jdk/lambda \
00:00:19         -Dtest.classes=/home/jenkins/workspace/test_x86-64_linux_experimental/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/jdk/lambda \
00:00:19         -Dtest.class.path=/home/jenkins/workspace/test_x86-64_linux_experimental/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/jdk/lambda \
00:00:19         -Dtest.vm.opts='-ea -esa -Xmx512m' \
00:00:19         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
00:00:19         -Dtest.compiler.opts= \
00:00:19         -Dtest.java.opts= \
00:00:19         -Dtest.jdk=/home/jenkins/workspace/test_x86-64_linux_experimental/openjdkbinary/j2sdk-image/jre/bin/../.. \
00:00:19         -Dcompile.jdk=/home/jenkins/workspace/test_x86-64_linux_experimental/openjdkbinary/j2sdk-image/jre/bin/../.. \
00:00:19         -Dtest.timeout.factor=4.0 \
00:00:19         -classpath /home/jenkins/workspace/test_x86-64_linux_experimental/jvmtest/OpenJDK_Playlist/SE80/work/classes/1/jdk/lambda:/home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/OpenJDK_Playlist/openjdk-jdk/jdk/test/jdk/lambda:/home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/TestConfig/lib/jtreg/lib/testng.jar:/home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/TestConfig/lib/jtreg/lib/jcommander.jar:/home/jenkins/workspace/test_x86-64_linux_experimental/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/TestConfig/lib/jtreg/lib/javatest.jar:/home/jenkins/workspace/test_x86-64_linux_experimental/openjdk-test/TestConfig/lib/jtreg/lib/jtreg.jar \
00:00:19         com.sun.javatest.regtest.agent.TestNGRunner jdk/lambda/vm/InterfaceAccessFlagsTest.java false vm.InterfaceAccessFlagsTest
00:00:19 STDOUT:
00:00:19 [TestNG] Running:
00:00:19   jdk/lambda/vm/InterfaceAccessFlagsTest.java
00:00:19 
00:00:19 test vm.InterfaceAccessFlagsTest.testPrivateMethodCall(): failure
00:00:19 java.lang.RuntimeException: IOException encountered during compilation
00:00:19 	at separate.Compiler.compileOne(Compiler.java:191)
00:00:19 	at separate.Compiler.compileHierarchy(Compiler.java:135)
00:00:19 	at separate.Compiler.compile(Compiler.java:111)
00:00:19 	at vm.InterfaceAccessFlagsTest.testMethodCallWithFlag(InterfaceAccessFlagsTest.java:56)
00:00:19 	at vm.InterfaceAccessFlagsTest.testPrivateMethodCall(InterfaceAccessFlagsTest.java:76)
00:00:19 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:00:19 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:00:19 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:00:19 	at java.lang.reflect.Method.invoke(Method.java:498)
00:00:19 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
00:00:19 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
00:00:19 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
00:00:19 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
00:00:19 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
00:00:19 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
00:00:19 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
00:00:19 	at org.testng.TestRunner.run(TestRunner.java:623)
00:00:19 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
00:00:19 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
00:00:19 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
00:00:19 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
00:00:19 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
00:00:19 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
00:00:19 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
00:00:19 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
00:00:19 	at org.testng.TestNG.run(TestNG.java:1018)
00:00:19 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
00:00:19 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:00:19 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:00:19 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:00:19 	at java.lang.reflect.Method.invoke(Method.java:498)
00:00:19 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
00:00:19 	at java.lang.Thread.run(Thread.java:748)
00:00:19 Test InterfaceAccessFlagsTest.testPrivateMethodCall FAILED
00:00:19 config separate.TestHarness.printError(org.testng.internal.TestResult@5532c145): success
00:00:19 config separate.TestHarness.reset(): success
00:00:19 test vm.InterfaceAccessFlagsTest.testPrivateStaticMethodCall(): failure
00:00:19 java.lang.RuntimeException: IOException encountered during compilation
00:00:19 	at separate.Compiler.compileOne(Compiler.java:191)
00:00:19 	at separate.Compiler.compileHierarchy(Compiler.java:135)
00:00:19 	at separate.Compiler.compile(Compiler.java:111)
00:00:19 	at vm.InterfaceAccessFlagsTest.testMethodCallWithFlag(InterfaceAccessFlagsTest.java:56)
00:00:19 	at vm.InterfaceAccessFlagsTest.testPrivateStaticMethodCall(InterfaceAccessFlagsTest.java:86)
00:00:19 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:00:19 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:00:19 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:00:19 	at java.lang.reflect.Method.invoke(Method.java:498)
00:00:19 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
00:00:19 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
00:00:19 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
00:00:19 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
00:00:19 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
00:00:19 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
00:00:19 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
00:00:19 	at org.testng.TestRunner.run(TestRunner.java:623)
00:00:19 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
00:00:19 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
00:00:19 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
00:00:19 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
00:00:19 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
00:00:19 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
00:00:19 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
00:00:19 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
00:00:19 	at org.testng.TestNG.run(TestNG.java:1018)
00:00:19 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
00:00:19 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:00:19 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:00:19 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:00:19 	at java.lang.reflect.Method.invoke(Method.java:498)
00:00:19 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
00:00:19 	at java.lang.Thread.run(Thread.java:748)
00:00:19 Test InterfaceAccessFlagsTest.testPrivateStaticMethodCall FAILED
00:00:19 config separate.TestHarness.printError(org.testng.internal.TestResult@3995488e): success
00:00:19 config separate.TestHarness.reset(): success
00:00:19 test vm.InterfaceAccessFlagsTest.testStaticMethodCall(): failure
00:00:19 java.lang.RuntimeException: IOException encountered during compilation
00:00:19 	at separate.Compiler.compileOne(Compiler.java:191)
00:00:19 	at separate.Compiler.compileHierarchy(Compiler.java:135)
00:00:19 	at separate.Compiler.compile(Compiler.java:111)
00:00:19 	at vm.InterfaceAccessFlagsTest.testMethodCallWithFlag(InterfaceAccessFlagsTest.java:56)
00:00:19 	at vm.InterfaceAccessFlagsTest.testStaticMethodCall(InterfaceAccessFlagsTest.java:81)
00:00:19 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:00:19 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:00:19 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:00:19 	at java.lang.reflect.Method.invoke(Method.java:498)
00:00:19 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
00:00:19 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
00:00:19 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
00:00:19 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
00:00:19 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
00:00:19 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
00:00:19 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
00:00:19 	at org.testng.TestRunner.run(TestRunner.java:623)
00:00:19 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
00:00:19 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
00:00:19 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
00:00:19 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
00:00:19 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
00:00:19 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
00:00:19 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
00:00:19 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
00:00:19 	at org.testng.TestNG.run(TestNG.java:1018)
00:00:19 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
00:00:19 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:00:19 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:00:19 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:00:19 	at java.lang.reflect.Method.invoke(Method.java:498)
00:00:19 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
00:00:19 	at java.lang.Thread.run(Thread.java:748)
00:00:19 Test InterfaceAccessFlagsTest.testStaticMethodCall FAILED
00:00:19 config separate.TestHarness.printError(org.testng.internal.TestResult@6c74f54): success
00:00:19 config separate.TestHarness.reset(): success
00:00:19

**Comment by akolarkunnu** [comment] 2018-03-15 08:33
It is a duplicate of openjdk bug https://bugs.openjdk.java.net/browse/JDK-8044051.

**Comment by smlambert** [comment] 2018-03-18 01:59
Closing as now listed in summary issue #345

**Closed by smlambert** 2018-03-18 01:59 UTC
Labels: Reported/Fixed Upstream, bug
