### ISSUE TITLE
jlink fails with openjdk(11|12|13) binaries for macOS: Error: Hash of java.rmi differs to expected hash recorded in java.base 

### ISSUE THREAD

**Issue by gubatron** [AdoptOpenJDK/openjdk-tests#1293] opened 2019-08-21 22:19 UTC
perhaps [this issue](https://github.com/AdoptOpenJDK/openjdk12-binaries/issues/1) will get a bit more attention here, more people involved in this repo.

`jlink` is broken on all macOS builds I've downloaded.

I've downloaded 3 different builds for macOS (x64/hotspot) (jdk11, jdk12, jdk13) and every time I try to create a custom jre with `jlink `I always have the following issue:

```bash
jlink --no-header-files --no-man-pages --add-modules --compress=1 java.base,java.compiler,java.desktop,java.instrument,java.management,jdk.management.agent,java.naming,java.prefs,java.scripting,java.sql,jdk.jdwp.agent,jdk.net,jdk.unsupported,jdk.security.auth,jdk.pack,jdk.crypto.cryptoki --output jre

Error: Hash of java.rmi (65cbca076e0ec4c90e2704d4fb8f4d7d121c0f0618a4af0381c9cc6aa58bc49c) differs to expected hash (e8e7adf5a12eba7ad5e980dfb857ab3ae770e4fce2a6cbffa83334d80436c38e) recorded in java.base
```

any help would be appreciated. I bet I'm not going to be the first ending up here given the Apple Store notarization requirements that don't pass with Oracle's JVM due to their .dylib files being built with an older MacSDK version. I was hoping AdoptOpenJDK uses newer MacSDK versions to build and finally be able to pass notarization without going down the rabbit hole of trying to build the JDK myself and risk incompatibility issues.

**Comment by smlambert** [comment] 2019-08-21 22:33
This is indeed a problem, our jlink test failed, and the issue is related to code signing (a new step now required as part of building the binaries), we have reported the issue to the openjdk-build repo under this issue: https://github.com/AdoptOpenJDK/openjdk-build/issues/1214, so I will close this issue in the test repo, as the fix required is at the build repo.

The binaries are being rolled back, under https://github.com/AdoptOpenJDK/TSC/issues/107 (linked here to let you know where to track the progress).

**Closed by smlambert** 2019-08-21 22:33 UTC

**Comment by gubatron** [comment] 2019-08-22 04:31
Thank you so much
