### ISSUE TITLE
jdk_tools: sun/tools/jstatd/TestJstatdDefaults.java fails (malformed VM identifier)

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#60] opened 2017-06-15 02:54 UTC
jstat fails to start due to Malformed VM Identifier: 23894@test-packet-x64-ubuntu-16.04-1, output from https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_linux/34/consoleFull:

21:33:25 Start jstat:
21:33:25 [/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/jstat -J-XX:+UsePerfData -J-Duser.language=en -gcutil 23894@test-packet-x64-ubuntu-16.04-1 250 5]
21:33:25 Malformed VM Identifier: 23894@test-packet-x64-ubuntu-16.04-1
21:33:25 Usage: jstat -help|-options
21:33:25        jstat -<option> [-t] [-h<lines>] <vmid> [<interval> [<count>]]
21:33:25 
21:33:25 Definitions:
21:33:25   <option>      An option reported by the -options option
21:33:25   <vmid>        Virtual Machine Identifier. A vmid takes the following form:
21:33:25                      <lvmid>[@<hostname>[:<port>]]
21:33:25                 Where <lvmid> is the local vm identifier for the target
21:33:25                 Java virtual machine, typically a process id; <hostname> is
21:33:25                 the name of the host running the target Java virtual machine;
21:33:25                 and <port> is the port number for the rmiregistry on the
21:33:25                 target host. See the jvmstat documentation for a more complete
21:33:25                 description of the Virtual Machine Identifier.
21:33:25   <lines>       Number of samples between header lines.
21:33:25   <interval>    Sampling interval. The following forms are allowed:
21:33:25                     <n>["ms"|"s"]
21:33:25                 Where <n> is an integer and the suffix specifies the units as 
21:33:25                 milliseconds("ms") or seconds("s"). The default units are "ms".
21:33:25   <count>       Number of samples to take before terminating.
21:33:25   -J<flag>      Pass <flag> directly to the runtime system.
21:33:25 
21:33:25 ProcessThread.stopProcess() will kill process
21:33:25 --- ProcessLog ---
21:33:25 cmd: /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/jstatd -J-XX:+UsePerfData -J-Djava.security.policy=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/sun/tools/jstatd/all.policy -J-Dparent.pid.19954
21:33:25 exitvalue: 143
21:33:25 stderr: 
21:33:25 stdout: 
21:33:25 
21:33:25 STDERR:
21:33:25  stdout: [];
21:33:25  stderr: [Malformed VM Identifier: 23894@test-packet-x64-ubuntu-16.04-1
21:33:25 Usage: jstat -help|-options
21:33:25        jstat -<option> [-t] [-h<lines>] <vmid> [<interval> [<count>]]
21:33:25 
21:33:25 Definitions:
21:33:25   <option>      An option reported by the -options option
21:33:25   <vmid>        Virtual Machine Identifier. A vmid takes the following form:
21:33:25                      <lvmid>[@<hostname>[:<port>]]
21:33:25                 Where <lvmid> is the local vm identifier for the target
21:33:25                 Java virtual machine, typically a process id; <hostname> is
21:33:25                 the name of the host running the target Java virtual machine;
21:33:25                 and <port> is the port number for the rmiregistry on the
21:33:25                 target host. See the jvmstat documentation for a more complete
21:33:25                 description of the Virtual Machine Identifier.
21:33:25   <lines>       Number of samples between header lines.
21:33:25   <interval>    Sampling interval. The following forms are allowed:
21:33:25                     <n>["ms"|"s"]
21:33:25                 Where <n> is an integer and the suffix specifies the units as 
21:33:25                 milliseconds("ms") or seconds("s"). The default units are "ms".
21:33:25   <count>       Number of samples to take before terminating.
21:33:25   -J<flag>      Pass <flag> directly to the runtime system.
21:33:25 ]
21:33:25  exitValue = 1
21:33:25 
21:33:25 java.lang.RuntimeException: Expected to get exit value of [0]
21:33:25 
21:33:25 	at jdk.testlibrary.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:361)
21:33:25 	at JstatdTest.verifyJstatOutput(JstatdTest.java:246)
21:33:25 	at JstatdTest.runToolsAndVerify(JstatdTest.java:259)
21:33:25 	at JstatdTest.doTest(JstatdTest.java:361)
21:33:25 	at TestJstatdDefaults.main(TestJstatdDefaults.java:35)
21:33:25 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:33:25 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:33:25 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:33:25 	at java.lang.reflect.Method.invoke(Method.java:498)
21:33:25 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
21:33:25 	at java.lang.Thread.run(Thread.java:748)
21:33:25 
21:33:25 JavaTest Message: Test threw exception: java.lang.RuntimeException
21:33:25 JavaTest Message: shutting down test
21:33:25 
21:33:25 
21:33:25 TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]

**Comment by sophia-guo** [comment] 2017-10-03 16:09
Duplicate of #115

**Closed by sophia-guo** 2017-10-03 16:09 UTC
Labels: linux
