### ISSUE TITLE
MBCS_Tests_* fail for JP, TW and KR on Test_openjdk8_j9_special.functional_x86-64_linux

### ISSUE THREAD

**Issue by austin0** [AdoptOpenJDK/openjdk-tests#1929] opened 2020-08-03 13:58 UTC
**Describe the bug**
The following MBCS tests are failing intermittently on OpenJ9-based builds:

- MBCS_Tests_urlclassloader_ja_JP_linux_0

- MBCS_Tests_urlclassloader_zh_TW_linux_0

- MBCS_Tests_urlclassloader_ko_KR_linux_0

- MBCS_Tests_coin_ja_JP_linux_0

- MBCS_Tests_coin_zh_TW_linux_0

- MBCS_Tests_coin_ko_KR_linux_0

see https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.functional_x86-64_linux/290/tapResults/

Issues have been seen on both jdk8 and jdk14 (https://ci.adoptopenjdk.net/job/Test_openjdk14_j9_special.functional_x86-64_linux/157/).

MBCS_Tests_urlclassloader_* tests fail with no useful error information.

MBCS_Tests_coin_* tests fail with the following output:

```
19:00:25  ===============================================
19:00:25  Running test MBCS_Tests_coin_ko_KR_linux_0 ...
19:00:25  ===============================================
19:00:25  MBCS_Tests_coin_ko_KR_linux_0 Start Time: Sun Aug  2 18:00:24 2020 Epoch Time (ms): 1596391224691
19:00:25  "/home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
19:00:25  JVMSHRC005I No shared class caches available
19:00:25  JVMSHRC005I No shared class caches available
19:00:25  cache cleanup done
19:00:25  variation: NoOptions
19:00:25  JVM_OPTIONS:  
19:00:25  { itercnt=1; \
19:00:25  mkdir -p "/home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/test_output_1596390416103/MBCS_Tests_coin_ko_KR_linux_0"; \
19:00:25  cd "/home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/test_output_1596390416103/MBCS_Tests_coin_ko_KR_linux_0"; \
19:00:25  LANG=ko_KR.UTF-8 bash /home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../../jvmtest/functional/MBCS_Tests/coin/test.sh; \
19:00:25  if [ $? -eq 0 ] ; then echo ""; echo "MBCS_Tests_coin_ko_KR_linux_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/TKG/..;  else echo ""; echo "MBCS_Tests_coin_ko_KR_linux_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/test_output_1596390416103/TestTargetResult";
19:00:38  1..6
19:00:38  ok 1 - SwitchTest
19:00:38  ok 2 - BinaryIntegralTest
19:00:38  not ok 3 - ExceptionTest
19:00:38  #   Failed test 'ExceptionTest'
19:00:38  #   at /home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../../jvmtest/functional/MBCS_Tests/coin/resultCheck.pl line 36.
19:00:38  not ok 4 - DiamondTest
19:00:38  #   Failed test 'DiamondTest'
19:00:38  #   at /home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../../jvmtest/functional/MBCS_Tests/coin/resultCheck.pl line 36.
19:00:38  not ok 5 - TryWithResourcesTest
19:00:38  #   Failed test 'TryWithResourcesTest'
19:00:38  #   at /home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../../jvmtest/functional/MBCS_Tests/coin/resultCheck.pl line 36.
19:00:38  ok 6 - SimplifiedVarargsTest
19:00:38  # Looks like you failed 3 tests of 6.
19:00:38  
19:00:38  MBCS_Tests_coin_ko_KR_linux_0_FAILED
```

**To Reproduce**
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.functional_x86-64_linux/290/console

**Expected behavior**
```
17:50:04  ===============================================
17:50:04  Running test MBCS_Tests_coin_ko_KR_linux_0 ...
17:50:04  ===============================================
17:50:04  MBCS_Tests_coin_ko_KR_linux_0 Start Time: Tue Jul 28 16:50:04 2020 Epoch Time (ms): 1595955004242
17:50:04  "/home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
17:50:04  JVMSHRC005I No shared class caches available
17:50:04  JVMSHRC005I No shared class caches available
17:50:04  cache cleanup done
17:50:04  variation: NoOptions
17:50:04  JVM_OPTIONS:  
17:50:04  { itercnt=1; \
17:50:04  mkdir -p "/home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/test_output_15959546452318/MBCS_Tests_coin_ko_KR_linux_0"; \
17:50:04  cd "/home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/test_output_15959546452318/MBCS_Tests_coin_ko_KR_linux_0"; \
17:50:04  LANG=ko_KR.UTF-8 bash /home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../../jvmtest/functional/MBCS_Tests/coin/test.sh; \
17:50:04  if [ $? -eq 0 ] ; then echo ""; echo "MBCS_Tests_coin_ko_KR_linux_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/TKG/..;  else echo ""; echo "MBCS_Tests_coin_ko_KR_linux_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/test_output_15959546452318/TestTargetResult";
17:50:15  1..6
17:50:15  ok 1 - SwitchTest
17:50:15  ok 2 - BinaryIntegralTest
17:50:15  ok 3 - ExceptionTest
17:50:15  ok 4 - DiamondTest
17:50:15  ok 5 - TryWithResourcesTest
17:50:15  ok 6 - SimplifiedVarargsTest
17:50:15  
17:50:15  MBCS_Tests_coin_ko_KR_linux_0_PASSED
```

**Additional context**
Failures have been across multiple different machines.
Last passing build: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.functional_x86-64_linux/285/
```
Checking out Revision 5a56dbdad3d5f12e30a162e6d85ffbd62dfcd7ac (origin/master)
Commit message: "Support extracting pax files (#1919)"
```
Earliest failing build found: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.functional_x86-64_linux/286/
```
Checking out Revision e55e5daa4631a894a86fc135fb0541ddd250d189 (origin/master)
Commit message: "Move openjdk java/util/zip/ZipFile/TestCleaner to special (#1913)"
```

**Comment by smlambert** [comment] 2020-08-03 15:48
Hi Austin,  I still owe you a best practices for triage session!  :)

For steps to reproduce, you have included the link to the Jenkins job console.  This is not very useful, as Jenkins jobs are not kept around very long, so in less than a week links like that will be stale.

A better option is for you to look at the end of that console output, where the test framework produces links to rerun any failing targets in a Grinder job.  So for this case, 6 targets fail, 6 rerun links are printed out:


20:02:07  TOTAL: 174   EXECUTED: 53   PASSED: 47   FAILED: 6   DISABLED: 0   SKIPPED: 121
20:02:07  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
20:02:07  To rebuild the failed test in a jenkins job, copy the following link and fill out the <Jenkins URL> and <FAILED test target>:
20:02:07  <Jenkins URL>/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=functional/MBCS_Tests&PLATFORM=x86-64_linux&TARGET=<FAILED test target>
20:02:07  
20:02:07  For example, to rebuild the failed tests in <Jenkins URL>=https://ci.adoptopenjdk.net/job/Grinder, use the following links:

 https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=functional/MBCS_Tests&PLATFORM=x86-64_linux&TARGET=MBCS_Tests_urlclassloader_ja_JP_linux_0

https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=functional/MBCS_Tests&PLATFORM=x86-64_linux&TARGET=MBCS_Tests_urlclassloader_ko_KR_linux_0

https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=functional/MBCS_Tests&PLATFORM=x86-64_linux&TARGET=MBCS_Tests_urlclassloader_zh_TW_linux_0

https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=functional/MBCS_Tests&PLATFORM=x86-64_linux&TARGET=MBCS_Tests_coin_ja_JP_linux_0

https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=functional/MBCS_Tests&PLATFORM=x86-64_linux&TARGET=MBCS_Tests_coin_ko_KR_linux_0

https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=functional/MBCS_Tests&PLATFORM=x86-64_linux&TARGET=MBCS_Tests_coin_zh_TW_linux_0


Those can be run at any Jenkins server where the Grinder job has been added (and by simply swapping out the server name in the URL).

**Comment by smlambert** [comment] 2020-08-03 15:54
Also based on Deep History in TRSS (which is the preferred tool for triage), this failure appears intermittent.
Example: https://trss.adoptopenjdk.net/deepHistory?testId=5f277cfd0bec7975ae084abc

Another interesting view from TRSS is seeing a test result across platforms and implementations, for this particular test run, it passed against HS and Corretto.  Example: https://trss.adoptopenjdk.net/testPerPlatform?testId=5f277cfd0bec7975ae084abc.  Since its an intermittent failure (that may be related to a particular machine missing some configuration needed), a triager would run Grinders of these test targets trying to determine the failure rate and any relationship to particular machines.

When there is a test failure that appears and is repeatable/reproducible (not intermittent like this one), interesting git diffs are in the source code repos (not just the git diff for test code repo that you shared).  TRSS grabs the diffs now to make it easier to report the reproducible failures:

**Git Diff of first seen failure and last success**
https://github.com/eclipse/openj9/compare/34cf4c075...660db2efc
https://github.com/eclipse/omr/compare/113e54219...2bb071341
https://github.com/ibmruntimes/openj9-openjdk-jdk8/compare/c82ff0c20f...28815f64

**Comment by toshiona** [comment] 2020-09-17 03:09
It seems the Japanese Kanji character, U+663B, triggered the issue.
Attaching is a sample code to reproduce the issue easily. Since it contains UTF-8 characters, please compile it under UTF-8 environment.

[ExceptionTestCode.java.txt](https://github.com/AdoptOpenJDK/openjdk-tests/files/5236000/ExceptionTestCode.java.txt)

**Comment by smlambert** [comment] 2020-09-17 12:23
So perhaps we need to put a [check for the UTF-8 locale](https://stackoverflow.com/questions/42784435/how-to-check-if-a-locale-is-utf-8) at the start of the test and abort with a message if it is not present.

**Comment by toshiona** [comment] 2020-09-17 12:31
Sorry. This problem can recreate in our Japanese UTF-8 environment. I think J9VM has some problem.

**Comment by takiguc** [comment] 2020-09-17 16:44
In case of JDK8 Nightly build, This issue might be fixed by 1.8.0_265-202008111718-b01.

```
$ 2020-08-05-08-20/jdk8u265-b01-jre/bin/java -showversion -jar ex.jar 
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-202008041719-b01)
Eclipse OpenJ9 VM (build master-2020312e3, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200804_734 (JIT enabled, AOT enabled)
OpenJ9   - 2020312e3
OMR      - 7b76a160b
JCL      - bf6e4d1c based on jdk8u265-b01)

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: ExceptionTestCode$????
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
	at java.security.AccessController.doPrivileged(AccessController.java:770)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
	at java.lang.J9VMInternals.prepareClassImpl(Native Method)
	at java.lang.J9VMInternals.prepare(J9VMInternals.java:303)
	at java.lang.Class.getMethodHelper(Class.java:1247)
	at java.lang.Class.getMethod(Class.java:1191)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
$ 2020-08-12-14-57/jdk8u265-b01-jre/bin/java -showversion -jar ex.jar 
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-202008111718-b01)
Eclipse OpenJ9 VM (build master-c739bf191, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200811_741 (JIT enabled, AOT enabled)
OpenJ9   - c739bf191
OMR      - e27fe4682
JCL      - 3a407abe based on jdk8u265-b01)
```

In case of JDK14 Nightly build, I could recreate this issue by following build, but it's the latest.
No fixed build was available for JDK14.

```
$ 2020-07-28-07-34/jdk-14.0.2+12-jre/bin/java -showversion -jar ex.jar
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12-202007272041)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-6b7bde031, JRE 14 Linux amd64-64-Bit Compressed References 20200727_160 (JIT enabled, AOT enabled)
OpenJ9   - 6b7bde031
OMR      - 8124c1385
JCL      - 23f997ca1a based on jdk-14.0.2+12)
Error: Unable to initialize main class ExceptionTestCode
Caused by: java.lang.NoClassDefFoundError: ExceptionTestCode$????

```

**Comment by takiguc** [comment] 2020-09-17 16:47
I assume the issue was fixed by
https://github.com/eclipse/openj9/pull/10226

**Comment by smlambert** [comment] 2020-10-21 15:54
Indeed, this issue is fixed via https://github.com/eclipse/openj9/pull/10226

**Closed by smlambert** 2020-10-21 15:54 UTC
Labels: bug
