### ISSUE TITLE
HCRLateAttachWorkload_0 Extended system test failure

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-tests#1555] opened 2020-01-15 16:35 UTC
Test failure in the JDK 11.0.6+10 release pipeline
Platform: Mac Hotspot

Eg. https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk11_hs_extended.system_x86-64_mac/122/

```
STF 04:32:56.918 - +------ Step 3 - Wait for Agent to complete, followed by the MiniMix test seconds later.
STF 04:32:56.918 - | Wait for processes to meet expectations
STF 04:32:56.918 - |   Processes: [LT, AG]
STF 04:32:56.918 - |
STF 04:32:56.918 - Monitoring processes: AG  LT 
AG  4:32:57 > Will attempt to attach to JVM with pid 71307
AG  4:32:57 > Attach will be done using agent jar file: /Users/jenkins/workspace/Test_openjdk11_hs_extended.system_x86-64_mac/jvmtest/system/openjdk-systemtest/openjdk.test.debugging/bin/StringModifierAgent.jar
AG  stderr Exception in thread "main" java.io.IOException: well-known file /var/folders/rt/8_by_h8n5g9d5jhp66cf_7d80000gr/T/.java_pid71307 is not secure: file's group should be the current group (which is -1) but the group is 0
AG  stderr 	at jdk.attach/sun.tools.attach.VirtualMachineImpl.checkPermissions(Native Method)
AG  stderr 	at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:108)
AG  stderr 	at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
AG  stderr 	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
AG  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.Attacher.main(Attacher.java:70)
STF 04:32:58.037 - **FAILED** Process AG  ended with exit code (1) and not the expected exit code/s (0)
STF 04:32:58.038 - Monitoring Report Summary:
STF 04:32:58.038 -   o Process AG  ended with exit code (1) and not the expected exit code/s (0)
STF 04:32:58.038 -   o Process LT  is still running
STF 04:32:58.038 - Killing processes: AG  LT 
STF 04:32:59.049 -   o Process LT  killed
STF 04:32:59.049 -   o Process AG  is not running
**FAILED** at step 3 (Wait for Agent to complete, followed by the MiniMix test seconds later.). Expected return value=0 Actual=1 at /Users/jenkins/workspace/Test_openjdk11_hs_extended.system_x86-64_mac/openjdk-tests/TKG/../TKG/test_output_15790911323735/HCRLateAttachWorkload_0/20200115-043255-HCRLateAttachWorkload/execute.pl line 149.
STF 04:32:59.062 - **FAILED** execute script failed. Expected return value=0 Actual=1
```

**Comment by Mesbah-Alam** [comment] 2020-01-15 16:46
```
well-known file /var/folders/rt/8_by_h8n5g9d5jhp66cf_7d80000gr/T/.java_pid71307 is not secure: file's group should be the current group (which is -1) but the group is 0
```

**Comment by smlambert** [comment] 2020-01-15 17:30
Then: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1353

**Comment by smlambert** [comment] 2020-02-22 17:45
closing this as duplicate of #1353

**Closed by smlambert** 2020-02-22 17:45 UTC
Labels: bug, triage required
