### ISSUE TITLE
jdk_rmi: java/rmi/registry/serialFilter/RegistryFilterTest.java impleDepthBuiltinNonRejectable() fails

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#62] opened 2017-06-15 03:11 UTC
RegistryFilterTest.impleDepthBuiltinNonRejectable(): fails with java.lang.AssertionError: Registry filter should not have rejected depth: 20, output from https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk_test_x86-64_linux/34/consoleFull:

20:34:41 HOME=/home/jenkins \
20:34:41 LANG=en_US.UTF-8 \
20:34:41 PATH=/bin:/usr/bin \
20:34:41     /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/javac \
20:34:41         -J-ea \
20:34:41         -J-esa \
20:34:41         -J-Xmx512m \
20:34:41         -J-Dtest.src=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/rmi/registry/serialFilter \
20:34:41         -J-Dtest.src.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/rmi/registry/serialFilter:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/rmi/testlibrary \
20:34:41         -J-Dtest.classes=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/rmi/registry/serialFilter \
20:34:41         -J-Dtest.class.path=/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/rmi/registry/serialFilter:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/rmi/testlibrary \
20:34:41         -J-Dtest.vm.opts='-ea -esa -Xmx512m' \
20:34:41         -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
20:34:41         -J-Dtest.compiler.opts= \
20:34:41         -J-Dtest.java.opts= \
20:34:41         -J-Dtest.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:34:41         -J-Dcompile.jdk=/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \
20:34:41         -J-Dtest.timeout.factor=4.0 \
20:34:41         -J-Dtest.modules='java.rmi/sun.rmi.registry java.rmi/sun.rmi.server java.rmi/sun.rmi.transport java.rmi/sun.rmi.transport.tcp' \
20:34:41         -d /home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/rmi/registry/serialFilter \
20:34:41         -sourcepath /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/rmi/registry/serialFilter:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/rmi/testlibrary \
20:34:41         -classpath /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/rmi/registry/serialFilter:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/rmi/registry/serialFilter:/home/jenkins/workspace/openjdk_test_x86-64_linux/jvmtest/OpenJDK_Playlist/SE80/work/classes/0/java/rmi/testlibrary:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/testng.jar:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/TestConfig/lib/jtreg/lib/jcommander.jar:/home/jenkins/workspace/openjdk_test_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar \
20:34:41         -XDignore.symbol.file=true /home/jenkins/workspace/openjdk_test_x86-64_linux/openjdk-test/OpenJDK_Playlist/openjdk-jdk8u/jdk/test/java/rmi/registry/serialFilter/RegistryFilterTest.java
20:34:41 STDOUT:
20:34:41 STDERR:
20:34:41 
20:34:41 ACTION: testng -- Failed. Execution failed: `main' threw exception: java.lang.Exception: failures: 1
20:34:41 REASON: User specified action: run testng/othervm RegistryFilterTest 
20:34:41 TIME:   1.75 seconds
20:34:41 messages:
20:34:41 command: testng RegistryFilterTest
20:34:41 reason: User specified action: run testng/othervm RegistryFilterTest 
20:34:41 Mode: othervm [/othervm specified]
20:34:41 elapsed time (seconds): 1.75
20:34:41 configuration:
20:34:41 STDOUT:
20:34:41 [TestNG] Running:
20:34:41   java/rmi/registry/serialFilter/RegistryFilterTest.java#id0
20:34:41 
20:34:41 RMI Registry filter: null
20:34:41 config RegistryFilterTest.setupRegistry(): success
20:34:41 test RegistryFilterTest.simpleBind("byte[max]", RegistryFilterTest$XX@c11f161, false): success
20:34:41 test RegistryFilterTest.simpleBind("String", RegistryFilterTest$XX@2cb48e04, false): success
20:34:41 test RegistryFilterTest.simpleBind("String[]", RegistryFilterTest$XX@472f40d6, false): success
20:34:41 test RegistryFilterTest.simpleBind("Long[4]", RegistryFilterTest$XX@e101f5c, false): success
20:34:41 test RegistryFilterTest.simpleBind("rej-byte[toobig]", RegistryFilterTest$XX@142f80e1, true): success
20:34:41 test RegistryFilterTest.simpleBind("rej-MarshalledObject", RegistryFilterTest$XX@d7250dc, true): success
20:34:41 test RegistryFilterTest.simpleBind("rej-RejectableClass", RegistryFilterTest$RejectableClass@25e2eeb7, false): success
20:34:41 overrideDepth: 20, filter: null
20:34:41 test RegistryFilterTest.simpleDepthBuiltinNonRejectable(): failure
20:34:41 java.lang.AssertionError: Registry filter should not have rejected depth: 20
20:34:41 	at org.testng.Assert.fail(Assert.java:94)
20:34:41 	at RegistryFilterTest.simpleDepthBuiltinNonRejectable(RegistryFilterTest.java:170)
20:34:41 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:34:41 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:34:41 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:34:41 	at java.lang.reflect.Method.invoke(Method.java:498)
20:34:41 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
20:34:41 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
20:34:41 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
20:34:41 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
20:34:41 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
20:34:41 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
20:34:41 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
20:34:41 	at org.testng.TestRunner.run(TestRunner.java:623)
20:34:41 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
20:34:41 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
20:34:41 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
20:34:41 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
20:34:41 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
20:34:41 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
20:34:41 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
20:34:41 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
20:34:41 	at org.testng.TestNG.run(TestNG.java:1018)
20:34:41 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
20:34:41 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
20:34:41 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:34:41 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:34:41 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:34:41 	at java.lang.reflect.Method.invoke(Method.java:498)
20:34:41 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
20:34:41 	at java.lang.Thread.run(Thread.java:748)
20:34:41 overrideDepth: 20, filter: null
20:34:41 test RegistryFilterTest.simpleDepthRejectable(): success
20:34:41 test RegistryFilterTest.simpleRejectableClass(): success

**Comment by akolarkunnu** [comment] 2018-01-12 10:30
I rerun this test case on linux and mac, and not able to reproduce. Also this test added in ProblemList_openjdk8.txt by referring to bug 61, not 62. Again this bug is for linux platform it added in ProblemList_openjdk8.txt for macosx platfrom.

**Comment by akolarkunnu** [comment] 2018-01-12 10:31
So I would suggest to close this bug and remove this test case from ProblemList

**Comment by smlambert** [comment] 2018-01-12 14:02
@akolarkunnu - if you feel comfortable to do so, please feel free to create a PR with the change to the ProblemList to reinclude the test.  I can review/merge.

**Comment by akolarkunnu** [comment] 2018-01-15 10:13
Created a PR https://github.com/AdoptOpenJDK/openjdk-tests/pull/216

**Comment by akolarkunnu** [comment] 2018-01-15 16:18
It resolved by PR #216

**Closed by akolarkunnu** 2018-01-15 16:18 UTC
Labels: bug, linux
