### ISSUE TITLE
Improve local test execution

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-tests#1046] opened 2019-03-29 12:39 UTC
The core problem is that running the tests locally is a convoluted process, and there appears to be no obvious "quick start" that works first time (at least, not for me).

I assert that the local test execution process needs be refined, so that only a small handful of commands need to be executed. Also, those brief commands should be spelt out at the top of the user docs.

### **Details:**

**User:** Someone who wants to execute the adopt test framework locally for defect investigation and reproduction.

**Test:** This specific test is HCRLateAttachWorkload (a system test), but I see no reason many of these issues should not affect.

**Problem 1:** The test documentation appears to be a script of commands to run, which must be tweaked and edited. These instructions need to be streamlined and shortened to make then more usable for the layman.

**Problem 2:** Jdk11 has a problem where it cannot compile the test material, because it goes into java_bin/../../bin and tries to find javac in there (which won't work on jdk11).

Error: ```/home/adamfarl/clones/test/stuff/openjdk-tests/TestConfig/src/build_envInfo.xml:42: Error running /home/adamfarl/jres/11j9/bin/../../bin/javac compiler```

**Problem 3:** The framework seems to have no concept of a hdd running out of space during setup. It uses up the space available to it in the tmp folder, and then fails. There should be an "x space is required" check at the start, and/or a useful error at the end.

**Problem 4:** The system test "HCRLateAttachWorkload" appears to fail to execute when run locally (*before* STF is called), so perhaps the docs should be updated to reflect the steps needed to execute this test, or the scripts should be updated to enable local test execution.

*Note:* the HCR failure occurs prior to STF being called. If you run the command in the systemtest playlist yourself:
```
cd $(OPENJDK_SYSTEMTEST_ROOT)/openjdk.build 
make test.HCRLateAttachWorkload
```
then the test runs and passes normally, though you do need to run the configure step yourself (it advises you of this during execution).

**Comment by adamfarley** [comment] 2019-03-29 12:43
Also, here's the set of commands I'm running when Problem 4 is seen:

```
export OPENJDK_SOURCES=/home/adamfarl/clones/8j9
export OPENJDK_BUILD=/home/adamfarl/jres/8j9
export tmpdir=/home/adamfarl/clones/test/stuff
export JAVA_HOME=/home/adamfarl/jres/8j9
export RESULTS_ROOT=/home/adamfarl/clones/test/results
pushd $tmpdir
git clone https://github.com/AdoptOpenJDK/openjdk-tests
cd openjdk-tests
export TOP_DIR=$(pwd)
export TEST_DIR="$TOP_DIR"
pushd systemtest
ln -s $OPENJDK_SOURCES openjdk-jdk
popd
export JAVA_BIN=$OPENJDK_BUILD/jre/bin
export BUILD_LIST=systemtest
export BUILD_ROOT=$TOP_DIR/test-results
./get.sh -t $TEST_DIR
./maketest.sh $TEST_DIR
OPENJDK_DIR=$OPENJDK_SOURCES ./maketest.sh $TEST_DIR HCRLateAttachWorkload
popd
echo "openjdk-tests located at $tmpdir/openjdk-tests"
```

The problem is seen during execution of the third command from the end.

**Comment by smlambert** [comment] 2019-04-01 15:57
We definitely need an update to the documentation.  

I believe you are following the doc that describes a very particular case added by @jerboaa, where you set up to compile your own JDK.  Some of those steps may be confusing and are unnecessary if you have a JDK that you have simply downloaded and wish to test.

1) Clone openjdk-tests:
    git clone https://github.com/AdoptOpenJDK/openjdk-tests
    cd openjdk-tests

2) Export env vars:
    export JAVA_BIN=$OPENJDK_BUILD/jre/bin  (for jdk9+ use $OPENJDK_BUILD/bin)
    export BUILD_LIST=systemtest

3) Fetch testkitgen:
    ./get.sh -t $(pwd)

4) Configure and make the test material:  
./maketest.sh $(pwd)

5) Run the test:
make HCRLateAttachWorkload

2 things we are looking at updating:

- get.sh currently can fetch a JDK and gets testkitgen.  We should separate this functionality, have a getsdk.sh script for those convenience download of an JDK from Adopt API and move the getting of testkitgen into maketest.sh (thus collapsing steps 3 & 4 into a single step if you already have an JDK)

- instead of using JAVA_BIN and expect user to set to jre/bin for jdk8 and bin for jdk11, just ask for TEST_JDK_HOME which should be home dir for the JDK that you want to test.

**If we make those 2 changes**, the steps are simplified to:
1) Clone openjdk-tests:
    git clone https://github.com/AdoptOpenJDK/openjdk-tests
    cd openjdk-tests

2) Export env vars:
    export TEST_JDK_HOME=$OPENJDK_BUILD  
    export BUILD_LIST=systemtest

3) Fetch testkitgen (if first run) and configure and make the test material:  
./maketest.sh $(pwd)

4) Run the test:
make HCRLateAttachWorkload


Additionally as you point out, one is certainly still free to run the underlying frameworks for the different type of tests directly whether it be stf or jtreg or junit or testng or some type of benchmark.  

But it is not how we will advise or support people to run the tests (as there are too many variations in instructions for fetching/downloading repos, building test material and execution (when you look across the different groups of tests we run).

**Comment by smlambert** [comment] 2020-10-06 21:04
I am closing this as all of the actions that we planned to take have been done (no plans to determine if sufficient disk space is available as that is left to the user, since we have options for overlaying private test material via VENDOR_REPO variable, we can not predict space required).  

Instructions and examples for running locally are at: https://github.com/eclipse/openj9/wiki/Reproducing-Test-Failures-Locally and will also be included in [Overhaul of AQA test documentation](https://github.com/AdoptOpenJDK/openjdk-tests/pull/1556) when it lands.

**Closed by smlambert** 2020-10-06 21:04 UTC
Labels: enhancement
