### ISSUE TITLE
Windows  jdk_native_sanity test fails on azure machines

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-tests#1471] opened 2019-11-27 14:23 UTC
It appears the jdk_native_sanity test on Windows passes on godaddy machines but fails on azure machines - see https://trss.adoptopenjdk.net/deepHistory?testId=5ddd0fd4440f9a5cbaaf02d5.
```
05:56:42  TEST: native_sanity/simplenativelauncher/ProgramTest.java
05:56:42  TEST JDK: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdkbinary\j2sdk-image
05:56:42  
05:56:42  ACTION: build -- Passed. Build successful
05:56:42  REASON: User specified action: run build jdk.testlibrary.OutputAnalyzer 
05:56:42  TIME:   1.562 seconds
05:56:42  messages:
05:56:42  command: build jdk.testlibrary.OutputAnalyzer
05:56:42  reason: User specified action: run build jdk.testlibrary.OutputAnalyzer 
05:56:42  Library /lib/testlibrary:
05:56:42    compile: jdk.testlibrary.OutputAnalyzer
05:56:42  elapsed time (seconds): 1.562
05:56:42  
05:56:42  ACTION: compile -- Passed. Compilation successful
05:56:42  REASON: .class file out of date or does not exist
05:56:42  TIME:   1.559 seconds
05:56:42  messages:
05:56:42  command: compile C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\lib\testlibrary\jdk\testlibrary\OutputAnalyzer.java
05:56:42  reason: .class file out of date or does not exist
05:56:42  Mode: agentvm
05:56:42  Agent id: 0
05:56:42  elapsed time (seconds): 1.559
05:56:42  configuration:
05:56:42  Boot Layer (javac runtime environment)
05:56:42    class path: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\jvmtest\openjdk\jtreg\lib\javatest.jar 
05:56:42                C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\jvmtest\openjdk\jtreg\lib\jtreg.jar 
05:56:42    patch:      java.base C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\patches\java.base
05:56:42  
05:56:42  javac compilation environment
05:56:42    source path: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\lib\testlibrary
05:56:42    class path:  C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\lib\testlibrary
05:56:42  
05:56:42  rerun:
05:56:42  cd 'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\scratch\0' && \
05:56:42  PATH='C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\cygwin64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Strawberry\perl\bin;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk8u172-b11\bin;C:\apache-ant\apache-ant-1.10.3\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0;C:\Program Files\Microsoft SQL Server\120\Tools\Binn' \
05:56:42  SystemDrive=C: \
05:56:42  SystemRoot='C:\Windows' \
05:56:42  TEMP='C:\Users\JENKIN~1.TES\AppData\Local\Temp' \
05:56:42  TMP='C:\Users\JENKIN~1.TES\AppData\Local\Temp' \
05:56:42  windir='C:\Windows' \
05:56:42      'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdkbinary\j2sdk-image\bin\javac' \
05:56:42          -J-ea \
05:56:42          -J-esa \
05:56:42          -J-Xmx512m \
05:56:42          -J-Xcompressedrefs \
05:56:42          -J'-Djava.library.path=C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdkbinary\openjdk-test-image\jdk\jtreg\native' \
05:56:42          -J-Dtest.class.path.prefix='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\native_sanity\simplenativelauncher;C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\lib\testlibrary' \
05:56:42          -J-Dtest.src='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\native_sanity\simplenativelauncher' \
05:56:42          -J-Dtest.src.path='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\native_sanity\simplenativelauncher;C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\lib\testlibrary' \
05:56:42          -J-Dtest.classes='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\native_sanity\simplenativelauncher\ProgramTest.d' \
05:56:42          -J-Dtest.class.path='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\native_sanity\simplenativelauncher\ProgramTest.d;C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\lib\testlibrary' \
05:56:42          -J-Dtest.vm.opts='-ea -esa -Xmx512m -Xcompressedrefs' \
05:56:42          -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-Xcompressedrefs' \
05:56:42          -J-Dtest.compiler.opts= \
05:56:42          -J-Dtest.java.opts= \
05:56:42          -J-Dtest.jdk='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdkbinary\j2sdk-image' \
05:56:42          -J-Dcompile.jdk='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdkbinary\j2sdk-image' \
05:56:42          -J-Dtest.timeout.factor=8.0 \
05:56:42          -J-Dtest.root='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk' \
05:56:42          -J-Dtest.nativepath='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdkbinary\openjdk-test-image\jdk\jtreg\native' \
05:56:42          -d 'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\lib\testlibrary' \
05:56:42          -sourcepath 'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\lib\testlibrary' \
05:56:42          -classpath 'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\lib\testlibrary' 'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\lib\testlibrary\jdk\testlibrary\OutputAnalyzer.java'
05:56:42  direct:
05:56:42  Note: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\lib\testlibrary\jdk\testlibrary\OutputAnalyzer.java uses or overrides a deprecated API.
05:56:42  Note: Recompile with -Xlint:deprecation for details.
05:56:42  
05:56:42  ACTION: build -- Passed. Build successful
05:56:42  REASON: User specified action: run build ProgramTest 
05:56:42  TIME:   0.426 seconds
05:56:42  messages:
05:56:42  command: build ProgramTest
05:56:42  reason: User specified action: run build ProgramTest 
05:56:42  Test directory:
05:56:42    compile: ProgramTest
05:56:42  elapsed time (seconds): 0.426
05:56:42  
05:56:42  ACTION: compile -- Passed. Compilation successful
05:56:42  REASON: .class file out of date or does not exist
05:56:42  TIME:   0.425 seconds
05:56:42  messages:
05:56:42  command: compile C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\native_sanity\simplenativelauncher\ProgramTest.java
05:56:42  reason: .class file out of date or does not exist
05:56:42  Mode: agentvm
05:56:42  Agent id: 0
05:56:42  elapsed time (seconds): 0.425
05:56:42  configuration:
05:56:42  Boot Layer (javac runtime environment)
05:56:42    class path: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\jvmtest\openjdk\jtreg\lib\javatest.jar 
05:56:42                C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\jvmtest\openjdk\jtreg\lib\jtreg.jar 
05:56:42    patch:      java.base C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\patches\java.base
05:56:42  
05:56:42  javac compilation environment
05:56:42    source path: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\native_sanity\simplenativelauncher
05:56:42                 C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\lib\testlibrary
05:56:42    class path:  C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\native_sanity\simplenativelauncher
05:56:42                 C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\native_sanity\simplenativelauncher\ProgramTest.d
05:56:42                 C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\lib\testlibrary
05:56:42  
05:56:42  rerun:
05:56:42  cd 'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\scratch\0' && \
05:56:42  PATH='C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\cygwin64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Strawberry\perl\bin;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk8u172-b11\bin;C:\apache-ant\apache-ant-1.10.3\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0;C:\Program Files\Microsoft SQL Server\120\Tools\Binn' \
05:56:42  SystemDrive=C: \
05:56:42  SystemRoot='C:\Windows' \
05:56:42  TEMP='C:\Users\JENKIN~1.TES\AppData\Local\Temp' \
05:56:42  TMP='C:\Users\JENKIN~1.TES\AppData\Local\Temp' \
05:56:42  windir='C:\Windows' \
05:56:42      'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdkbinary\j2sdk-image\bin\javac' \
05:56:42          -J-ea \
05:56:42          -J-esa \
05:56:42          -J-Xmx512m \
05:56:42          -J-Xcompressedrefs \
05:56:42          -J'-Djava.library.path=C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdkbinary\openjdk-test-image\jdk\jtreg\native' \
05:56:42          -J-Dtest.class.path.prefix='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\native_sanity\simplenativelauncher\ProgramTest.d;C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\native_sanity\simplenativelauncher;C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\lib\testlibrary' \
05:56:42          -J-Dtest.src='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\native_sanity\simplenativelauncher' \
05:56:42          -J-Dtest.src.path='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\native_sanity\simplenativelauncher;C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\lib\testlibrary' \
05:56:42          -J-Dtest.classes='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\native_sanity\simplenativelauncher\ProgramTest.d' \
05:56:42          -J-Dtest.class.path='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\native_sanity\simplenativelauncher\ProgramTest.d;C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\lib\testlibrary' \
05:56:42          -J-Dtest.vm.opts='-ea -esa -Xmx512m -Xcompressedrefs' \
05:56:42          -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-Xcompressedrefs' \
05:56:42          -J-Dtest.compiler.opts= \
05:56:42          -J-Dtest.java.opts= \
05:56:42          -J-Dtest.jdk='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdkbinary\j2sdk-image' \
05:56:42          -J-Dcompile.jdk='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdkbinary\j2sdk-image' \
05:56:42          -J-Dtest.timeout.factor=8.0 \
05:56:42          -J-Dtest.root='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk' \
05:56:42          -J-Dtest.nativepath='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdkbinary\openjdk-test-image\jdk\jtreg\native' \
05:56:42          -d 'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\native_sanity\simplenativelauncher\ProgramTest.d' \
05:56:42          -sourcepath 'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\native_sanity\simplenativelauncher;C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\lib\testlibrary' \
05:56:42          -classpath 'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\native_sanity\simplenativelauncher;C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\native_sanity\simplenativelauncher\ProgramTest.d;C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\lib\testlibrary' 'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\native_sanity\simplenativelauncher\ProgramTest.java'
05:56:42  direct:
05:56:42  C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\lib\testlibrary\jdk\testlibrary\ProcessTools.java:344: warning: [dep-ann] deprecated item is not annotated with @Deprecated
05:56:42      public static OutputAnalyzer executeTestJvm(String... options) throws Exception {
05:56:42                                   ^
05:56:42  Note: Some input files use or override a deprecated API.
05:56:42  Note: Recompile with -Xlint:deprecation for details.
05:56:42  1 warning
05:56:42  
05:56:42  ACTION: build -- Passed. All files up to date
05:56:42  REASON: Named class compiled on demand
05:56:42  TIME:   0.008 seconds
05:56:42  messages:
05:56:42  command: build ProgramTest
05:56:42  reason: Named class compiled on demand
05:56:42  elapsed time (seconds): 0.008
05:56:42  
05:56:42  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
05:56:42  REASON: User specified action: run main/native ProgramTest 
05:56:42  TIME:   0.716 seconds
05:56:42  messages:
05:56:42  command: main ProgramTest
05:56:42  reason: User specified action: run main/native ProgramTest 
05:56:42  Mode: agentvm
05:56:42  Agent id: 3
05:56:42  elapsed time (seconds): 0.716
05:56:42  configuration:
05:56:42  Boot Layer
05:56:42    class path: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\jvmtest\openjdk\jtreg\lib\javatest.jar 
05:56:42                C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\jvmtest\openjdk\jtreg\lib\jtreg.jar 
05:56:42    patch:      java.base C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\patches\java.base
05:56:42  
05:56:42  Test Layer
05:56:42    class path: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\native_sanity\simplenativelauncher\ProgramTest.d
05:56:42                C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\native_sanity\simplenativelauncher
05:56:42                C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\lib\testlibrary
05:56:42                C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\lib\testlibrary
05:56:42  
05:56:42  rerun:
05:56:42  cd 'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\scratch\0' && \
05:56:42  PATH='C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\cygwin64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Strawberry\perl\bin;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk8u172-b11\bin;C:\apache-ant\apache-ant-1.10.3\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0;C:\Program Files\Microsoft SQL Server\120\Tools\Binn' \
05:56:42  SystemDrive=C: \
05:56:42  SystemRoot='C:\Windows' \
05:56:42  TEMP='C:\Users\JENKIN~1.TES\AppData\Local\Temp' \
05:56:42  TMP='C:\Users\JENKIN~1.TES\AppData\Local\Temp' \
05:56:42  windir='C:\Windows' \
05:56:42      'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdkbinary\j2sdk-image\bin\java' \
05:56:42          -Dtest.class.path.prefix='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\native_sanity\simplenativelauncher\ProgramTest.d;C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\native_sanity\simplenativelauncher;C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\lib\testlibrary' \
05:56:42          -Dtest.src='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\native_sanity\simplenativelauncher' \
05:56:42          -Dtest.src.path='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\native_sanity\simplenativelauncher;C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\lib\testlibrary' \
05:56:42          -Dtest.classes='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\native_sanity\simplenativelauncher\ProgramTest.d' \
05:56:42          -Dtest.class.path='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\native_sanity\simplenativelauncher\ProgramTest.d;C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\lib\testlibrary' \
05:56:42          -Dtest.vm.opts='-ea -esa -Xmx512m -Xcompressedrefs' \
05:56:42          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-Xcompressedrefs' \
05:56:42          -Dtest.compiler.opts= \
05:56:42          -Dtest.java.opts= \
05:56:42          -Dtest.jdk='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdkbinary\j2sdk-image' \
05:56:42          -Dcompile.jdk='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdkbinary\j2sdk-image' \
05:56:42          -Dtest.timeout.factor=8.0 \
05:56:42          -Dtest.root='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk' \
05:56:42          -Dtest.nativepath='C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdkbinary\openjdk-test-image\jdk\jtreg\native' \
05:56:42          -classpath 'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\native_sanity\simplenativelauncher\ProgramTest.d;C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\native_sanity\simplenativelauncher;C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work\classes\0\lib\testlibrary;C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\lib\testlibrary;C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\jvmtest\openjdk\jtreg\lib\javatest.jar;C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\jvmtest\openjdk\jtreg\lib\jtreg.jar' \
05:56:42          ProgramTest
05:56:42  STDERR:
05:56:42   stdout: [];
05:56:42   stderr: []
05:56:42   exitValue = 255
05:56:42  
05:56:42  java.lang.RuntimeException: Expected to get exit value of [0]
05:56:42  
05:56:42  	at jdk.testlibrary.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:375)
05:56:42  	at ProgramTest.main(ProgramTest.java:40)
05:56:42  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05:56:42  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
05:56:42  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:56:42  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
05:56:42  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
05:56:42  	at java.base/java.lang.Thread.run(Thread.java:832)
05:56:42  
05:56:42  JavaTest Message: Test threw exception: java.lang.RuntimeException
05:56:42  JavaTest Message: shutting down test
05:56:42  
05:56:42  
05:56:42  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
05:56:42  --------------------------------------------------
05:56:42  Test results: passed: 2; failed: 1
05:56:51  Report written to C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\jvmtest\openjdk\report\html\report.html
05:56:51  Results written to C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TestConfig\test_output_1574743336826\jdk_native_sanity_0\work
05:56:51  Error: Some tests failed or other problems occurred.
05:56:51  
05:56:51  jdk_native_sanity_0_FAILED
```

**Comment by smlambert** [comment] 2019-11-27 14:28
I presume you are doing extra triage on this one, to verify that this is what it looks like, a difference in machine config, and subsequently would be raised in the openjdk-infrastructure repo.

**Comment by lumpfish** [comment] 2019-11-27 14:51
I assume it will end up being something which needs fixing in the machines, but it's not obvious to me what the difference is.  Can't be as simple are unzip not being present (failing to unzip the test package) because the jdk under test is also unzipped.
Raised it here in case someone else spots it and can see it's already raised (I think this repo is the first place people look?).

**Comment by smlambert** [comment] 2019-11-27 14:59
Yes I am just encouraging the raisers to further triage the issues they raise, following the [triage guidance](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/doc/Triage.md) in order to avoid a pile of stale issues (as there are no spare people to review the backlog very often).

**Comment by karianna** [comment] 2019-11-28 11:59
@d3r3kk and/or @junyzheng - are we seeing this internally?

**Comment by adam-thorpe** [comment] 2019-11-28 13:23
Yep this is a dupe of the above issue already raised at infra so this can be closed. I forgot to exclude the test which is why it still appears in the nightlies.

**Closed** 2019-11-29 13:17 UTC
Labels: bug, duplicate
