### ISSUE TITLE
jdk8u242-b08_openj9-0.18.0 : January Release 2020 - Build Triage (Failures)

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-tests#1567] opened 2020-01-21 11:10 UTC
Jenkins build pipeline ID: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/832/

Link to the TRSS Grid view of the pipeline: https://trss.adoptopenjdk.net/resultGrid?parentId=5e259832291346186002cf9c

Result summary (Failed/Passed/Disabled/Skipped/Total): 

**1. Faliure** 
    **Platform**
       ppc64_aix
  
   **Detail**
 sanity.openjdk failures
      java/io/Serializable/serialFilter/GlobalFilterTest.java.GlobalFilterTest - https://github.com/eclipse/openj9/issues/8352

java/nio/file/WatchService/LotsOfCancels.java.LotsOfCancels
-Rerunning the test: https://ci.adoptopenjdk.net/job/Grinder/1816/parameters/  : **Failed**
-Rerun again the test https://ci.adoptopenjdk.net/job/Grinder/1820/parameters/: **Passed**
-Looks like Intermittent test failures hence raised here: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1511

java/nio/file/WatchService/LotsOfEvents.java.LotsOfEvents
 Rerunning the test: https://ci.adoptopenjdk.net/job/Grinder/1817/parameters/ : **Passed**

sanity.system failures: Build failed 
      https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.system_ppc64_aix/3/
      Build appears to have failed because it failed to process the java system property os.name correctly, which it gets by running java -xshowSettings:properties and parsing the output.  Resubmitted the tests and they have started ok: https://ci.adoptopenjdk.net/job/Grinder/1818 : **Passed**

**Comment by adam-thorpe** [comment] 2020-01-21 11:17
**2. Failure**
**Platform:**
x64_linux

sanity.openjdk
java/io/Serializable/serialFilter/GlobalFilterTest.java -> https://github.com/eclipse/openj9/issues/8352
java/lang/invoke/RevealDirectTest.java -> https://github.com/eclipse/openj9/issues/8268
java/net/Inet6Address/B6206527.java (Investigating)
java/net/ipv6tests/B6521014.java (Investigating)

**Comment by archanaNogriya** [comment] 2020-01-21 11:33
3. Failure 
**Platform:**
ppc64_aix
x86-64_windows_xl
x86-64_windows
x86-64_mac_xl
x86-64_mac
x86-64_linux_xl
x86-64_linux
x86-32_windows
s390x_linux
ppc64le_linux


**Details**
sanity.openjdk failure

`TestNG] Running:
01:00:04    java/io/Serializable/serialFilter/GlobalFilterTest.java
01:00:04  
01:00:04  test GlobalFilterTest.globalFilter(): failure
01:00:04  java.lang.AssertionError: System.setProperty("jdk.serialfilter", ...) should not change filter: java.lang.StringBuffer;!*
01:00:04  	at org.testng.Assert.fail(Assert.java:94)
01:00:04  	at org.testng.Assert.assertNotEquals(Assert.java:856)
01:00:04  	at GlobalFilterTest.globalFilter(GlobalFilterTest.java:114)
01:00:04  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:00:04  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:00:04  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:00:04  	at java.lang.reflect.Method.invoke(Method.java:498)
01:00:04  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
01:00:04  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
01:00:04  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
01:00:04  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
01:00:04  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
01:00:04  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
01:00:04  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
01:00:04  	at org.testng.TestRunner.run(TestRunner.java:623)
01:00:04  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
01:00:04  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
01:00:04  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
01:00:04  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
01:00:04  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
01:00:04  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
01:00:04  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
01:00:04  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
01:00:04  	at org.testng.TestNG.run(TestNG.java:1018)
01:00:04  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
01:00:04  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
01:00:04  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:00:04  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:00:04  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:00:04  	at java.lang.reflect.Method.invoke(Method.java:498)
01:00:04  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
01:00:04  	at java.lang.Thread.run(Thread.java:821)
01:00:04  test GlobalFilterTest.setGlobalFilter(): success
01:00:04  `

**Issue Raised :** 
java/io/Serializable/serialFilter/GlobalFilterTest.java -> eclipse/openj9#8352

**Comment by archanaNogriya** [comment] 2020-01-21 11:42
4. Failure 
**Platform**
s390x_linux
x86-64_linux

**Details**
sanity.openjdk failures 

```
java/lang/invoke/RevealDirectTest.java.RevealDirectTest
13:05:48  *** FAIL: public final native java.lang.invoke.MethodHandle.invoke(Object[])Object => java.lang.AssertionError: expected:<4369> but was:<401>
13:05:48  @Test testMethodHandleInvokes/1 executed 639 positive tests in 28 ms
13:05:48  STDERR:
13:05:48  JavaTest Message: JUnit Failure: testMethodHandleInvokes(test.java.lang.invoke.RevealDirectTest): expected:<4369> but was:<401>
13:05:48  java.lang.AssertionError: expected:<4369> but was:<401>
13:05:48  	at org.junit.Assert.fail(Assert.java:93)
13:05:48  	at org.junit.Assert.failNotEquals(Assert.java:647)
13:05:48  	at org.junit.Assert.assertEquals(Assert.java:128)
13:05:48  	at org.junit.Assert.assertEquals(Assert.java:472)
13:05:48  	at org.junit.Assert.assertEquals(Assert.java:456)
13:05:48  	at test.java.lang.invoke.RevealDirectTest.consistent(RevealDirectTest.java:639)
13:05:48  	at test.java.lang.invoke.RevealDirectTest.testWithMember(RevealDirectTest.java:718)
13:05:48  	at test.java.lang.invoke.RevealDirectTest.testOnMembersImpl(RevealDirectTest.java:384)
13:05:48  	at test.java.lang.invoke.RevealDirectTest.testOnMembers(RevealDirectTest.java:357)
13:05:48  	at test.java.lang.invoke.RevealDirectTest.testMethodHandleInvokes(RevealDirectTest.java:184)
13:05:48  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:05:48  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:05:48  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:05:48  	at java.lang.reflect.Method.invoke(Method.java:498)
13:05:48  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
13:05:48  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
13:05:48  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
13:05:48  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
13:05:48  	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
13:05:48  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
13:05:48  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
13:05:48  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
13:05:48  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
13:05:48  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
13:05:48  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
13:05:48  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
13:05:48  	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
13:05:48  	at org.junit.runners.Suite.runChild(Suite.java:128)
13:05:48  	at org.junit.runners.Suite.runChild(Suite.java:24)
13:05:48  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
13:05:48  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
13:05:48  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
13:05:48  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
13:05:48  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
13:05:48  	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
13:05:48  	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
13:05:48  	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
13:05:48  	at org.junit.runner.JUnitCore.run(JUnitCore.java:127)
13:05:48  	at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:76)
13:05:48  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:76)
13:05:48  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:43)
13:05:48  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:05:48  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:05:48  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:05:48  	at java.lang.reflect.Method.invoke(Method.java:498)
13:05:48  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:05:48  	at java.lang.Thread.run(Thread.java:821)
13:05:48  
13:05:48  java.lang.Exception: JUnit test failure
13:05:48  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:92)
13:05:48  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:43)
13:05:48  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:05:48  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:05:48  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:05:48  	at java.lang.reflect.Method.invoke(Method.java:498)
13:05:48  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:05:48  	at java.lang.Thread.run(Thread.java:821)
13:05:48  
13:05:48  JavaTest Message: Test threw exception: java.lang.Exception: JUnit test failure
13:05:48  JavaTest Message: shutting down test
13:05:48  
13:05:48  STATUS:Failed.`main' threw exception: java.lang.Exception: JUnit test failure
13:05:48  rerun:
```

**Issue Raised: ** java/lang/invoke/RevealDirectTest.java -> eclipse/openj9#8268

**Comment by archanaNogriya** [comment] 2020-01-21 12:02
5. Failure

Platform
s390x_linux

Detail
sanity.openjdk
[java/rmi/activation/rmidViaInheritedChannel/InheritedChannelNotServerSocket.java.InheritedChannelNotServerSocket](https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux/104/)

```
java.rmi.server.ExportException: Port already in use: 60004; nested exception is: 
13:28:12  	java.net.BindException: Address already in use (Bind failed)
13:28:12  	at sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:346)
13:28:12  	at sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:254)
13:28:12  	at sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:412)
13:28:12  	at sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)
13:28:12  	at sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:237)
13:28:12  	at sun.rmi.registry.RegistryImpl.setup(RegistryImpl.java:213)
13:28:12  	at sun.rmi.registry.RegistryImpl.<init>(RegistryImpl.java:198)
13:28:12  	at java.rmi.registry.LocateRegistry.createRegistry(LocateRegistry.java:203)
13:28:12  	at InheritedChannelNotServerSocket.main(InheritedChannelNotServerSocket.java:91)
13:28:12  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

Rerunning this test : https://ci.adoptopenjdk.net/job/Grinder/1819/

**Comment by M-Davies** [comment] 2020-01-21 12:08
> 1. Failure
> 
> Platform
> s390x_linux
> 
> Detail
> sanity.openjdk
> [java/rmi/activation/rmidViaInheritedChannel/InheritedChannelNotServerSocket.java.InheritedChannelNotServerSocket](https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux/104/)
> 
> ```
> java.rmi.server.ExportException: Port already in use: 60004; nested exception is: 
> 13:28:12  	java.net.BindException: Address already in use (Bind failed)
> 13:28:12  	at sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:346)
> 13:28:12  	at sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:254)
> 13:28:12  	at sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:412)
> 13:28:12  	at sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)
> 13:28:12  	at sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:237)
> 13:28:12  	at sun.rmi.registry.RegistryImpl.setup(RegistryImpl.java:213)
> 13:28:12  	at sun.rmi.registry.RegistryImpl.<init>(RegistryImpl.java:198)
> 13:28:12  	at java.rmi.registry.LocateRegistry.createRegistry(LocateRegistry.java:203)
> 13:28:12  	at InheritedChannelNotServerSocket.main(InheritedChannelNotServerSocket.java:91)
> 13:28:12  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> ```
> 
> Rerunning this test : https://ci.adoptopenjdk.net/job/Grinder/1819/

This test is excluded in HS and J9 on MacOSX but not Z. https://bugs.openjdk.java.net/browse/JDK-8170562 looks like it could be a similar issue

**Comment by smlambert** [comment] 2020-01-21 12:59
> sanity.external
Failures with:
thorntail-mp-tck_x86-64_linux: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.external_thorntail-mp-tck_x86-64_linux/214/
tomee_x86-64_linux: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.external_tomee_x86-64_linux/173/
(Seen on hotspot, non-blocking. @ShelleyLambert would this be counted as reproduced?)

yes, these will be considered non-blocking, same reason as for hotspot, appears to be test setup issue (related: https://github.com/AdoptOpenJDK/TSC/issues/135#issuecomment-576273558)

**Comment by adam-thorpe** [comment] 2020-01-21 13:22
> All 27 targets are failing with a no such file or directory error (thanks google translate), suggesting a test setup issue.
Perhaps similar to the system test failure on aix? https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.system_ppc64_aix/3/tapResults/

**Comment by adam-thorpe** [comment] 2020-01-21 13:36
**6. Failure**
**Platform:**
x64_mac
x64_mac_xl

**sanity.openjdk**
java/lang/Runtime/loadLibrary/LoadLibraryTest.java -> https://github.com/eclipse/openj9/issues/8287

**Comment by adam-thorpe** [comment] 2020-01-21 14:08
**6. Failure**
**Platform:**
x64_mac_xl

**sanity.openjdk**
java/net/Inet6Address/B6206527.java.B6206527
java/net/InetAddress/CheckJNI.java.CheckJNI
java/net/Socket/LinkLocal.java.LinkLocal
java/net/ipv6tests/B6521014.java.B6521014
java/net/ipv6tests/TcpTest.java.TcpTest
Known issue on test-macincloud-macos1014-x64-2 -> https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1085

**Comment by M-Davies** [comment] 2020-01-21 14:17
> > special.functional
> > 27 Failures: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.functional_x86-64_linux/131/
> 
> These were consistently passing until Jan 10th, at which point they began consistently failing. We need to look and see what changed in that timeframe (machines or tests or jdk)?
> 
> bash: /home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../../jvmtest/functional/MBCS_Tests/jdbc41/test.sh: 그런 파일이나 디렉터리가 없습니다.
> 
> All 27 targets are failing with a no such file or directory error (thanks google translate), suggesting a test setup issue.

Potential Breaking Changes

Test
- https://github.com/AdoptOpenJDK/TKG/commit/5234a60fc3e41a2011378a698ba8b890b55aeeef was pushed on Jan 9, 2020 and the only change on TKG. Removal of deprecated -XX:StartAsJITServer option
JDK
- Noticed `[WARNING] Reference path does not exist: /home/jenkins/openjdk_cache` in the console log.

**Comment by lumpfish** [comment] 2020-01-22 12:49
> > All 27 targets are failing with a no such file or directory error (thanks google translate), suggesting a test setup issue.
> 
> Perhaps similar to the system test failure on aix? https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.system_ppc64_aix/3/tapResults/

I don't think so.  That was due to the test build failing to determine the platform by parsing the java -XshowSettings:properties output for the value of the jdk system property os.name.  It's not clear why it couldn't determine that - the tests ran ok on a grinder rerun.

**Comment by lumpfish** [comment] 2020-01-22 13:12
openj9 have created a new release tag openj9-0.18.1 with a fix for eclipse/openj9#8352.
The builds are being rerun - if successful this time the release will be jdk8u242-b08_openj9-0.18.1

**Comment by lumpfish** [comment] 2020-01-22 13:30
Regarding the 27 MBCS test failures, the new test runs (jdk8u242-b08_openj9-0.18.1) on x86 linux are failing with the message in English:
```
11:06:54  bash: /home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../../jvmtest/functional/MBCS_Tests/scanner/test.sh: No such file or directory
11:06:54  
11:06:54  MBCS_Tests_scanner_ja_JP_linux_0_FAILED
```
Full output in: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.functional_x86-64_linux/132/consoleFull
Shouldn't the script location be:
```
/home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests//functional/MBCS_Tests/scanner/test.sh
```
?

**Comment by smlambert** [comment] 2020-01-22 15:02
MBCS_Tests, that may be caused by a change to the job config that I made to try and work around the open infra issue (regarding ant version being too old on certain machines which causes functional test compilation to fail).  I will update the job config, but if the machines are not updated, and this particular job lands on it, build step fails.

**Comment by adam-thorpe** [comment] 2020-01-23 09:39
jdk8u242-b08_openj9-0.18.1 Triage:
**1. New Failure**
**Platform**
openliberty-mp-tck_x86-64_linux
```
11:50:31  Unhandled exception
11:50:31  Type=Segmentation error vmState=0x00000000
11:50:31  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
11:50:31  Handler1=00007FDD9D1F1030 Handler2=00007FDD9CADC090 InaccessibleAddress=0000000000000008
11:50:31  RDI=0000000000000000 RSI=0000000000000000 RAX=0000000000000000 RBX=0000000001AD8F08
11:50:31  RCX=0000000000000021 RDX=0000000000000022 R8=00007FDD980102B0 R9=0000000000000022
11:50:31  R10=0000000000000074 R11=0000000000000048 R12=0000000001852100 R13=0000000000000000
11:50:31  R14=0000000000000000 R15=0000000000000044
11:50:31  RIP=00007FDD9D16CD8A GS=0000 FS=0000 RSP=00007FDD9500F640
11:50:31  EFlags=0000000000010246 CS=0033 RBP=00000000FCE3C790 ERR=0000000000000004
11:50:31  TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000008
11:50:31  xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
11:50:31  xmm1 0000000049bf63f8 (f: 1237279744.000000, d: 6.112974e-315)
11:50:31  xmm2 00007fdd9500fa00 (f: 2499869184.000000, d: 6.946052e-310)
11:50:31  xmm3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
11:50:31  xmm4 43e0000000000000 (f: 0.000000, d: 9.223372e+18)
11:50:31  xmm5 000000003e305c9d (f: 1043356800.000000, d: 5.154868e-315)
11:50:31  xmm6 000000004a94b47a (f: 1251259520.000000, d: 6.182043e-315)
11:50:31  xmm7 4030beba2bb4ef11 (f: 733277952.000000, d: 1.674503e+01)
11:50:31  xmm8 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
11:50:31  xmm9 4030beba8555c8c4 (f: 2236991744.000000, d: 1.674503e+01)
11:50:31  xmm10 3fecae55961f5015 (f: 2518634496.000000, d: 8.962810e-01)
11:50:31  xmm11 bcd2c00000000000 (f: 0.000000, d: -1.040834e-15)
11:50:31  xmm12 3c5b000000000000 (f: 0.000000, d: 5.854692e-18)
11:50:31  xmm13 4030a2b23f3baa00 (f: 1060874752.000000, d: 1.663553e+01)
11:50:31  xmm14 3bf52b7dbbf7c9d1 (f: 3153578496.000000, d: 7.172637e-20)
11:50:31  xmm15 4030a2b23f3baa00 (f: 1060874752.000000, d: 1.663553e+01)
11:50:31  Module=/opt/java/openjdk/jre/lib/amd64/compressedrefs/libj9vm29.so
11:50:31  Module_base_address=00007FDD9D158000
11:50:31  Target=2_90_20200119_507 (Linux 4.4.0-159-generic)
11:50:31  CPU=amd64 (4 logical CPUs) (0x1f225e000 RAM)
11:50:31  ----------- Stack Backtrace -----------
11:50:31  (0x00007FDD9D16CD8A [libj9vm29.so+0x14d8a])
11:50:31  (0x00007FDD9D16A700 [libj9vm29.so+0x12700])
11:50:31  (0x00007FDD9D22BE22 [libj9vm29.so+0xd3e22])
11:50:31  ---------------------------------------
11:50:31  JVMDUMP039I Processing dump event "gpf", detail "" at 2020/01/22 11:50:30 - please wait.
11:50:31  JVMDUMP032I JVM requested System dump using '/root/.gradle/workers/core.20200122.115030.656.0001.dmp' in response to an event
11:50:33  JVMDUMP010I System dump written to /root/.gradle/workers/core.20200122.115030.656.0001.dmp
11:50:33  JVMDUMP032I JVM requested Java dump using '/root/.gradle/workers/javacore.20200122.115030.656.0002.txt' in response to an event
11:50:33  JVMDUMP010I Java dump written to /root/.gradle/workers/javacore.20200122.115030.656.0002.txt
11:50:33  JVMDUMP032I JVM requested Snap dump using '/root/.gradle/workers/Snap.20200122.115030.656.0003.trc' in response to an event
11:50:34  JVMDUMP010I Snap dump written to /root/.gradle/workers/Snap.20200122.115030.656.0003.trc
11:50:34  JVMDUMP007I JVM Requesting JIT dump using '/root/.gradle/workers/jitdump.20200122.115030.656.0004.dmp'
11:50:43  JVMDUMP010I JIT dump written to /root/.gradle/workers/jitdump.20200122.115030.656.0004.dmp
11:50:43  JVMDUMP013I Processed dump event "gpf", detail "".
11:50:43  
11:50:43  FAILURE: Build failed with an exception.
11:50:43  
11:50:43  * What went wrong:
11:50:43  Execution failed for task ':com.ibm.ws.jaxrs.2.0_fat:compileJava'.
11:50:43  > Failed to run Gradle Worker Daemon
11:50:43     > Process 'Gradle Worker Daemon 2' finished with non-zero exit value 255
```

**Comment by adam-thorpe** [comment] 2020-01-23 09:46
**2. Failure**
**Platform**
ppc64 aix

**sanity.openjdk**
java/lang/ProcessBuilder/Basic.java (needs investigating)

**Comment by adam-thorpe** [comment] 2020-01-23 09:50
**3. Failure**
**Platform**
ppc64le linux

**sanity.openjdk**
Jenkins clean-up failed but all of the tests ran and completed.
Failures:
java/lang/invoke/RevealDirectTest.java -> https://github.com/eclipse/openj9/issues/8268
java/net/Inet6Address/B6206527.java
java/net/ipv6tests/B6521014.java
java/net/MulticastSocket/SetOutgoingIf.java

**Comment by adam-thorpe** [comment] 2020-01-23 09:53
**4. New Failure**
**Platform**
s390x_linux_xl

**sanity.system**
TestJlmRemoteThreadNoAuth_SE80_Linux_0
```
Step 7 - Wait for processes to complete
STF 08:26:22.136 - **FAILED** Process CL2 has timed out
CL2 stderr java.rmi.UnmarshalException: Error unmarshaling return header; nested exception is: 
CL2 stderr 	java.io.EOFException
CL2 stderr 	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:254)
CL2 stderr 	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
CL2 stderr 	at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
CL2 stderr 	at javax.management.remote.rmi.RMIConnectionImpl_Stub.invoke(Unknown Source)
CL2 stderr 	at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.invoke(RMIConnector.java:1020)
CL2 stderr 	at net.adoptopenjdk.test.jlm.resources.ThreadData.writeData(ThreadData.java:611)
CL2 stderr 	at net.adoptopenjdk.test.jlm.remote.ThreadProfiler.getStatsViaServer(ThreadProfiler.java:197)
CL2 stderr 	at net.adoptopenjdk.test.jlm.remote.ThreadProfiler.main(ThreadProfiler.java:99)
CL2 stderr Caused by: java.io.EOFException
CL2 stderr 	at java.io.DataInputStream.readByte(DataInputStream.java:267)
CL2 stderr 	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:240)
CL2 stderr 	... 7 more
CL2 stderr Exception in thread "main" java.lang.AssertionError: Error unmarshaling return header; nested exception is: 
CL2 stderr 	java.io.EOFException
CL2 stderr 	at org.junit.Assert.fail(Assert.java:88)
CL2 stderr 	at net.adoptopenjdk.test.jlm.resources.ThreadData.writeData(ThreadData.java:727)
CL2 stderr 	at net.adoptopenjdk.test.jlm.remote.ThreadProfiler.getStatsViaServer(ThreadProfiler.java:197)
CL2 stderr 	at net.adoptopenjdk.test.jlm.remote.ThreadProfiler.main(ThreadProfiler.java:99)
```

**Comment by adam-thorpe** [comment] 2020-01-23 09:54
**5. Failures**
**Platform**
thorntail-mp-tck_x86-64_linux
tomee_x86-64_linux

Known Failures, non blocking

**Comment by adam-thorpe** [comment] 2020-01-23 09:56
**6. Failures**
**Platform**
x86-64_linux

**special.functional**
Known -> https://github.com/AdoptOpenJDK/openjdk-tests/issues/1567#issuecomment-576676676

**Comment by M-Davies** [comment] 2020-01-23 09:59
**6. Failures**
**Platform**
x86-64_mac

**sanity.openjdk**
Known -> https://github.com/eclipse/openj9/issues/8287

**Comment by adam-thorpe** [comment] 2020-01-23 10:00
**7. Failures**
**Platforms**
x86-64_mac
x86-64_mac_xl

**sanity.openjdk**
java/lang/Runtime/loadLibrary/LoadLibraryTest.java -> https://github.com/eclipse/openj9/issues/8287


**8. Failure**
**Platform**
x86-64_mac_xl

**sanity.openjdk**
java/lang/invoke/RevealDirectTest.java -> eclipse/openj9#8268

**Comment by M-Davies** [comment] 2020-01-23 10:13
> **2. Failure**
> **Platform**
> ppc64 aix
> 
> **sanity.openjdk**
> java/lang/ProcessBuilder/Basic.java (needs investigating)

Has been raised by @lumpfish in the past for the same error https://github.com/AdoptOpenJDK/openjdk-tests/issues/1397

**Comment by adam-thorpe** [comment] 2020-01-23 10:13
**9. Failure**
**Platform**
x86-64_mac

**extended.system**
Jenkins error, seen before.
Resubmitted -> https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1836/

**Comment by adam-thorpe** [comment] 2020-01-23 11:58
@smlambert could you take a look into the openliberty build crash at 1) please? Other than that all of the other failures look non-blocking to me

**Comment by M-Davies** [comment] 2020-01-23 13:13
> **3. New Failures**
> **Platform**
> ppc64le linux
> 
> **sanity.openjdk**
> Jenkins clean-up failed but all of the tests ran and completed.
> Failures:
> java/net/MulticastSocket/SetOutgoingIf.java

SetOutgoingIf.java appeared to a one off, very intermittent failure. This can be considered non blocking

**Comment by lumpfish** [comment] 2020-01-23 14:06
Regarding the new issue eclipse/openj9#8382 - the difference between openj9-0.18.0 and openj9-0.18.1 could not have caused the crash, so the failure must be intermittent and low frequency (the test passed with the openj9-0.18.0 release and in many nightly builds before that).  It should not be regarded as blocking.

**Comment by smlambert** [comment] 2020-01-23 14:56
re: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1567#issuecomment-577650872

That is the first time we have seen a crash in that test.  2 things to note:
- its crashing while trying to compile the openliberty test material
- looking at console output, there are some setup failures early on:

[2020-01-22T11:11:06.106Z] Fetching artifact gives error org/apache/cxf/cxf-rt-ws-mex/2.6.2-ibm-s20180529-1900/cxf-rt-ws-mex-2.6.2-ibm-s20180529-1900.jar : 500 TaggedData [tag=null, code=500, modified=Thu Jan 01 00:00:00 GMT 1970, url=http://public.dhe.ibm.com/ibmdl/export/pub/software/olrepo/org/apache/cxf/cxf-rt-ws-mex/2.6.2-ibm-s20180529-1900/cxf-rt-ws-mex-2.6.2-ibm-s20180529-1900.jar, state=OTHER, msg=
[2020-01-22T11:11:06.106Z] 500 Internal Server Error

We can retry this test, to see that without this spurious network failure things work fine.  (IMHO things should not crash due to artifacts missing... but that may be something we report to upstream (to not proceed into compilation stage, if artifact fetch fails), should look more closely and report if need be.

**Comment by M-Davies** [comment] 2020-01-23 15:58
The 500 server error shouldn't affect the result of the test. Looking at the 0.18.0 run, the same server error was present there but the test passed (no mention of a compileJava error) 
```
12:40:25  Fetching artifact gives error org/apache/aries/blueprint/org.apache.aries.blueprint/1.3.0-ibm-s20170710-0926/org.apache.aries.blueprint-1.3.0-ibm-s20170710-0926.jar : 500 TaggedData [tag=null, code=500, modified=Thu Jan 01 00:00:00 GMT 1970, url=http://public.dhe.ibm.com/ibmdl/export/pub/software/olrepo/org/apache/aries/blueprint/org.apache.aries.blueprint/1.3.0-ibm-s20170710-0926/org.apache.aries.blueprint-1.3.0-ibm-s20170710-0926.jar, state=OTHER, msg=
12:40:25  500 Internal Server Error
```
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.external_openliberty-mp-tck_x86-64_linux/214/consoleFull

**Comment by smlambert** [comment] 2020-02-22 17:43
Release triage was completed with issues raised for identified problems, closing this now.

**Closed by smlambert** 2020-02-22 17:43 UTC
Labels: release triage
